### ISSUE TITLE
Missing `analysis-overlay` icon in latest 1.0.4

### ISSUE THREAD

**Issue by subgan82** [Esri/calcite-components#6440] opened 2023-02-08 16:29 UTC
## Actual Behavior

Map Viewer Updated to calcite version 1.0.4 today we were looking for updated `analysis-overlay` icon which is now not rendering on our development site.

https://github.com/Esri/calcite-components/blob/master/package.json#L86https://github.com/Esri/calcite-ui-icons/blob/v3.21.0/icons/analysis-overlay-32.svg same name we use it should have updated with the latest version

https://github.com/Esri/calcite-components/blob/master/package.json#L49 it gets copied and it is a dependency for calcite components https://github.com/Esri/calcite-components/blob/master/package.json#L86

![Screenshot 2023-02-08 at 10 49 09 AM](https://user-images.githubusercontent.com/1017712/217586879-87f8692c-ae29-42cb-9b92-4e701ba4061a.png)
<img width="935" alt="Screenshot 2023-02-08 at 10 50 29 AM" src="https://user-images.githubusercontent.com/1017712/217586885-02d76038-5d69-45fa-8971-96a8c6fb0f5a.png">
![Screenshot 2023-02-08 at 11 02 10 AM](https://user-images.githubusercontent.com/1017712/217586887-295cadbd-ac26-4f7e-9cef-ff60f4900834.png)
<img width="1428" alt="Screenshot 2023-02-08 at 11 06 36 AM" src="https://user-images.githubusercontent.com/1017712/217586891-cafaa70b-c5a5-49b4-b040-4ca0ab1bc5e6.png">

It is missing in the `assets` folder of the calcite-components distributable as seen from the `404 network request`

## Expected Result 

Icon should render as follows 

https://github.com/Esri/calcite-components/blob/master/package.json#L86https://github.com/Esri/calcite-ui-icons/blob/v3.21.0/icons/analysis-overlay-32.svg 

![Screenshot 2023-02-08 at 11 02 10 AM](https://user-images.githubusercontent.com/1017712/217587026-6c0e835e-fd9a-462d-96a7-5df2c77d6ffb.png)

## Sample 

https://codepen.io/subgan82/pen/bGjyKbm

1. check out the code pen above to see the `analysis-overlay` icon is not rendering. 

2. Same issue can be seen logging into mapviewer on our development site

Seen in version `1.0.4` regression from `1.0.3`. This is a show stopper releasing analysis in map viewer in R01

**Comment by geospatialem** [comment] 2023-02-08 16:39
This issue relates to a new icon added in [@esri/calcite-ui-icons/v/3.21.0](https://www.npmjs.com/package/@esri/calcite-ui-icons/v/3.21.0).

While not a regression, this is a high priority fix needed by the Map Viewer team for the upcoming release.

**Comment by subgan82** [comment] 2023-02-08 16:50
Hi @geospatialem 

https://github.com/Esri/calcite-components/blob/v1.0.4/package.json#L86  1.0.4 version is using 3.21.0 version of calcite-icons

**Comment by ethanbdev** [comment] 2023-02-08 17:52
It seems like the icon is also missing from `calcite-ui-icons` https://www.npmjs.com/package/@esri/calcite-ui-icons?activeTab=explore

@paulcpederson is possibly taking a look

**Comment by paulcpederson** [comment] 2023-02-08 17:58
@geospatialem @benelan so it looks like the automated publishing of the calcite icons is not working. None of the last three versions were actually pushed to npm. 

I've manually published 3.21.2, so if calcite updates to that this should solve the problem.

**Comment by benelan** [comment] 2023-02-08 17:59
The automated publish is still waiting for your final review, I think @SkyeSeitz has been releasing?
https://github.com/Esri/calcite-ui-icons/pull/243

**Comment by paulcpederson** [comment] 2023-02-08 18:01
Welp, that would explain it. I bet she's been out or forgot (or maybe thought that pr got merged like I did...)

**Comment by paulcpederson** [comment] 2023-02-08 18:06
OK, pr merged so hopefully icons will get published automatically now. Can we get another calcite patch with the new icon version?

**Comment by geospatialem** [comment] 2023-02-08 18:28
> OK, pr merged so hopefully icons will get published automatically now. Can we get another calcite patch with the new icon version?

We're planning on another patch, targeted for later this week. cc @jcfranco

**Comment by geospatialem** [comment] 2023-02-09 14:56
Verified in `1.0.5`

![image](https://user-images.githubusercontent.com/5023024/217847850-336d6dac-8ee6-43c2-8359-1e54fba43a12.png)

**Closed by geospatialem** 2023-02-09 14:56 UTC
Labels: bug, p - high, 4 - verified, ArcGIS Map Viewer
