### ISSUE TITLE
[Dropdown] Unwanted scrolling when max-items >= number of dropdown items

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4880] opened 2022-07-08 17:40 UTC
### Actual Behavior

When `max-items` is used on `calcite-dropdown`, and the value equals or exceeds the number of `calcite-dropdown-items`, a small bit of unwanted scrolling appears in the dropdown container.

### Expected Behavior

There is no extra scrolling when the number of dropdown items is equal to or less than the `max-items` value

### Reproduction Sample

https://codepen.io/mac_and_cheese/pen/WNzwzwa?editors=1000

### Reproduction Steps

1 - Go to codepen
2 - See the extra scrolling in the two examples with max-items set

### Reproduction Version

83

**Comment by geospatialem** [comment] 2022-09-08 23:36
The scrollbar is fixed with smaller `max-item` numbers, but when `max-items` is set to 8 or greater the scroller seems to still be added in. 

It looks like this is a regression, last working in `beta.74`. @driskull, can you take a look? 

- [`next`](https://codepen.io/geospatialem/pen/zYjrgeY) - scrollbar present when it shouldn't be
- [`beta.74`](https://codepen.io/geospatialem/pen/PoeZMxO) - expected behavior

**Comment by driskull** [comment] 2022-09-08 23:39
@geospatialem the scrollbar is still dependent on the window size as well. That might be the reason for it. It has a max height of `45vh`.

**Comment by geospatialem** [comment] 2022-09-09 14:14
Thanks @driskull for the background! Was able to get the list without the scrollbar when opening in a larger window. Marking this as verified. ✔️

**Closed by geospatialem** 2022-09-09 14:14 UTC
Labels: bug, 3 - installed
