### ISSUE TITLE
Bug: calcite-input-time-picker - when to show ':00' for seconds

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2329] opened 2021-06-17 20:27 UTC
### Actual Behavior

It’s not consistent about when it displays the seconds or not. If I just clicked the seconds arrows and set it to 00 it stays on. If I click the arrows for minutes or hours the seconds display goes away. I don’t really care one way or another if seconds is set to 00, but it should be the same in all cases.

![image](https://user-images.githubusercontent.com/44481292/122467627-9c910000-cf6f-11eb-9ea1-bf875e22c427.png)

### Expected Behavior

same behavior in all cases

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by driskull** [comment] 2021-07-26 16:17
@AdelheidF I'm not able to reproduce this. Do you have a sample?

**Comment by eriklharper** [comment] 2021-07-26 19:32
Closing this in favor of a new `calcite-input-time` component which will solve this issue by showing the seconds field when the `step` field is less than `60`.

https://github.com/Esri/calcite-components/issues/2331#issuecomment-886963949

**Closed by eriklharper** 2021-07-26 19:32 UTC
Labels: 0 - new, bug, help wanted
