### ISSUE TITLE
calcite-date triggers calciteDateChange event unexpectedly

### ISSUE THREAD

**Issue by codylawson** [Esri/calcite-components#722] opened 2020-07-10 23:40 UTC
Programmatically changing the date value provided to the `calcite-date` element causes `calciteDateChange` to be fired. This seems to be a bug and the event should only fire when a user interacts with the date picker UI.

**Comment by paulcpederson** [comment] 2020-10-05 23:44
@codylawson fix for this should be in the latest release.

**Closed by paulcpederson** 2020-10-05 23:44 UTC
Labels: 3 - installed, bug 🐞, component-date

**Comment by codylawson** [comment] 2020-10-06 16:11
@paulcpederson Awesome! Thanks for resolving this.

**Comment by codylawson** [comment] 2020-11-10 23:19
@paulcpederson This seems to have been reverted in the latest release. We're now getting update events from the date picker when the value is changed programatically.

**Comment by paulcpederson** [comment] 2020-11-10 23:45
@jcfranco was there something weird with the last release? I don't see any changes in this file that would have impacted this regression?

**Comment by jcfranco** [comment] 2020-11-10 23:55
I don't think think so, at least the most recent commit. All tests were passing. Do you have a repro case? We could use it to `git bisect` the culprit and maybe add another test.

**Comment by codylawson** [comment] 2020-11-11 16:36
@jcfranco I'll work on a repro case for you. We did revert to beta 42 and are no longer seeing the issue, so it seems something happened in the last two releases.

**Comment by codylawson** [comment] 2020-11-11 17:45
@jcfranco Could you give this a shot? https://codesandbox.io/s/gracious-sky-2772j?file=/src/components/HelloWorld.vue

Noticing I get two change events when setting the date via the date picker, and another one when I click the button. If you think there's a better way handle a controlled date picker let me know! Thanks

**Comment by jcfranco** [comment] 2020-11-11 17:59
I think I'm missing something, but I see all of the events you describe with beta 40 – 44.

**Comment by codylawson** [comment] 2020-11-11 18:08
Sorry, I should have removed the reference from package.json, I'm using the library from unpkg. Here's two forks with [beta.42](https://codesandbox.io/s/cc-date-picker-beta42-2772j) and [beta.44](https://codesandbox.io/s/cc-date-picker-beta44-t3xht)

**Comment by jcfranco** [comment] 2020-11-11 18:47
Got it, thanks! I managed to repro w/ beta 43, so I think the issue is in one of these: https://github.com/Esri/calcite-components/compare/v1.0.0-beta.42...v1.0.0-beta.43. 

@codylawson Do you have a non-Vue repro case by any chance? This will help us `git bisect` the culprit.

**Comment by codylawson** [comment] 2020-11-11 19:54
@jcfranco I do not, would a react example be useful or does that have a similar problem as Vue?

**Comment by codylawson** [comment] 2020-12-09 18:16
@jcfranco while testing `next.56` I noticed this bug is no longer reproducible. Hoping that's expected 🎉

**Comment by paulcpederson** [comment] 2020-12-09 18:20
@codylawson simplified the date component render cycle for #1111  maybe that also solved this issue
