### ISSUE TITLE
Slider thumb position oddly depends on the document font size

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-components#5766] opened 2022-11-16 09:51 UTC
### Actual Behavior

When the thumb label is visible, the thumb position depends on the document font size.
For small fonts it's shifted up.

![image](https://user-images.githubusercontent.com/5318527/202147210-d39dd9be-ede8-4885-9e3c-6d502bca65d9.png)

For large fonts it's shifted down.

![image](https://user-images.githubusercontent.com/5318527/202147638-b95708a3-6a75-41ea-adc9-5386feecc4fa.png)

### Expected Behavior

The thumb position must not depend on the document font size.

### Reproduction Sample

https://codepen.io/cont-kolomeets/pen/gOKxJLO?editors=1000

https://codepen.io/cont-kolomeets/pen/GRGvaWK?editors=1000

### Reproduction Steps

See the samples.

### Reproduction Version

beta.98

### Esri team

ArcGIS Business/Community Analyst

**Comment by jcfranco** [comment] 2023-02-27 21:53
This seems to be a duplicate of https://github.com/Esri/calcite-components/issues/4721.

**Comment by geospatialem** [comment] 2023-02-28 00:19
This is verified as mitigated in `1.0.8-next.1`.

![image](https://user-images.githubusercontent.com/5023024/221719349-cf58fb4f-e7b7-4269-9b00-43cc0ca7b1ed.png)

**Closed by geospatialem** 2023-02-28 00:19 UTC
Labels: bug, 4 - verified, needs triage, ArcGIS Business/Community Analyst
