### ISSUE TITLE
PickList and ValueList - add position definition for slotted Dropdown

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-components#3725] opened 2021-12-15 22:22 UTC
### Actual Behavior
In Firefox and Safari, when a Dropdown is added to the `menu-actions` slot of PickList (and ValueList), the Dropdown's position doesn't respect the `sticky` position of the header.

![image](https://user-images.githubusercontent.com/44481292/149390995-e13d0cd4-3e17-461a-82dc-a846143bb2b5.png)

### Expected Behavior
Dropdown should stay sticky with the header.
Solution appears to be simply adding `position: relative` to a Dropdown that is in the `menu-actions` slot.

### Reproduction Steps and Sample

_Sample_: https://codepen.io/afreitag/pen/vYegbbg?editors=1000

Note: we're not able to repro in a Codepen, but it's happening in Feature Specific effects in Map Viewer. See attached gif.

1. In FF or Safari, open the filter next to the search field
2. scroll

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-<version>`

- [ ] CDN
- [ ] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

**Comment by asangma** [comment] 2021-12-29 19:05
@benelan Mind if we push up the priority on this?

**Comment by benelan** [comment] 2021-12-29 19:55
I put it in the next sprint @asangma

**Comment by y0n4** [comment] 2022-01-12 22:41
Hi, could you include an attached gif? Thanks!

**Comment by jcfranco** [comment] 2022-02-18 19:47
This is blocked by #3815.

**Comment by geospatialem** [comment] 2022-04-22 15:20
There are a few blockers associated with this fix, including (Feb 18): 

> This is blocked by #3815.

Additional R&D has determined fixing for picklist and valuelist, creates a break for others.

**Comment by AdelheidF** [comment] 2022-05-02 19:24
I would like to point out here how big of a problem this is in just the Map Viewer application. (I probably didn't catch all scenarios.)

Field picker used in Effects (shown here), Table, Styles, Filter, Labels, FeatureDisplayOrder components
![picklist](https://user-images.githubusercontent.com/44481292/166306789-02244383-e119-4462-9e0b-e5b122329c75.gif)

Unique values picker in Filter component, which is also used in Effects, Labels, Clustering component
![picklist2](https://user-images.githubusercontent.com/44481292/166306806-22db59af-0dcb-43d6-a081-1ce7ffd7357f.gif)

Symbol picker in Sketch and Styles components
<img src=https://user-images.githubusercontent.com/44481292/166304782-e6ff9ebc-e429-4a07-b270-596fb9b88fb8.png width=250/><img src=https://user-images.githubusercontent.com/44481292/166308306-24ae0614-996c-45c1-9dbb-679b87aada96.png width=250/>

List in Charts component
<img src=https://user-images.githubusercontent.com/44481292/166308578-e15114e3-c1d1-462f-b3ef-91be7046fbf3.png width=250/>

**Comment by AdelheidF** [comment] 2022-06-20 23:57
workaround

![image](https://user-images.githubusercontent.com/44481292/174690357-34958ef6-d9f0-4001-829b-d716c94785cc.png)

**Comment by jcfranco** [comment] 2022-08-09 18:56
The latest version of `floating-ui` has fixes for shadow DOM positioning (see https://github.com/Esri/calcite-components/issues/3815#issuecomment-1201698447). I couldn't test w/ the original codepen since it doesn't reproduce the issue, but based on other, similar issues, this may be fixed. @AdelheidF @subgan82 Would either of you be able to test w/ `@next`?

**Comment by AdelheidF** [comment] 2022-08-09 19:06
Actually with the upgrade to beta.86 we had to remove all those `position:relative` to make it work properly again.

**Comment by benelan** [comment] 2022-08-10 23:13
I can't repro the issue using the sample Alan provided. `beta.91` just released, can someone who can repro in MV please test?

**Comment by AdelheidF** [comment] 2022-08-12 22:11
Will test this with beta.92...

**Comment by AdelheidF** [comment] 2022-08-24 22:05
works fine with beta.93

**Comment by geospatialem** [comment] 2022-10-04 19:37
Verified in August - Closing. 🚀

**Closed by geospatialem** 2022-10-04 19:37 UTC
Labels: bug, p - high, 4 - verified, blocked, milestone adjusted, has workaround
