### ISSUE TITLE
Bug: calcite-label not removing original textNode

### ISSUE THREAD

**Issue by mpriour** [Esri/calcite-components#1178] opened 2020-10-27 15:12 UTC
### Summary
The caclite-label text is repeated. The text node inside a the calcite-label element is not getting replaced, thus 2 "labels" are being shown. The first is wrapped in a span inside a label element while the second is a plain text node that was supposed to get removed.

### Actual Behavior
Here is the markup that is being produced:
```html
<calcite-label class="sc-calcite-label-h sc-calcite-label-s" dir="ltr" status="idle" scale="m" layout="default"><!---->
<label class="sc-calcite-label-h sc-calcite-label-s sc-calcite-label">
<span class="calcite-label-text">URL</span>
</label>
URL
<calcite-input id="sourceInput" name="source" type="text" prefix-text="https://" class="sc-calcite-input-h sc-calcite-input-s" dir="ltr" alignment="start" number-button-type="vertical" scale="m" status="idle" value=""><!---->
...
</calcite-input>
</calcite-label>
```

### Expected Behavior
In the expected markup produced from the component, the `URL` textNode should be removed
```html
<calcite-label class="sc-calcite-label-h sc-calcite-label-s" dir="ltr" status="idle" scale="m" layout="default"><!---->
<label class="sc-calcite-label-h sc-calcite-label-s sc-calcite-label">
<span class="calcite-label-text">URL</span>
</label>
<calcite-input id="sourceInput" name="source" type="text" prefix-text="https://" class="sc-calcite-input-h sc-calcite-input-s" dir="ltr" alignment="start" number-button-type="vertical" scale="m" status="idle" value=""><!---->
...
</calcite-input>
</calcite-label>
```

### Reproduction Steps

1. Here is the original markup that produced that result:
```html
<calcite-label scale="m">URL
     <calcite-input id="sourceInput" name="source" scale="m" type="text" prefix-text="https://">
     </calcite-input>
</calcite-label>
```

### Relevant Info 

This effect is happening in nearly all my labels on my form in a Preact project using preact 10.5.4, typescript 4.0.3, and calcite-components 1.0.0-beta.42

**Comment by eriklharper** [comment] 2020-10-27 16:25
Dupe of #1140

**Comment by eriklharper** [comment] 2020-10-28 00:01
Having trouble reproducing this.  @mpriour if you could share the repository where this issue is happening so I can try and replicate locally, that will help move this along.

**Comment by mpriour** [comment] 2020-11-10 16:38
@eriklharper I've gotten a chance to loop back around to this. The project this is happening in is a "wizard" style form that uses a stepper to walk a user through the relevant choices.

I've created a very simplified version of this at https://github.com/mpriour/cc_preact.

I noticed that even in this simplified version the double labeling happens every time that the page is re-rendered.
In this example app it would be whenever you make a radio button choice or "blur" an input field.

**Comment by mpriour** [comment] 2020-11-10 16:45
@eriklharper The markup for the initial radio button choice screen is in https://github.com/mpriour/cc_preact/blob/main/src/components/SubTypes/AppSubType.tsx

The markup for the input form is in https://github.com/mpriour/cc_preact/blob/main/src/components/ListingDetails/ListingDetails.tsx

**Closed** 2020-12-18 23:47 UTC
Labels: 0 - new, 1 - assigned, 2 - in development, bug
