### ISSUE TITLE
Bug: Selected date in input-date-picker displays in incorrect format for Bosnian in Chrome

### ISSUE THREAD

**Issue by BlakeStearman** [Esri/calcite-components#4583] opened 2022-05-18 22:41 UTC
### Actual Behavior

A selected date in an instance of `input-date-picker` set to the Bosnian locale shows in the incorrect date format of `YYYY-MM-DD`. The placeholder value before you select a date shows the correct format of `DD. MM. YYYY.`. This only occurs in Chrome. Firefox and Edge (Chromium) seem to display the selected date in the expected format of `DD. MM. YYYY.`.

### Expected Behavior

The selected date in Chrome should display in the same format the placeholder indicates, "DD. MM. YYYY.".

### Reproduction Sample

https://codepen.io/bstearman/pen/ExQmZXP

### Reproduction Steps

In Chrome browser:
1. Load instance of `input-date-picker` with `locale` property set to `"bs"`.
2. Note that the `input-date-picker` shows the `placeholder` format correctly as `DD. MM. YYYY.`.
3. Open calendar and select a date.
4. Observe that the date value doesn't follow the expected format of `DD. MM. YYYY.`, but instead follows a format of `"YYYY-MM-DD"`.

Note that Firefox and Edge (Chromium) display the selected date in the expected format of `DD. MM. YYYY.`

### Reproduction Version

beta.82 

### Relevant Info

Only occurs on Chrome browser.

Firefox and Edge (Chromium) seem to render the selected date according to the expected format.

### Regression?

No

**Comment by anveshrmekala** [comment] 2022-06-13 22:11
The issue is related to chrome browser. To get the desired format `DD.MM.YYYY` , we need to use `locale='bs-Cyrl'` (cyrillic alphabet).

**Comment by benelan** [comment] 2022-06-15 18:41
Based on [this chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=842524), it looks like Chrome does not support the `bs` locale. This is a [list of their supported locales](https://source.chromium.org/chromium/chromium/src/+/main:third_party/icu/scripts/chrome_ui_languages.list) provided by a chromium dev. 

It looks like [Edge added support for `bs`](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-languages#supported-display-languages) on their own. I'm closing this issue for now, we can take another look if Chrome adds support for `bs` and it still doesn't work in `calcite-input-date-picker`.

**Closed by benelan** 2022-06-15 18:41 UTC
Labels: bug, browser-chrome, 1 - assigned, i18n-l10n, has workaround

**Comment by BlakeStearman** [comment] 2022-06-15 18:43
@anveshmekala @benelan Thanks for the summary. Will look at a workaround in our own app for Chrome by using `bs-Cyrl` for the time being then.
