### ISSUE TITLE
[Button]: is still clickable when disabled in Firefox

### ISSUE THREAD

**Issue by jasdelreyes** [Esri/calcite-components#7164] opened 2023-06-12 22:15 UTC
### Actual Behavior

Disabled button is still clickable in Firefox. When the button has the disabled prop set to true, the button is still clickable.

### Expected Behavior

It is expected that when the disabled state is true, "interaction is prevented" as referred to in the Calcite doc.

### Reproduction Sample

https://codepen.io/jasdelreyes/pen/yLQYegR?editors=100

### Reproduction Steps

1. Open https://codepen.io/jasdelreyes/pen/yLQYegR?editors=100 in the Firefox browser.
2. Open the codepen link in Chrome or Safari.
3. Observe that the disabled calcite button in the firefox browser still triggers clickable events.

### Reproduction Version

calcite-components 1.4.2

### Relevant Info

Firefox 114.0.1

### Priority impact

p4 - not time sensitive

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment] 2023-06-13 17:24
A workaround for FF includes adding the `style="pointer-events:none"` to the disabled button:

```html
<calcite-button style="pointer-events:none" disabled id="example-button">Open modal</calcite-button>
```

**Comment by driskull** [comment] 2023-06-14 00:12
going to un-assign myself since @jcfranco already has this one in progress.

**Comment by jcfranco** [comment] 2023-06-14 23:14
@geospatialem This is indeed a duplicate of #7043. Maybe we can copy any relevant information over and close this one?

Worth noting that the proposed workaround would prevent users from wiring up a tooltip with a disabled component (https://github.com/Esri/calcite-components/issues/5318).

**Comment by geospatialem** [comment] 2023-06-15 14:50
Closing in favor of #7043. The workarounds, with the caveat of a `tooltip` with the disabled `button` are mentioned in https://github.com/Esri/calcite-components/issues/7043#issuecomment-1593217256.

**Closed by geospatialem** 2023-06-15 14:50 UTC
Labels: bug, browser-firefox, research, p - high, 1 - assigned, regression, has workaround, ArcGIS Map Viewer, ArcGIS Online, estimate - 5, p4 - not time sensitive
