### ISSUE TITLE
Input-date-picker: Incorrect date separator appearing for "it-CH", incorrect date appearing for "zh-CN" and "zh-TW", and cannot select date in beta.98

### ISSUE THREAD

**Issue by annierm18** [Esri/calcite-components#5969] opened 2022-12-09 18:39 UTC
### Actual Behavior

**Issue 1:**
With input-date-picker [Calcite Input Date Picker](http://calcite-dev.esri.com:3008/demos/input-date-picker.html), the separator in between the dates did not change between "it-CH" and "it". I saw it was changing as expected for other locales like for fr-CH --> fr for "it-CH" but saw "25/3/2023".  In beta.98,  when I put "it-CH", I see "." (see issue 3 below for more info on beta.98).

**Issue 2:**
First, the date looks like this right when I change the lang (see standard small component)
![Screenshot (98)](https://user-images.githubusercontent.com/25759835/206760931-167efe1d-c4d5-4469-a14b-02c5153b33d2.png)

Then, it looks like this once I select another date (see standard small component)
![Screenshot (99)](https://user-images.githubusercontent.com/25759835/206760961-d405ba98-8924-4cac-9a94-093974a3a5f6.png)

Lastly, changes to this after I select a date once more (see standard small component)
![Screenshot (100)](https://user-images.githubusercontent.com/25759835/206760975-9a0951a6-40f4-4664-ac31-9ae54e8914b5.png)

**Issue 3:** 
Reproduced in Chrome & Edge: beta.98  with or without the lang attribute included, I can click on the input and get the calendar to appear, but cannot select anything. When I try to select, the calendar dropdown goes away. Note: when I put "it-CH", I see "." in the input field as expected, but I cannot confirm the behavior once a date is clicked. 

### Expected Behavior

**Issue 1:**
I would expect the separator to be ".". Correct separator and date formatting for "it-CH" can be found [here](https://icu4c-demos.unicode.org/icu-bin/locexp?d_=en&_=it_CH). It works correctly in beta.97 in Codepen. Interestingly, the "." appears correctly for "fr-CH" in the same environment where it does not work for "it-CH". 

**Issue 2:**
I would expect the date to remain in the correct...e.g. 2022 would stay as 2022 and not get converted somehow to 190X.

**Issue 3:** 
On beta.98, I would expect to be able to select dates from the dropdown.

### Reproduction Sample

**Issue 3:** https://codepen.io/ainermfc/pen/qBKvQRx?editors=100

### Reproduction Steps

**Issue 1:**
1. Open input date picker 
2. Add lang="it-CH"
3. Click the input

**Issue 2**
1. Open input date picker 
2. Add lang="zh-CN" or "zh-TW"
3. Click the input and select a date
4. Select another date

**Issue 3:**
1. Open input date picker in beta.98
2. Click the input
3. Click anything on the component

### Reproduction Version
**Issues 1 and 2:**
http://calcite-dev.esri.com:3008/demos/input-date-picker.html. ( build is based off #5471 )

**Issue 3:**
beta.98

### Relevant Info

Windows 10

Reproduced issue on Chrome and Edge

### Esri team

N/A

**Comment by geospatialem** [comment] 2022-12-09 19:06
> @anveshmekala and @geospatialem, please add any info you have from your experiences reproducing the issues

@annierm18 Was able to reproduce the same experience and behavior mentioned above. With the above issue, what is your take on priority level / for inclusion of next month's release?

**Comment by annierm18** [comment] 2022-12-09 19:48
@geospatialem Issues 2 and 3 are high. Issue 1 is low (see additional comments below). Please let me know if these need to go in separate tickets.

**Additional Comments:**
For issue 2, I said high because: Chinese is a very popular language amongst users; we also have GeoScene in China selling our products as 'native' products, so we need to behave correctly for all of China

Issue 3 is definitely high since the component is not working at all.

**Comment by benelan** [comment] 2022-12-09 20:09
Can you try testing on `next`? Some of the issues may be fixed. Also one of the issues may be due to or a duplicate of #5886

**Comment by benelan** [comment] 2022-12-09 20:15
- Issue one sounds a lot like the issue I linked above. I'll have that fixed before v1
- Issue 2 may be fixed and issue 3 is fixed: https://codepen.io/benesri/pen/Poagpow

**Comment by geospatialem** [comment] 2022-12-09 20:37
Thanks @benelan for verifying the updates with `next`, there's been a lot of changes going into the component the last few weeks. 🔍 

Going to add a `blocked` label to wait for 5886 to land to determine if there is a fix in place, or if further action is needed after the 1.0 release. cc @annierm18

**Comment by benelan** [comment] 2022-12-09 20:46
@annierm18 do you mind testing issue 1 in this codepen:
https://codepen.io/benesri/pen/mdKQejR?editors=1010

If you see the issue, can you change `next.622` to `next.621` (in two locations) and try again? If it repro's in `next.622` but not `next.621` then issue 1 is a duplicate of #5886. And since issue 2/3 are fixed we could close this issue.

**Comment by annierm18** [comment] 2022-12-09 20:51
@benelan I reproduced issue 3 in the codepen with next.622 and next.621 and thus could not fully test issue 1.

**Comment by benelan** [comment] 2022-12-09 20:53
Ah, of course. Okay I'll ping you after I fix #5886 so we can see if this one is fixed as well

**Comment by geospatialem** [comment] 2023-01-18 17:14
Verified on `next.727`

### issue 1
![image](https://user-images.githubusercontent.com/5023024/213248581-c529b8d8-3bf5-47cb-8bad-83d03855fa76.png)

issues 2 and 3 were fixed earlier and also verified on `next.727`.

**Closed by geospatialem** 2023-01-18 17:14 UTC
Labels: bug, p - low, 4 - verified, i18n-l10n
