### ISSUE TITLE
Enhancement: placement for large popovers on top of shell-panels

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3196] opened 2021-10-11 21:51 UTC
In the Map Viewer we often display larger popovers on top of the right or left shell-panel, e.g. when users have to select a field. These popovers cover about half the vertical size of the panel and the reference element, e.g. button, that opens this popover can be anywhere on the panel. 

The problem we encounter is that the popup is not always placed well and might even have its top cut off. Is there a way to have a fixed placement for the popover over a panel?

<img src=https://user-images.githubusercontent.com/44481292/136856265-e199da2d-32a5-4d24-badb-3cfb0e3b19bd.png width=250/>![image](https://user-images.githubusercontent.com/44481292/136859284-b4dd4e20-adba-4412-949e-c1565e727204.png)

One idea was to add a slot for the popover and have it always use the same internal reference element for placement.

**Comment by benelan** [comment] 2021-10-13 21:25
Hey @AdelheidF, do you have a sample that reproduces this issue?

**Comment by AdelheidF** [comment] 2021-11-30 02:11
Could the panel header node be exposed somehow? Then we could anchor the popover below the header.

**Comment by AdelheidF** [comment] 2021-12-14 20:00
We get several bug reports about popovers being partially hidden in several of our components all due to calcite-panel or its content not having a good reference element that doesn't scroll out of view or scroll into positions where popper places them weird.

Could we give this issue a higher priority, please?

**Comment by benelan** [comment] 2021-12-14 20:09
Moving this to the next sprint starting 12/20

**Comment by driskull** [comment] 2021-12-22 19:26
It looks like the `calcite-shell-panel` has a slot named `header`. Can you throw a div in that and use that div as the reference element for the popover?

I don't think this slot is documented but I'm not sure why not? @asangma?

**Comment by AdelheidF** [comment] 2021-12-22 19:33
> It looks like the calcite-shell-panel has a slot named header. Can you throw a div in that and use that div as the reference element for the popover?

Most of our app components are just calcite-panels that the app places into the shell-panel. This would require all apps to create that header div and pass a reference of it to the app components. This works but is a bit complicated. Could each panel have that kind of slot/header instead?

**Comment by driskull** [comment] 2021-12-22 20:04
@AdelheidF so if I understand correctly...

- You need a way to attach a popover to the header of a panel
- So that the popover doesn't scroll with the content of a panel
- Attaching to the panel itself won't work because the target would be too large.

So we can either...

- Create a slot for supplying a reference element
  -  Not ideal because it wouldn't be anything visible.
- Create a read only property that is the header of the panel for use as a reference element.
  - Tricky because I don't think stencil allows readOnly props.
- Create a method that will return a reference element to the header
  - Not ideal because it would be a method and async.

@jcfranco what are your thoughts here?

**Comment by AdelheidF** [comment] 2021-12-22 20:11
> You need a way to attach a popover to the header of a panel
> So that the popover doesn't scroll with the content of a panel

yes!

> Attaching to the panel itself won't work because the target would be too large.

the placement is weird if we do this

**Comment by driskull** [comment] 2021-12-22 22:28
@jcfranco this is the only way I can think of doing this, right?

```ts
/**
 * test
 */
@Method()
async getHeaderEl(): Promise<HTMLElement> {
  return this.headerEl || null;
}
```

If we make this a pattern, we would probably be better off with one standard method name to return all elements we want to expose.

**Comment by driskull** [comment] 2022-01-13 00:20
Have a potential solution here: https://github.com/Esri/calcite-components/pull/3926

**Comment by driskull** [comment] 2022-05-31 21:42
floating UI virtual elements could probably help with this one. https://floating-ui.com/docs/virtual-elements

**Comment by driskull** [comment] 2022-06-02 22:31
@AdelheidF we installed https://github.com/Esri/calcite-components/pull/4665 which allows for an end user to set the positioning in advanced cases where you want it in a specific spot. 

Can you try out this solution?

This is the basic gist of it:

```js
function generateGetBoundingClientRect() {
        return () => ({
          width: 0,
          height: 0,
          top: 100,
          right: 100,
          bottom: 100,
          left: 600
        });
      }

      const virtualElement = {
        getBoundingClientRect: generateGetBoundingClientRect()
      };

      const popover = document.getElementById("virtual-popover");
      popover.referenceElement = virtualElement;
```

**Comment by driskull** [comment] 2022-06-02 22:36
Let me know if this will work for your use case. It should give you ultimate control over where you want something placed.

**Comment by driskull** [comment] 2022-06-14 00:18
Tests installed @jcfranco .

**Comment by benelan** [comment] 2022-06-15 22:33
Verified on `beta.83` - https://codepen.io/benesri/pen/BaYbyyj?editors=1010

**Closed by benelan** 2022-06-15 22:33 UTC
Labels: enhancement, question, discussion, convention, 3 - installed, milestone adjusted

**Comment by AdelheidF** [comment] 2022-06-30 20:52
The virtual element works well. Thanks.
