### ISSUE TITLE
React: [Alert]  `autoClose` prop will not open the component unless accompanied by the `autoCloseDuration` prop

### ISSUE THREAD

**Issue by geospatialem** [Esri/calcite-components#6824] opened 2023-04-21 14:59 UTC
### Actual Behavior

When using @esri/calcite-components-react and the `alert` component, the `autoClose` prop will not open the `alert`. 

When accompanied by the `autoCloseDuration` prop, the `alert` will display, but `autoClose` should be independent of the `autoCloseDuration` prop.

### Expected Behavior

`alert` should load regardless of the presence of the `autoCloseDuration` prop.

### Reproduction Sample

https://codesandbox.io/s/cc-bug-calcitealert-autoclose-autocloseduration-9ht5xd?file=/src/App.js

### Reproduction Steps

1. [Open the sample](https://codesandbox.io/s/cc-bug-calcitealert-autoclose-autocloseduration-9ht5xd?file=/src/App.js)
2. Observe `alert` doesn't open on load
3. Add `autoCloseDuration={"medium"}` to `alert`
4. Observe `alert` now loads with `autoClose`

### Reproduction Version

1.2.0

### Relevant Info

Seems to be specific to React

### Priority impact

p3 - want for upcoming milestone

### Impact

Seems low with the workaround, but should be mitigated as its not a great bug.

### Esri team

Calcite (dev)

**Comment by mpayson** [comment] 2023-04-21 22:06
I think this is a duplicate of https://github.com/Esri/calcite-components/issues/6363?

**Comment by geospatialem** [comment] 2023-04-21 22:42
Good catch, Max! The above didn't populate when I did a search earlier, and it looks like some of the supplemental information above will solve the needs more info needed in #6363. Will add some context to the original and remove the "need more info" label with the additional context.

**Closed** 2023-04-21 22:48 UTC
Labels: bug, framework-react, 0 - new, needs triage, p - medium, has workaround, Calcite (dev), p3 - want for upcoming milestone
