### ISSUE TITLE
Bug: Scroll bar encroaching on icons in action toolbars in Map Viewer

### ISSUE THREAD

**Issue by lau11123** [Esri/calcite-components#1656] opened 2021-03-03 19:52 UTC
### Summary
If you open Map Viewer Beta in Firefox on a laptop sized screen using the recommended scale (125%) then the scroll bars on <b>collapsed</b> action toolbars encroach on the icons. This doesn't occur when the scale is reduced or on larger monitors, but since it occurs at the recommended scale for a standard laptop I think it might be worth addressing. When I inspected the action bar in Firefox's debugger, it doesn't look like there's any padding for the scroll bar like there is in Chrome.

### Actual Behavior
![image](https://user-images.githubusercontent.com/71884380/109862920-04c10d80-7c2f-11eb-8a8e-04fb55e7e244.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/71884380/109863031-2621f980-7c2f-11eb-9558-d6e3e1bcdbf2.png)

### Reproduction Steps

1. Open Map Viewer Beta in Firefox
2. Set computer's display scale to 125%
3. Set computer's display resolution to 1920 x 1080
4. Collapse the action toolbar (if it isn't already) - see that the scroll bar encroaches on the action icons

### Relevant Info 
- Screen size: 13.5"
- Occurs on both right and left toolbar
- Chrome and Edge don't show this behaviour with the same settings

@asangma

**Comment by driskull** [comment] 2021-03-03 20:12
@asangma now that we have the overflow menu installed. Can we just remove the scrolling? https://github.com/Esri/calcite-components/issues/1466

**Comment by driskull** [comment] 2021-03-16 23:37
@asangma i'll assign back to you if you want to tackle the scrollbar issue for Firefox.

**Comment by jcfranco** [comment] 2021-07-03 00:07
@asangma @lau11123 Is this still valid?

**Comment by lau11123** [comment] 2021-07-05 13:17
@jcfranco not anymore. I checked and it looks like the introduction of the overflow menu has overcome the original issue I reported. It seems like the discussion about the need for scroll bars on the action bar even with the overflow menu has been concluded, but just in case it hasn't I'll leave it up to @asangma to make the final call on this issue.

**Comment by jcfranco** [comment] 2021-07-06 16:49
Sounds good. Thanks! 

@asangma you are the judge, jury and executioner on this one.

**Comment by jcfranco** [comment] 2021-08-12 00:16
@asangma What's your call on this one?

**Comment by asangma** [comment] 2021-12-29 17:59
I think having scrollbars when `overflow-actions-disabled` is enabled makes sense even if it's not pretty. Without the scrolling, there can be actions that are no longer available to the user.

As far as FF, @lau11123 is that the scrollbar that appears only during interaction or is it persistent?

**Comment by asangma** [comment] 2021-12-29 18:03
note: It looks like FF doesn't respect system settings on Mac. I have scrollbars turned on, and they appear as intended in Chrome and Safari, but only appear during interaction in FF.

**Comment by benelan** [comment] 2022-02-15 22:17
Closing as resolved

**Closed by benelan** 2022-02-15 22:17 UTC
Labels: bug, 1 - assigned
