### ISSUE TITLE
Bug: calcite-dropdown-group attributes not respected when using custom elements bundles

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-components#3368] opened 2021-10-28 12:03 UTC
### Actual Behavior

When using the custom elements bundles (`@esri/calcite-components/dist/components/*`), the `selection-mode` (and possible other attributes) of the `<calcite-dropdown-group>` are not respected.

### Expected Behavior

<table>
<thead>
<th>Expected</th>
<th>Actual</th>
</thead>
<tbody>
<td><img src="https://user-images.githubusercontent.com/3759114/139247652-1a57824f-0573-4753-b559-7c2bf28794ca.jpg"/></td>
<td><img src="https://user-images.githubusercontent.com/3759114/139247773-acb6ce58-6b35-41d0-bc72-c944b8a5640e.jpg"/>
</tbody>
</table>

### Reproduction Steps and Sample

- Load custom element modules dynamically (unbundled).
- Make a dropdown with a group and `selection-mode` set to `none`.
- Notice that the dropdown items are still displayed as if the selection mode was set to `single`.

Was not able to reproduce this in Codesandbox because things end up getting bundled. When the app is bundled this bug does not manifest itself.

One thing which may be relevant here is that this happens with modules which have been converted to AMD with Rollup and loaded with the AMD Dojo Loader. It could be possible that the conversion process would break something, I suppose.

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.68`

- [ ] CDN
- [x] NPM package

Regression? _Last working version_: `@esri/calcite-components@1.0.0-<version>`

<sub>SVCH</sub>

**Comment by jcfranco** [comment] 2022-03-16 00:12
Marking this as a duplicate of #4215.

**Closed by jcfranco** 2022-03-16 00:12 UTC
Labels: bug, 0 - new, needs triage
