### ISSUE TITLE
 calcite-input-date-picker issue when range property is set

### ISSUE THREAD

**Issue by jlias-devtester** [Esri/calcite-components#6469] opened 2023-02-14 17:53 UTC
### Actual Behavior

Clicking back and forth between the two inputs (start date and end date)  you can see that the calendar do not position correctly.

### Expected Behavior

The calendar should be positioned right above or just below the two inputs when clicked.

### Reproduction Sample

https://codepen.io/rpanichakit/pen/ZEMEaxG

### Reproduction Steps

1. Prepare a clean ENU browser.
2. Login https://qaext.arcgis.com.
3. Switch to Organization page and click Status tab.
4. Navigate to Reports and click Create Single report.
5. Expand Report type and select Item view count.
6. Click Quarter and click end date to expand calendar. –key step
7. Observe the result.
8. Click start date of Quarter.
9. Observe the result.

### Reproduction Version

not sure

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment] 2023-04-18 17:27
Research to determine next steps, could also be related to https://github.com/Esri/calcite-components/issues/6800.

**Comment by jcfranco** [comment] 2023-06-02 17:49
This is no longer reproducible with 1.4.2 (looks like it got fixed in 1.4.0 via https://github.com/Esri/calcite-components/pull/6900).

**Comment by geospatialem** [comment] 2023-06-02 18:18
Verified in `1.4.2`

**Closed by geospatialem** 2023-06-02 18:18 UTC
Labels: bug, p - low, 4 - verified, ArcGIS Online
