### ISSUE TITLE
[Tooltip] Tooltip jumps to the top left when reference element is no longer visible

### ISSUE THREAD

**Issue by mpayson** [Esri/calcite-components#6397] opened 2023-01-31 17:48 UTC
### Actual Behavior
When a tooltip reference element is no longer visible, the tooltip will briefly jump to the top left before disappearing

### Expected Behavior
The tooltip is removed immediately when the reference element is no longer visible

### Reproduction Sample
https://codepen.io/mpayson/pen/qByJPaB

### Reproduction Steps
Open the codepen
Hover over the button until the tooltip appears
Click the button to add a new flow item
Notice the tooltip jumps to the top left

### Reproduction Version
1.0.3

### Relevant Info
No response

### Regression?
No response

### Impact
This happens relatively frequently in our app since we use buttons with tooltips that replace panel content, or move to a deeper flow. cc @ethanbdev

### Esri team
ArcGIS Online

**Comment by macandcheese** [comment] 2023-01-31 19:38
Following as the new component sample on the Developer site suffers from this as well in certain places.

**Comment by ethanbdev** [comment] 2023-01-31 23:17
Just adding that this can also happen with popovers. When it loses the reference element there is a delay to closing where it repositions to the top left

**Comment by jcfranco** [comment] 2023-03-01 07:41
@mpayson @ethanbdev @macandcheese I'm sure I'm missing something, but I haven't been able to reproduce on my machine. Would you be able to provide an additional info or an example? This is what I see:

![floating-ui-left-pop-in](https://user-images.githubusercontent.com/197440/222074408-4de6afdc-8ad1-4d88-915f-bd3600cb5a96.gif)

I've tested Chrome 110, Firefox 110, Edge 110 and Safari 16.3 on OSX Ventura 13.2.1.

**Comment by ethanbdev** [comment] 2023-03-01 16:41
> @mpayson @ethanbdev @macandcheese I'm sure I'm missing something, but I haven't been able to reproduce on my machine. Would you be able to provide an additional info or an example? This is what I see:
> 
> ![floating-ui-left-pop-in](https://user-images.githubusercontent.com/197440/222074408-4de6afdc-8ad1-4d88-915f-bd3600cb5a96.gif) [ ![floating-ui-left-pop-in](https://user-images.githubusercontent.com/197440/222074408-4de6afdc-8ad1-4d88-915f-bd3600cb5a96.gif) ](https://user-images.githubusercontent.com/197440/222074408-4de6afdc-8ad1-4d88-915f-bd3600cb5a96.gif) [ ](https://user-images.githubusercontent.com/197440/222074408-4de6afdc-8ad1-4d88-915f-bd3600cb5a96.gif)
> 
> I've tested Chrome 110, Firefox 110, Edge 110 and Safari 16.3 on OSX Ventura 13.2.1.

Hey, try collapsing the block that the button is in. That makes it pretty consistent for me, its a bit easier if you swap the tooltip for a popover
![E67A98D0-B596-4B2C-8465-CF6C4205947C](https://user-images.githubusercontent.com/52869490/222204758-be0a01e7-4a0b-494c-a220-35cbc4e13004.GIF)

**Comment by jcfranco** [comment] 2023-03-01 17:49
Sadly, no dice. 🎲

![floating-ui-left-pop-in-2](https://user-images.githubusercontent.com/197440/222220411-c94d0b14-4db8-48a7-9c19-1baa9e920921.gif)

Any other info you think might be useful? What's your environment?

**Comment by ethanbdev** [comment] 2023-03-01 17:59
😮 Its so consistent for me

Not sure - browser is Chrome Version 110.0.5481.178 (Official Build) (64-bit) on Windows. 

How about this simpler example with just a block and a popover? https://codepen.io/eborgen/pen/ExeWZoP?editors=1000

**Comment by macandcheese** [comment] 2023-03-01 18:08
I see what @ethanbdev sees - I'm on Mac - Chrome Version 110.0.5481.100 (Official Build) (arm64). This video is from Chrome, but I see the same consistently in Safari / FF as well 😓



https://user-images.githubusercontent.com/4733155/222225142-05c43997-af46-40d0-8f72-9cff0ef3aefc.mov

**Comment by jcfranco** [comment] 2023-03-01 20:54
Managed to reproduce on another machine. I'll follow up with any findings.

**Comment by macandcheese** [comment] 2023-03-13 20:25
Simple way to reproduce this (or one of the related positioning issues) is have a set of actions and tooltips and quickly tab through them: 

https://user-images.githubusercontent.com/4733155/224823598-362757c4-9b4f-43aa-9012-40d7442d0bee.mov



https://codepen.io/mac_and_cheese/pen/yLxKyEz?editors=1000

**Comment by jcfranco** [comment] 2023-03-13 22:00
@macandcheese Awesome! I was able to repro with that use case reliably. I think this was introduced by https://github.com/Esri/calcite-components/pull/5484 when we tweaked initial positioning of floating-UI elements to prevent odd initial positioning. We could try restoring the always and testing the previous behavior (position regardless of visibility) since https://github.com/Esri/calcite-components/pull/6520 includes a fix for positioning across shadow DOM with no perf hit.

**Comment by jcfranco** [comment] 2023-03-31 07:39
Upon closer inspection, it seems 2 things are going on here:

1. inconsistent reset behavior when floating-ui components are closing
2. the floating-ui repositioning when its reference element suddenly changes position (e.g., block closing) and then hiding (since reference element is no longer visible).

1 should be fixed by #6404. Not sure what we can do about 2. 🤔 cc @driskull

**Comment by driskull** [comment] 2023-03-31 16:08
Not sure what to do about (2) either.

**Comment by nwhittaker** [comment] 2023-04-03 21:28
Would be good to also test https://github.com/Esri/calcite-components/issues/6280 as part of any fix, since it was marked as a duplicate, but has different repro steps.

**Comment by geospatialem** [comment] 2023-04-11 17:38
Research needed to determine next steps, coordination with Matt and Franco to determine next steps.

**Comment by driskull** [comment] 2023-04-13 17:16
Looks like @jcfranco took this one so I'll un-assign myself.

**Comment by jcfranco** [comment] 2023-05-18 23:47
Apologies for the belated update:

> 1. inconsistent reset behavior when floating-ui components are closing

✅ This should now be fixed (original use case is addressed). 

> 2. the floating-ui repositioning when its reference element suddenly changes position (e.g., block closing) and then hiding (since reference element is no longer visible).

⚠️ This may still happen when the reference element is hidden as `floating-ui` keeps updating the position. We could stop applying transforms when we know the reference element is hidden, but this would mean floating elements are no longer anchored and could look odd when reappearing. Leaving this as is for now, but we could revisit in the future if it becomes more noticeable.

> Would be good to also test #6280 as part of any fix, since it was marked as a duplicate, but has different repro steps.

✅ This also appears to be fixed.

**Comment by geospatialem** [comment] 2023-05-20 01:08
Verified in `1.4.0-next.23`. Also mentioning Franco's [note above](https://github.com/Esri/calcite-components/issues/6397#issuecomment-1553788376) WRT floating-ui positioning:

> ⚠️ This may still happen when the reference element is hidden as floating-ui keeps updating the position. We could stop applying transforms when we know the reference element is hidden, but this would mean floating elements are no longer anchored and could look odd when reappearing. Leaving this as is for now, but we could revisit in the future if it becomes more noticeable.

**Closed by geospatialem** 2023-05-20 01:08 UTC
Labels: bug, p - high, 4 - verified, ArcGIS Online, estimate - 8, ArcGIS Web Analysis, airtable
