### ISSUE TITLE
Bug: Toggling a modal's close button changes height of modal header

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#1707] opened 2021-03-08 23:20 UTC
### Summary
Sometimes it is necessary to dynamically change whether or not a `<calcite-modal>` element's close button is enabled. For example, a delete confirmation initially has the close button enabled, but once the user chooses to do the delete, the modal could stick around in a _waiting_ state to ensure the delete succeeds before it dismisses. While in this state, the close button becomes disabled.

### Actual Behavior
The act of toggling the modal's `disableCloseButton` property actually add/removes the button entirely which can cause the height of the modal's `<header>` to fluctuate if the height of the `header` slot's content is different from the height of the close button.

### Expected Behavior
The height of the `<header>` element does not fluctuate when toggling the `disableCloseButton` property.

### Reproduction Steps
```html
<calcite-modal active>
    <h3 slot="header">Modal title</h3>
    <button slot="primary" onclick="this.parentElement.disableCloseButton = !this.parentElement.disableCloseButton">
        Toggle close button
    </button>
</calcite-modal>
```

**Comment by benelan** [comment] 2021-12-10 01:12
It looks like the height is still changing on `next`. @Elijbet can you please take another look at this one.

https://codepen.io/benesri/pen/MWEjWeb?editors=1000

**Comment by Elijbet** [comment] 2021-12-10 17:14
> It looks like the height is still changing on `next`. @Elijbet can you please take another look at this one.
> 
> https://codepen.io/benesri/pen/MWEjWeb?editors=1000

Hmm... can't seem to reproduce it on my end. I looked at it on a larger screen, but don't see the height change.

**Comment by benelan** [comment] 2021-12-10 17:20
Weird, @nwhittaker can you repro with the sample above? Maybe I'm just seeing things.

**Comment by nwhittaker** [comment] 2021-12-10 17:37
>Weird, @nwhittaker can you repro with the sample above? Maybe I'm just seeing things.

I can't repro the issue in https://codepen.io/benesri/pen/MWEjWeb?editors=1000 in the latest versions of Chrome, Edge, Firefox, and Safari on macOS. Specifically, I don't see the height change anymore when the calcite-modal's `scale` attribute is a valid value.

I do see a hight change when the `scale` attribute is set to an invalid or empty value, but I'm not sure that's in scope or what the expected behavior would be anyway.

**Comment by benelan** [comment] 2021-12-10 18:17
![cc_issue_1707](https://user-images.githubusercontent.com/10986395/145622107-d895e991-0778-4751-a5fa-12f55b9eb2fe.gif)
Interesting, I'm on Windows (only one on the team I think) so maybe its an OS issue. I'll assign it to myself and try to get it working on my machine when I have some time.

**Comment by geospatialem** [comment] 2023-01-05 22:35
Verified modal close button consistent header height on Windows in `next.710`

![verify-toggle-modal-height](https://user-images.githubusercontent.com/5023024/210893008-8b3e7ff2-ea8c-4ccc-8559-14d237300a65.gif)

**Closed by geospatialem** 2023-01-05 22:35 UTC
Labels: bug, good first issue, 3 - installed
