### ISSUE TITLE
Bug: Action Bar expand collapse not honored on Action item click

### ISSUE THREAD

**Issue by apfister** [Esri/calcite-components#2857] opened 2021-08-19 14:23 UTC
### Actual Behavior
When an action bar is collapsed, clicking on an action item within the bar will auto-expand the entire bar.
![action bar expand collapse (1)](https://user-images.githubusercontent.com/5233042/130086163-7c1cdf26-fd6b-4f39-88ab-8b18b3fb3310.gif)

### Expected Behavior
When an action bar is collapsed, clicking on an action item should honor the current expand/collapse status of the action bar.

### Reproduction Steps or Sample
https://codesandbox.io/s/action-bar-expand-collapse-bug-lr8u7

### Relevant Info
- Calcite Components v1.0.0-beta.62
- Calcite Components React v0.3.0

- [ ] CDN
- [x] NPM package

**Comment by driskull** [comment] 2021-08-19 16:42
This seems to be an issue with our actionbar component and react.

The problem is that the click is causing another render which is setting the expanded on the actionbar to true and textEnabled on the action to true as well.

If you remove both of those props then things seem to work fine.

Those two props need to stay in sync so that their state is the same.

**Comment by apfister** [comment] 2021-08-24 14:41
@driskull are you saying i should be doing it a different way in React?

**Comment by driskull** [comment] 2021-08-24 15:56
@apfister this should work correctly if you do not set `textEnabled` on any of the actions within the actionbar.

**Comment by apfister** [comment] 2021-09-02 17:20
@driskull removing the `textEnabled` property does not appear to solve the problem.

**Comment by driskull** [comment] 2021-09-02 17:36
@apfister you probably need to maintain a state for the 'expanded' property. If it renders again it will open it up no matter what.

1 - Don't set textEnabled on the actions
2 - Maintain a state for expanded property.

**Comment by jcfranco** [comment] 2021-09-09 00:01
I agree w/ @driskull's solution. Closing since this is not a component issue.

**Closed by jcfranco** 2021-09-09 00:01 UTC
Labels: bug, framework-react, 0 - new
