### ISSUE TITLE
Incorrect positioning of dropdown when clicking in quick succession

### ISSUE THREAD

**Issue by jmanke** [Esri/calcite-components#5732] opened 2022-11-10 00:55 UTC
### Actual Behavior

Clicking on a dropdown trigger in quick succession will cause the dropdown menu to be incorrectly positioned.  

![chrome-capture-2022-10-9 (2)](https://user-images.githubusercontent.com/19629809/200980229-c4d91c9b-2b59-4882-a6ce-1f17f51a74de.gif)

### Expected Behavior

Dropdown menu should be positioned correctly at all times.

### Reproduction Sample

https://codepen.io/jmanke/pen/gOKgNNY

### Reproduction Steps

1. Click on the dropdown button 3 times in quick succession. If that doesn't show the bug, click on it multiple times in quick succession.
2. Observe dropdown menu is incorrectly positioned

### Reproduction Version

beta.98

### Relevant Info

MacOS, Chrome 107

### Regression?

beta.97

### Moderate

We don't have a workaround to this issue at the moment. We are also seeing incorrectly placed dropdowns in nuanced instances. For example, this dropdown will be positioned incorrectly around 50% of the time even if the user only clicks once. Please let me know if you would like me to try reproducing that scenario in codepen.

![Screen Shot 2022-11-09 at 4 53 27 PM](https://user-images.githubusercontent.com/19629809/200973825-a07f67f6-7fc2-48cb-b453-7fd6511df2e2.png)

### Esri team

ArcGIS Dashboard

**Comment by driskull** [comment] 2022-11-10 22:29
@jcfranco looks like in this case, the transition is removed. Seems like the floating-ui is being reset when it shouldn't be. (After transition end).

Maybe we can fix this by getting reposition to cancel any resetting.

**Comment by ReidPritchard** [comment] 2023-01-03 18:16
Believe I'm seeing a related issue in beta.99

The repro steps are slightly different, but produce a similar result. At first glance, it seems like they could be addressed in the same fix, but happy to open a separate issue if that would be best.

### Reproduction Sample

https://codepen.io/reidpritchard/pen/ZEjpGQr

  <h3> Repro Steps: </h3>
  <ul>
    <li> Open dropdown (click "..." action) </li>
    <li> With dropdown open, switch to second tab </li>
    <li> Switch back to first tab </li>
    <li> Re-open dropdown, wait a second for it to jump to upper left corner </li>
    <li> on window resize/scroll the position is correctly reset </li>
  </ul>

https://user-images.githubusercontent.com/11465190/210415763-b1666939-05d7-43cf-9bc2-1a3b80759442.mov

**Comment by geospatialem** [comment] 2023-02-28 18:18
Additional research will be performed in the April milestone.

**Comment by jcfranco** [comment] 2023-05-31 17:24
This should be fixed in the latest release.

**Comment by geospatialem** [comment] 2023-05-31 21:46
Verified as mitigated in both samples, https://codepen.io/jmanke/pen/gOKgNNY and https://codepen.io/reidpritchard/pen/ZEjpGQr  with `1.4.2`.

**Closed by geospatialem** 2023-05-31 21:46 UTC
Labels: bug, research, p - low, 1 - assigned, ArcGIS Dashboards
