### ISSUE TITLE
[Edge Bug] Click events do not work in Calcite Tree

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#136] opened 2019-09-16 17:14 UTC
When navigating with mouse, click events cause a `Unable to get property '0' of undefined or null reference` console error. Navigating with ENTER / SPACE / ARROWS works fine.

Expected functionality:
Click events should work as keyboard events do in Edge.

**Comment by pr3tori4n** [comment] 2019-09-18 20:49
Root cause:
`event.originalTarget` and `event.path` are not supported in Edge. MDN recommends avoiding the use of both and going with `event.composedPath()`.

This gets us past that issue, but then the logic for shouldSelect is not working in edge. event.target and event.parentTarget are not the same in Edge due to the lack of an actual shadowDom in polyfilled environments.

I recommend setting up additional clickHandlers and simplifying the clickHandler logic so that it doesn't need to determine the target. I have a branch with a start, but I'm going to need some additional info on expected behavior to make sure this doesn't break existing functionality.
https://github.com/Esri/calcite-components/tree/hrobbins/tree-edge-fix-136

**Comment by pr3tori4n** [comment] 2019-09-18 20:52
@macandcheese @julio8a do you guys know where I can find the requirements for this component? We should get some tests added to cover these use cases and verify any changes don't break them.

**Comment by macandcheese** [comment] 2019-09-18 20:57
@pr3tori4n Great, thanks for checking in! The original issue was https://github.com/Esri/calcite-components/issues/11 but I know it was built for VTSE and additional use cases have been added since that issue. @patrickarlt will have more insight as author.

**Comment by patrickarlt** [comment] 2019-09-27 23:12
Should be resolved in the next release.

**Closed by patrickarlt** 2019-09-27 23:12 UTC
Labels: bug
