### ISSUE TITLE
(React) Calcite Action Groups always collapse, not just when space runs out

### ISSUE THREAD

**Issue by RSantosGIS** [Esri/calcite-components#5076] opened 2022-08-03 15:30 UTC
### Actual Behavior

Members of Calcite Action Groups appear to just always collapse into the collapse menu regardless of the space in the parent container.  I am not sure what exactly causes the collapse behavior

### Expected Behavior

Calcite Action Groups should only automatically collapse if the space to contain all the Actions runs out.  As space runs out, more items should be added to the overflow popout menu.

### Reproduction Sample

https://codesandbox.io/s/calciteactiongroupproblem-1rfijm?file=/src/App.js

### Reproduction Steps

1. The second group (with three elements) should load already in a collapsed state

### Reproduction Version

Calcite beta.86, Calcite-components-react 0.27.0

**Comment by macandcheese** [comment] 2022-08-03 16:41
I agree this is unexpected behavior. The `overflowActionsDisabled` isn't really a solution since it prevents appending items at all, even when they should collapse due to viewport size. I suppose as a workaround someone could conditionally set / remove this property themselves based on viewport, but that is a pain.

**Comment by benelan** [comment] 2022-08-03 21:32
Reproducible outside of react as well: https://codepen.io/benesri/pen/OJvvWJy

In the sample if you add this CSS it works:
```css
html, body, calcite-action-bar {
      height: 100%;
}
```

**Comment by driskull** [comment] 2022-11-14 19:31
@asangma @macandcheese can you comment on what CSS approach we should take?

- Use flex for stretching?
- Use 100% height?

The codepen in this example would still need to update a container to display flex or 100% height. That could be the body if no container.

**Comment by driskull** [comment] 2022-11-14 21:41
This seems to work perfectly fine when the `#root` container is set to `display:flex`.

Updated sample: https://codesandbox.io/s/calciteactiongroupproblem-forked-zulq87?file=/public/index.html

```html
<style>
      html,
      body,
      #root {
        height: 100%;
        width: 100%;
        margin: 0;
        padding: 0;
      }
      #root {
        display: flex;
      }
    </style>
```

I think we can close this issue. Feel free to reopen if necessary.

@geospatialem should we update documentation on the `action-bar` to say its parent should be displayed as flex?

**Closed** 2022-11-14 21:41 UTC
Labels: bug, 0 - new, milestone adjusted, has workaround

**Comment by geospatialem** [comment] 2022-11-16 17:42
> @geospatialem should we update documentation on the `action-bar` to say its parent should be displayed as flex?

It looks like its been fixed in [Ben's codepen](https://codepen.io/benesri/pen/OJvvWJy) as of `beta.89`, perhaps from your fix in https://github.com/Esri/calcite-components/pull/5006? 

It does look like its still persisting with the React wrapper in `0.35.0`, so we could add it to the [React Framework Gotcha section](https://developers.arcgis.com/calcite-design-system/frameworks/#gotchas), although it seems kinda like a hack? WDYT @driskull?

**Comment by driskull** [comment] 2022-11-16 17:52
Its not related to react. Its basically related to making its parents full height and flex.

**Comment by geospatialem** [comment] 2022-11-17 15:44
@driskull This looks to be a bug with the `expand-disabled` property. When using the prop, it adds the `...` menu when more than two `action`s are present in an `action-group`:

- [Codepen with `expandDisabled`](https://codepen.io/geospatialem/pen/qBKPGNY)
- ![image](https://user-images.githubusercontent.com/5023024/202486735-cc657ca1-e9ac-4bb7-9672-ac35c1af19e6.png)

Whereas, when the `expand-disabled` property is not present, the menu system behaves as-expected (using `@esri/calcite-components-react 0.35.0` and `beta.98`:

- [Codepen without `expandDisabled` present](https://codepen.io/benesri/pen/OJvvWJy)
- ![image](https://user-images.githubusercontent.com/5023024/202487294-d67aa5f3-f178-435a-939e-d65d814275a5.png)


Could it be related to the [resize method](https://github.com/Esri/calcite-components/blob/master/src/components/action-bar/action-bar.tsx#L224-L256)?

**Comment by driskull** [comment] 2022-11-17 18:24
@geospatialem Its not a bug. Here's a fixed codepen https://codepen.io/driskull/pen/OJEOLoV?editors=1000


```html
 <style>
    html, body{
      height:100%;
      width:100%;
      margin:0;
      padding:0;
    }
    body{
      display:flex;
    }
  </style>
```
