### ISSUE TITLE
Bug: calcite-select height and RTL issues

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#1874] opened 2021-03-31 18:33 UTC
### Summary

(1)
first row is a calcite-button, second row is a calcite-select, third row is a calcite-input. The components no longer have the same height.

production:
<img src=https://user-images.githubusercontent.com/44481292/113192995-50f27400-9214-11eb-8b1a-d98d0f6f4ff0.png width=200/>

devext (next.127)
<img src=https://user-images.githubusercontent.com/44481292/113193165-8303d600-9214-11eb-94b9-53897f014fea.png width=200/>

### Reproduction Steps

1.

**Comment by AdelheidF** [comment] 2021-03-31 23:18
Something is majorly wrong with `calcite-select` suddenly in RTL (tested with next.127 and next.133). I assume this is related to the height issue.

![image](https://user-images.githubusercontent.com/44481292/113222688-5ebbef80-923c-11eb-8d8e-a2a2bdeb8530.png)

production is fine

![image](https://user-images.githubusercontent.com/44481292/113222796-a04c9a80-923c-11eb-8429-12901635e57f.png)

**Comment by julio8a** [comment] 2021-04-02 22:32
@AdelheidF,

When I try to access that link in Chrome the page just keeps trying to load content and my computer fan goes crazy but nothing ever loads. Not sure if this is on my end?
Video:
[chrome-page-doesn't-load.zip](https://github.com/Esri/calcite-components/files/6251439/chrome-page-doesn.t-load.zip)


On Safari I am able to access the app and the RLT on select looks fine.

![image](https://user-images.githubusercontent.com/6144462/113458784-52649d80-93c8-11eb-942f-b2b0d309af62.png)

Is there more info to reproduce this?

**Comment by AdelheidF** [comment] 2021-04-02 22:49
Maybe you run into the shield page on devext. Try this instead.

https://qaext.arcgis.com/apps/mapviewer/index.html
does this load for you? Just accept some of the info messages.
Now try this
https://qaext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0
does the layer load?
Now try this in Arabic
https://qaext.arcgis.com/apps/mapviewer/index.html?url=https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/FatalAccidents2017/FeatureServer/0&locale=ar

If you set the focus on the calcite-select component you won't see the issue. Set the focus on something else.

I still see the issue on Windows + Chrome using next.133

<img src=https://user-images.githubusercontent.com/44481292/113459639-efc0d100-93ca-11eb-9528-f5514c0c16de.png width=400/>

**Comment by AdelheidF** [comment] 2021-04-02 22:56
https://github.com/Esri/calcite-components/pull/1909

**Comment by AdelheidF** [comment] 2021-04-06 22:01
(2) is fixed with next.147

**Comment by AdelheidF** [comment] 2021-04-06 22:24
Moving part (1) to a later date

cc @caripizza

**Comment by caripizza** [comment] 2021-05-13 18:15
Closing this one since select's RTL styles were fixed in pr #1909.

The other aspect of this issue ("(1)") is that calcite-select has the new Figma refactor (per pr #1719), but calcite-button and calcite-input haven't been refactored yet. This is why the sizes don't match right now (it's not a bug, it's expected).

Here are the follow up issues: #2139, #2140

**Closed by caripizza** 2021-05-13 18:15 UTC
Labels: 1 - assigned, bug, p - high
