### ISSUE TITLE
modal,dropdown, combobox : deprecated `active` prop is not acting as alias with `open` 

### ISSUE THREAD

**Issue by anveshmekala** [Esri/calcite-components#4996] opened 2022-07-21 18:48 UTC
### Actual Behavior

Whenever the user sets either of `active` or `open` prop, the other one should be in sync and deprecated prop should act as an alias. The same applies when the user removes either of the props.

E.g:
`<calcite-combobox open active> </calcite-combobox>` 

When the user removes the `open` prop, then the `active` prop still stays. 

### Expected Behavior

- If the user sets `active` prop via DOM manipulation, parsing as prop or setting it programmatically `open` prop should be added as well and vice-versa. 
- 
- If the user removes `active` prop via DOM manipulation , parsing as prop or setting it programmatically `open` prop should be added as well and vice-versa. 

### Reproduction Sample

https://codepen.io/ANVESHMEKALA/pen/KKomjgd?editors=1010

### Reproduction Steps

1. Click on the combobox to set `open` to `true`
2. Both `open` & `active` attributes will be appended to combobox in DOM.
3. When you remove `open` attribute from DOM , `active` still stays.

### Reproduction Version

beta.86

### Relevant Info

Related to [4775](https://github.com/Esri/calcite-components/pull/4775)

**Comment by benelan** [comment] 2022-08-05 00:59
I tested this on `next`, you still need to set both `active` and `open` to false in order to close the combobox:
https://codepen.io/benesri/pen/abYYewb?editors=1010

Assigning this back to dev for another look

**Comment by jcfranco** [comment] 2022-08-10 00:00
I believe this is working as expected. The default for both is false, so we honor whichever is present and can't assume the lack of `open` means closed. To summarize:

1. none specified ➡️ closed
2. any specified (both or either) ➡️ open

The codepen does bring up some subtle behavior related to updating components before hydration. It looks like setting attributes before hydration does populate the property correctly (see https://github.com/Esri/calcite-components/issues/4762#issuecomment-1193099704), but it [doesn't work the other way around](https://codepen.io/jcfranco/pen/poLZeXO?editors=1011). Not sure if this is by design or not. 

LMK if I missed something.

**Comment by benelan** [comment] 2022-08-10 03:28
> 1. none specified ➡️ closed
> 2. any specified (both or either) ➡️ open

This contradicts what we [discussed in a related PR here](https://github.com/Esri/calcite-components/pull/4807#issuecomment-1202720528), specifically:

> replacement properties take precedence over deprecated properties when both are set.

Not sure if it matters that there are inconsistencies w/ the way deprecated props behavior with their replacements since it's not supported. But if it is inconsistent, I don't think we should say anything in the doc about how it behaves; only that it is not supported.

**Comment by benelan** [comment] 2022-08-10 03:31
closing this as verified on `next` - I'll bring the discussion about my comment above to the open, related PR

**Closed by benelan** 2022-08-10 03:31 UTC
Labels: bug, p - high, 1 - assigned, milestone adjusted
