### ISSUE TITLE
`<calcite-option>` value attribute missing when set via handlebars after delayed render

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#3576] opened 2021-11-29 17:53 UTC
### Actual Behavior
Given a `<calcite-option>` element with a `value` attribute set to a handlebars expression, if the element is rendered dynamically, the `value` attribute is never set. However, if the element is rendered immediately on page load, the `value` attribute is set.

### Expected Behavior
To maintain a consistent behavior, the `value` attribute is set in both cases.

### Reproduction Steps and Sample

_Sample_: https://ember-twiddle.com/6ad914f1e2715b997aa87c6211959014

1. Visit the code sample and inspect the visible `<calcite-select>` element. Notice the 1st option's `value` attribute is static and is visible in the DOM. Also notice the 2nd option's `value` attribute is a handlebars expression and is also visible in the DOM.
2. Click the "Show/hide" button to render the 2nd `<calcite-select>` element.
3. Inspect the 2nd `<calcite-select>` element. Notice the `value` attribute of its 2nd option is also a handlebars expression but its value is not visible in the DOM.

### Relevant Info
Due to how Ember's routing works, it is common for elements to not be rendered during the initial page load. As a result it is very common for elements to be rendered dynamically. It's also easier to write tests that match on attribute values. Possibly stems from the same issue as https://github.com/Esri/calcite-components/issues/1409.

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.70`

- [ ] CDN
- [ ] NPM package

Regression? No

**Comment by jcfranco** [comment] 2021-12-08 01:15
I'm afraid this is the same issue as [#3240](https://github.com/Esri/calcite-components/issues/3240#issuecomment-974606786). `calcite-option`, as well as other components, do not reflect their `value` property (by design).  

I'm not sure if there is a way to force Ember to set the attribute when updating the DOM from an expression. If not, a workaround would be to use a data attribute instead.

Closing as a duplicate.

**Closed by jcfranco** 2021-12-08 01:15 UTC
Labels: bug, framework-ember, 1 - assigned

**Comment by nwhittaker** [comment] 2021-12-09 15:44
@jcfranco, #3240 was not dealing with a rich-data value (neither is this one) and it lacked the detail about delayed rendering, so I just want to make sure we're talking about the same thing:

<img width="1119" alt="Screen Shot 2021-12-07 at 9 26 39 PM" src="https://user-images.githubusercontent.com/421496/145140430-593e3cc6-704f-4b67-a714-3044b3a198ce.png">

Out of curiosity, I added a couple standard `<select>` menus to the [code sample](https://ember-twiddle.com/6ad914f1e2715b997aa87c6211959014) with similarly crafted `<option>` elements. Both their `value` attributes  did behave per the expected behavior. This suggests to me the analysis in https://github.com/Esri/calcite-components/issues/3240#issuecomment-974606786 is not applicable to this scenario.

I don't understand why `<calcite-option>` elements would be expected to behave differently from standard `<option>` elements, and inconsistently across different rendering contexts, with respect to the `value` attribute?

Given the above observations, I think this issue should be reopened.

**Comment by jcfranco** [comment] 2021-12-10 18:12
Unlike native HTML form elements, some of our components allow `value` to be of any type, not just string. This is why we do not reflect the property, regardless of the actual value.

Taking a step back, may I ask why you need `value` to be reflected? Is it for styling?
