### ISSUE TITLE
Bug: calcite-popover - trap focus inside

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2133] opened 2021-05-13 00:42 UTC
All 3 sub-issues here a related, so I added them into the same issue.

<details>
<summary>(1) (fixed with the use of `calcite-list`)</summary>
<br>
Add an option to value list to not allow selection of the text, only `action-end`.

![image](https://user-images.githubusercontent.com/44481292/118058980-4a433a80-b344-11eb-8140-8c3f70458446.png)

This is a lists of values in the filter component, clicking on a value name does not call an action. Only `action-end` matters here.
![image](https://user-images.githubusercontent.com/44481292/118060144-f1c16c80-b346-11eb-8f8a-77a6baa72a5b.png)

This is a list of detailed information inside a popover. Nothing should happen when you click on the text, only `action-end` matters here as well.
![image](https://user-images.githubusercontent.com/44481292/118060204-0c93e100-b347-11eb-9661-d393a12d27d3.png)
</details>

<details>
<summary>(2) (fixed with the use of `calcite-list`)</summary>
<br>
Navigating in this value list is a bit weird. Initially only the first row, first text then action-end, can be selected. If you then tab again it leaves the list. You need to use the down arrow to navigate inside the list, but the down arrow only works on the text, not on action-end. Same with `calcite-pick-list`.
</details>

(3) 
Focus gets lost if there if no other focusable item after the value-list when using tab key after `action-end` is selected. This is a problem for keyboard only users in the popover case above. How can I catch the focus (or know when the focus leaves value-list) and redirect it back to the close icon of the popover? I tried `onBlur` but that didn't work.
Scenario:
popover opens with close button on focus. Then I tab my way through the list. After the last focusable item in the list is active and I hit tab the focus gets lost.

____________
New list component https://github.com/Esri/calcite-components/issues/2117

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by TheBlueDog** [comment] 2021-05-27 13:07
Follow

**Comment by TheBlueDog** [comment] 2021-05-27 13:09
Follow

**Comment by AdelheidF** [comment] 2021-08-05 18:27
(1) and (2) are fixed with the use of the new `calcite-list`. (3) is still valid. Changed the title.

**Comment by macandcheese** [comment] 2021-11-05 18:29
@AdelheidF can you put together a codepen that illustrates this bug? Thanks!

**Comment by AdelheidF** [comment] 2021-11-09 00:24
https://codepen.io/afreitag/pen/LYjmaWv?editors=1000

Click on the button to open the popover. Wait until focus sits on close button, now tab 4 times, all good. Now tab one more time, the focus should go back to the close button. How can I know that the focus left the list to set it back to the close button? A keyboard-only user would be lost now.

**Comment by macandcheese** [comment] 2022-01-05 17:46
Is this specific to list? Looking at it now it just seems like we don't trap focus inside a popover. That seems like a reasonable thing to have support though.

**Comment by AdelheidF** [comment] 2022-01-05 18:05
> Is this specific to list?

not really, `trap focus inside a popover` is the better description for what I need probably.

**Comment by AdelheidF** [comment] 2022-09-12 16:37
another use case:

This popover has 2 focusable elements. 
![image](https://user-images.githubusercontent.com/44481292/189707846-da48969c-944b-414d-9022-0ab156af37f3.png)
I tab once to get to the button
![image](https://user-images.githubusercontent.com/44481292/189707929-bb91647a-6de3-49ff-8817-7a9e1298f8aa.png)
If I tab one more time the focus is lost from the popover and here on my browser page. It's very hard then go back to where I was only using the keyboard.
![image](https://user-images.githubusercontent.com/44481292/189708272-3a46f1d6-589b-46e5-a5e0-0cdf57cc4202.png)
![image](https://user-images.githubusercontent.com/44481292/189708053-ba47b379-c116-45c5-a4cc-d40a81557892.png)

**Comment by macandcheese** [comment] 2022-09-12 17:18
Yeah, in that case the behavior could be more like a modal. If we add focus trapping to popover, do we need to offer `disableEscape` and related options from modal? cc @geospatialem

**Comment by geospatialem** [comment] 2022-09-12 18:20
> Yeah, in that case the behavior could be more like a modal.

We got similar feedback from a screen reader user earlier this summer, as they were expecting functionality similar to a modal. Would be a great feature to add to the component.

> do we need to offer `disableEscape` and related options from modal?

Ideally we'd like to always allow escape as an option for closing, as it is an expected behavior for keyboard users when open. 

It looks like tooltip closes with the escape key, and there is no `disableEscape` property. Perhaps we could follow suit in this case as opposed to modal? We'd also need to add functionality to allow the escape key for closing the component, as its not currently built in.

**Comment by AdelheidF** [comment] 2022-09-14 16:00
I think `calcite-modal` has the same issue.

We just got an issue from the accessibility testing group about this too.
```
Violation
Ensure that keyboard focus remains within modal dialogs
```

**Comment by driskull** [comment] 2022-11-01 17:20
@jcfranco should we use this npm package for this? https://www.npmjs.com/package/focus-trap

We could update the modal to use this package too.

**Comment by geospatialem** [comment] 2022-11-23 15:59
Verified on `next.639`

![verify-popover-trap](https://user-images.githubusercontent.com/5023024/203592143-1a1268ff-13e5-4da2-9d46-716884973b97.gif)

**Closed by geospatialem** 2022-11-23 15:59 UTC
Labels: bug, design, 4 - verified, milestone adjusted
