### ISSUE TITLE
Creating issue spams "Sync to Airtable" workflow failures

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#6510] opened 2023-02-23 17:30 UTC
### Summary

Submitting a new issue spins off 4-5 **Sync to Airtable** workflow jobs. One appears to succeed and the rest are canceled.[^1] Each canceled workflow emails the submitter.

[^1]: https://github.com/Esri/calcite-components/actions/workflows/sync_to_airtable.yml?query=event%3Aissues

### Desired Outcome

Perhaps tune the workflow so it only runs once when submitting a new issue, if possible.

**Comment by jcfranco** [comment] 2023-02-23 23:50
cc @alisonailea

**Comment by jcfranco** [comment] 2023-02-23 23:52
@noahmulfinger Thanks for letting us know and sorry for the noise. We'll fine tune the GH action.

**Comment by alisonailea** [comment] 2023-02-24 00:07
@nwhittaker the action is expected to fire multiple times on a new issue. There may be a better way in the long run however the action is designed to cancel itself if it's fired multiple times in short succession. Check your notification settings. Make sure under Notification > Actions you have it checked to only alert you for failed workflows. 
![Screenshot 2023-02-23 at 4 06 55 PM](https://user-images.githubusercontent.com/3362490/221059587-3129f507-3f9b-4c1c-8f25-13cbc51611d3.png)

**Comment by nwhittaker** [comment] 2023-02-24 01:04
>@nwhittaker the action is expected to fire multiple times on a new issue. There may be a better way in the long run however the action is designed to cancel itself if it's fired multiple times in short succession.

@alisonailea, it sounds like you need the system to not consider a cancelation as a failure -- otherwise how do you disambiguate between cancelations and real failures? I'm not sure how the concurrency logic is setup, but how about skipping the jobs within the workflow instead? Skipped jobs don't result in failures. Or skip the workflow entirely, if that's possible.

>Check your notification settings. Make sure under Notification > Actions you have it checked to only alert you for failed workflows.

This doesn't help because the canceled workflows are seen as failures by the system which then sends failure emails for each one.

**Comment by benelan** [comment] 2023-02-24 01:11
Yeah skipping is the way to go. You can create [conditionals](https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution), for example:

https://github.com/Esri/calcite-components/blob/3a7f11238d52e7b5cec1cd2dd597d0184d7e0ce3/.github/workflows/chromatic.yml#L10-L13

It also might be a good idea to fork the repo or create a test repo for QA

**Comment by alisonailea** [comment] 2023-02-24 01:22
I don't think conditionals will help this problem. The issue is how many times the action is triggered, unless you know a way to have conditionals check for that. 

I have a test repo I am debugging in. It sounds like the solution here is to break the triggers out into different actions to reduce concurrency.

**Comment by geospatialem** [comment] 2023-02-28 16:48
@nwhittaker How are notifications behaving for you since yesterday (2/27) from 5:30pm ET on when a fix was added?

The Airtable notifications seem less noisy on my end, but wanted to get your take prior to closing the issue out.

**Comment by nwhittaker** [comment] 2023-02-28 16:57
>The Airtable notifications seem less noisy on my end…

Agreed. I added an enhancement issue this morning and didn't notice any failure/cancelation emails. Thanks!

**Comment by geospatialem** [comment] 2023-02-28 16:59
Closing out the above issue.

**Closed by geospatialem** 2023-02-28 16:59 UTC
Labels: tooling, p - high, 4 - verified, airtable
