### ISSUE TITLE
A11y: pick-list-items in pop-up pick-list are not listening to keyboard selection

### ISSUE THREAD

**Issue by lau11123** [Esri/calcite-components#1530] opened 2021-02-09 19:59 UTC
### Summary
The event listener for `pick-list` where `multiple` = `true` isn't picking up selection changes to a `pick-list-item` using keyboard navigation in Map Viewer Betas pop-up configuration. I would expect that the Space key should select and de-select items in a `pick-list` the same way a mouse click does. Right now, the Space key doesn't select or de-select a `pick-list-item` in the chart mediaInfo or the fieldInfo `pick-list`. Also, in the Styler `pick-list` the Space key can select items, but it doesn't de-select them.

### Actual Behavior
![PopupKBSelectPickListItem](https://user-images.githubusercontent.com/71884380/107418626-df842800-6ae4-11eb-8cfb-195aaa099661.gif)

### Expected Behavior
*This is the expected behaviour for selecting an item with the Space key.
![StylerKBSelectPickListItem](https://user-images.githubusercontent.com/71884380/107419553-ef503c00-6ae5-11eb-928a-ac99c43a53cd.gif)

### Reproduction Steps

1. Open a Hosted Feature Layer in Map Viewer Beta
2. Click on the layer in the TOC
3. Click Configure pop-ups in the right action bar
4. Expand the Fields block
5. Tab to Select fields and click Enter once focused
6. Tab/arrow key to a field (item) that's selected
7. Press the Space key - see that the check mark goes away but the field remains in the pop-up
8. Tab/arrow key to an unselected field (item)
9. Press the Space key - see that a check mark appears but the field isn't added to the list in the pop-up
10. Tab to the Done button and press Enter - see that the list in the pop-up doesn't reflect the selection changes

### Working W3C Example/Tutorial

**Comment by lau11123** [comment] 2021-02-09 20:02
@asangma I can't adjust the label, milestones, assignees, etc. in this repo. Could you apply the appropriate ones please? :D

**Comment by jcfranco** [comment] 2021-05-25 23:30
@lau11123 Do you have an isolate repro case with the pick list? The list component seems to be working as expected on my end.

**Comment by jcfranco** [comment] 2021-05-26 23:27
Moving to backlog until we get a reproducible test case. cc @julio8a

**Comment by jcfranco** [comment] 2021-06-04 16:12
@lau11123 Closing per our conversation. This was an issue on the wrapping component side.

**Closed by jcfranco** 2021-06-04 16:12 UTC
Labels: 0 - new, a11y, bug, p - high
