### ISSUE TITLE
Share the upcoming release changes in the changelog

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-components#1846] opened 2021-03-25 19:14 UTC
### Description 
Folks would like to be aware of breaking changes earlier.

### Which Component
This applies to all components.

**Comment by driskull** [comment] 2021-03-29 20:18
@jcfranco would it be possible to generate an updated `NEXTCHANGELOG.md` during the `next` build generation?

**Comment by jcfranco** [comment] 2021-03-30 01:39
This seems to be a duplicate of https://github.com/Esri/calcite-components/issues/1076.

I was hoping `standard-version` would have made an update to make this easier, but it doesn't seem to be the case. I think it's possible to do this, but I'd like to avoid managing two changelogs. Instead, I would propose updating our tooling to manage an unreleased/upcoming section in the changelog for anything deployed to @next. This section would get removed on each release.

@julio8a What is the priority, timeline for this?

**Comment by driskull** [comment] 2021-03-30 16:23
@jcfranco I had Julio create this issue but the request came from @AdelheidF. We just need a more visible way to see upcoming changes rather than a user having to checkout the repo and run a specific script.

As for the priority, I don't think its high. Probably a low priority that could increase if more users ask us for upcoming changes frequently.

**Comment by jcfranco** [comment] 2022-03-11 15:11
Closing, as this was addressed by https://github.com/Esri/calcite-components/issues/1076 in beta.60.

**Closed by jcfranco** 2022-03-11 15:11 UTC
Labels: 0 - new, needs triage
