### ISSUE TITLE
`CalciteTree.componentWillRender()` throws error when `<calcite-tree>` is detached

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#5464] opened 2022-10-12 17:28 UTC
### Actual Behavior

A `TypeError` is sometimes thrown by the `CalciteTree.componentWillRender()` hook.

### Expected Behavior

A `TypeError` is never thrown by the `CalciteTree.componentWillRender()` hook.

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/KKRbYOQ

### Reproduction Steps

1. Visit sample and open the browser's console.
2. Click the **Mutate and detach** button
3. Observe error output in console.

### Reproduction Version

beta.95

### Relevant Info

Due to stencil's asynchronous nature when updating props or calling methods, a race condition exists when mutating a property immediately before removing the element from the DOM. A scenario more likely encountered when writing unit tests.

Specifically, the property mutation triggers a re-render at the same time the element is detached. By the time the `componentWillRender()` is called, the element may already be detached. When this is the case, the following error and stacktrace (abbreviated) is thrown:

```
TypeError: Cannot read properties of null (reading 'closest')
    componentWillRender (p-e1c801a6.entry.js:formatted:252)
    ...
    requestAnimationFrame (async)
    ...
    set (p-975aba66.js:6)
    (anonymous) (tests.js:19450)
...
```

The failing line is:
https://github.com/Esri/calcite-components/blob/f5716f345f71a14d99267e1bf72d22fa28a9870f/src/components/tree-item/tree-item.tsx#L160

If the element is detached at this point, `parentTree.parentElement` is `null` and `parentTree.isConnected` is `false`.

### Esri team

ArcGIS Field Apps

**Comment by benelan** [comment] 2022-10-12 21:58
Looks like a duplicate of #5333

**Closed** 2022-10-18 17:26 UTC
Labels: bug, duplicate, 0 - new, ArcGIS Field Apps
