### ISSUE TITLE
calcite-tooltip performance issues when rendering many instances

### ISSUE THREAD

**Issue by rpanichakit9541** [Esri/calcite-components#3727] opened 2021-12-16 19:13 UTC
### Actual Behavior

When rendering a bunch of calcite-tooltip (300 in the sample CodePen), I noticed some slow rendering when scrolling in Firefox. In Chrome, the rendering does not blink in and out, but the scrolling itself becomes a bit laggy.

![tooltip_performance](https://user-images.githubusercontent.com/44479773/146433572-b3bcc50f-5546-4ff0-97d6-dd8633ffa5a1.gif)

### Expected Behavior

I would expect the scrolling/rendering to be smooth regardless of how many tooltips are on the page.

### Reproduction Steps and Sample

_Sample_:

1. https://codepen.io/rpanichakit/pen/ZEXKYYQ

### Relevant Info

Firefox 95.0.1 (64-bit) 
Chrome Version 96.0.4664.93 (Official Build) (64-bit)
OS: Windows 10

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.71`

**Comment by driskull** [comment] 2022-01-12 19:19
I'm not noticing any performance issues on FF/Chrome with beta71 or 74.

**Comment by rpanichakit9541** [comment] 2022-01-12 19:24
@driskull - I see the blinking issue on my FF 96.0 and Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by driskull** [comment] 2022-01-26 21:20
@rpanichakit9541 does this codepen make any difference?

https://codepen.io/driskull/pen/JjOoJaa?editors=0010

**Comment by rpanichakit9541** [comment] 2022-01-26 21:25
@driskull - Unfortunately, I still see the issue in your codepen

![tooltip_perf](https://user-images.githubusercontent.com/44479773/151249472-c9818da4-1eda-4af3-9f82-441d3b7f1e1c.gif)

**Comment by driskull** [comment] 2022-01-26 21:36
@rpanichakit9541 I'm not sure we can do anything to fix this at this time.

If you remove setting the referenceElement on the tooltip, I suspect the performance issue will no longer be a problem.

@benelan @jcfranco maybe we can move this to the backburner for now?

The reason for this performance hit is that it updates the placement of the tooltip when scrolling occurs. We need to have the positioning correct before we show the tooltip to handle the slight animation.

**Comment by rpanichakit9541** [comment] 2022-01-26 21:40
@driskull - Yes I verified that removing `referenceElement` does resolve the issue.

**Comment by driskull** [comment] 2022-01-27 18:22
I think floating-ui might fix this performance a bit. It would allow us to not reposition any hidden tooltips.

**Comment by benelan** [comment] 2022-03-16 23:26
@rpanichakit9541 can you please verify that this issue is resolved in `beta.79`? I was unable to reproduce the issue with your original sample

**Comment by rpanichakit9541** [comment] 2022-03-16 23:37
@benelan - I just verified that changing to beta.79 resolved it.

**Closed** 2022-03-16 23:38 UTC
Labels: bug, 3 - installed, milestone adjusted, has workaround
