### ISSUE TITLE
[Combobox] Combobox now requires two tabs to navigate through the component.

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#5191] opened 2022-08-19 22:44 UTC
### Actual Behavior

Combobox now requires two tabs to navigate through the component:
The first tab focuses the component but not the input. The second tab correctly focuses the input.

Version 91: https://codepen.io/mac_and_cheese/pen/ExErbYd?editors=100

### Expected Behavior

A single tab will focus the component and the internal input is immediately actionable:

Version 86: https://codepen.io/mac_and_cheese/pen/yLKZPBp?editors=100

### Reproduction Sample

See above

### Reproduction Steps

View two above Codepens - see the correct behavior on version 86, and incorrect on version 91.

### Reproduction Version

91

### Regression?

86

**Comment by driskull** [comment] 2022-08-22 16:43
Looks like a regression from https://github.com/Esri/calcite-components/commit/1798571cc7e3185c35f68aaf7f63d9377b3bad31 cc @geospatialem

**Comment by anveshmekala** [comment] 2022-08-22 16:55
we may need to remove the `tabIndex` to get this fixed.

**Comment by geospatialem** [comment] 2022-08-22 17:29
> Looks like a regression from [1798571](https://github.com/Esri/calcite-components/commit/1798571cc7e3185c35f68aaf7f63d9377b3bad31)

That it is. Thanks for diagnosing, @driskull!

> we may need to remove the `tabIndex` to get this fixed.

@anveshmekala Removing the `tabIndex` will work for this fix. Thanks for tackling so fast!

**Comment by jcfranco** [comment] 2022-08-23 03:21
Removed `needs triage` label and assigned to this milestone based on the assignment, status label and linked PR.

**Comment by geospatialem** [comment] 2022-09-02 20:01
Verified on beta.93

**Closed by geospatialem** 2022-09-02 20:01 UTC
Labels: bug, 4 - verified, regression
