### ISSUE TITLE
calcite-dropdown: hover state grey dot permanently on first item

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#181] opened 2019-10-18 17:22 UTC
I don't think the calcite-dropdown places the grey dot correctly. When I set a calcite-dropdown-item to active that is not the first one it gets a blue dot correctly, but the first calcite-dropdown-item in the list has a grey dot. When I then hover over other items they get a grey dot while I hover, which is fine. But the first item just keeps that grey dot permanently.

![image](https://user-images.githubusercontent.com/44481292/67114104-fdab7380-f18f-11e9-8cc9-6062d8cd5fce.png)

Here the mouse hovers over 'order in table'
![image](https://user-images.githubusercontent.com/44481292/67114320-81fdf680-f190-11e9-964a-b812c4b23e16.png)

**Comment by macandcheese** [comment] 2019-10-18 17:30
@AdelheidF - The focus state styling is assigned programmatically to the first item in the dropdown when it's opened. Maybe it should just assign focus when opened via keyboard? Not sure the best way to approach that, I think it's an accessibility requirement that an item is focused when the dropdown is opened. cc @paulcpederson did you have some insight here?

**Comment by paulcpederson** [comment] 2019-10-18 17:33
@macandcheese I think we could only show the dot on hover, rather than on hover + focus?

**Comment by macandcheese** [comment] 2019-10-18 17:36
I guess the issue is that, it's potentially a little weird that there's a possible state with an active, a hovered, and a focused item in one dropdown. Removing the dot from either hover or focused maybe solves for that?

**Comment by paulcpederson** [comment] 2019-10-18 17:48
Yeah, to keep it accessible you have to focus into the dropdown when it's opened and the focused item has to have a focus state.

There are approaches where you only show focus styles for keyboard focus and not mouse focus (like `button:focus:not(:focus-visible)` approach), but that won't help here as the focus is programmatically assigned, so you don't really know currently which input mode the user is in. 

I've also tried updating the focus element on hover before, but can also be weird if you have a lot of handlers for focus events.

**Comment by macandcheese** [comment] 2019-10-18 17:52
We could detect how the dropdown has been invoked (click vs. key) and... conditionally assign styling, but, seems like a little much. I believe WCAG says to focus the currently active / selected item which would... eliminate the weirdness, but in a multi-group dropdown, there are potentially multiple active items, I guess you'd need to focus the first one. 

These GH dropdowns throughout these issue pages (overflow ...) allow you to open without focusing, first keystroke focuses first item, but it was my impression that's NOT an accessible practice.

**Comment by paulcpederson** [comment] 2019-10-18 18:05
I don't think you necessarily _have_ to focus the first element, actually. This example from the WAI aria leaves focus on the triggering element until you tab in: https://www.w3.org/TR/wai-aria-practices/examples/disclosure/disclosure-navigation.html

**Comment by macandcheese** [comment] 2019-10-18 18:17
This one does seem to solve by only focusing with keyboard, and not with click, which I think is more analogous than a nav menu with no active state - https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-2/menubar-2.html

What it does is also move focus with hover so you don't end up with three states, just selected and hover/focus as one. 
<img width="798" alt="Screen Shot 2019-10-18 at 11 17 01 AM" src="https://user-images.githubusercontent.com/4733155/67118005-d73e0600-f198-11e9-8560-a447339d834e.png">

**Comment by paulcpederson** [comment] 2019-10-18 18:23
Wow that example is almost exactly what we're doing, I say 🚢 ship it

**Comment by macandcheese** [comment] 2019-10-21 16:38
Before I dive in, @AdelheidF does the above example work for this case - with focus state item being "superseded" by hovered item?

**Comment by AdelheidF** [comment] 2019-10-21 16:43
That seems fine to me, whatever you guys think works best. I first assumed it's a bug what's there now.

**Comment by macandcheese** [comment] 2019-11-01 21:00
Addressed in https://github.com/Esri/calcite-components/pull/211

**Closed** 2019-11-01 22:05 UTC
