### ISSUE TITLE
[calcite-components-react] `active` property on Calcite Modal is not bindable to a boolean in React

### ISSUE THREAD

**Issue by gavinr** [Esri/calcite-components#4317] opened 2022-03-28 17:15 UTC
### Actual Behavior

Creating a modal like this:

```
<CalciteModal active={false}>... </CalciteModal>
```

Shows the modal:
![image](https://user-images.githubusercontent.com/209355/160451423-46a06caf-c353-487b-8eba-c6dbc90fc5e2.png)

### Expected Behavior

The modal should **not** initially show since `active` property is set to `false`

### Reproduction Sample

https://codesandbox.io/s/nostalgic-frost-serugy?file=/src/App.js

### Reproduction Steps

1. Open the sample calcite-components-react:  https://codesandbox.io/s/calcite-template-p95kp?file=/src/App.js
2. add this code:
```
<CalciteModal active={false}>
  <div slot="header" id="modal-title">
    Modal title
  </div>
  <div slot="content">
    Modal content lorem ipsum dolor sit amet, consectetur adipiscing elit,
    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
    enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi
    ut aliquip ex ea commodo consequat.
  </div>
  <CalciteButton slot="primary" width="full" onClick={() => {}}>
    OK
  </CalciteButton>
</CalciteModal>
```

### Reproduction Version

@esri/calcite-components-react v0.21.0

**Comment by benelan** [comment] 2022-03-28 17:19
Possible duplicate of #3230, I'll document that this sprint.

**Comment by benelan** [comment] 2022-03-28 17:35
Correct. [Here is a codesandbox](https://codesandbox.io/s/react-cc-radio-group-change-error-forked-g23wx?file=/src/App.js) with another workaround for the same type of issue.

**Comment by benelan** [comment] 2022-03-28 17:47
Closing this issue as a duplicate of #3230

**Closed by benelan** 2022-03-28 17:47 UTC
Labels: bug, duplicate, 0 - new, needs triage

**Comment by gavinr** [comment] 2022-03-28 18:17
Thanks @benelan!
