### ISSUE TITLE
Overflowing subtree content is clipped

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#5168] opened 2022-08-16 21:22 UTC
### Actual Behavior

Overflowing content within a nested `<calcite-tree>` is clipped by the `"children"` slot container.

<img width="286" alt="Screen Shot 2022-08-16 at 5 08 50 PM 2" src="https://user-images.githubusercontent.com/421496/184986620-2bd41faa-f7fb-4a1b-a06a-4063ef0eeaa2.png">

### Expected Behavior

Overflowing content is allowed to flow out of the `"children"` slot container.

<img width="286" alt="Screen Shot 2022-08-16 at 5 11 10 PM 2" src="https://user-images.githubusercontent.com/421496/184986666-37e6ddad-b06a-4a58-b8d1-2d8454b3ac5a.png">

### Reproduction Sample

https://codepen.io/nwhittaker-esri/pen/ZExmMbQ

### Reproduction Steps

1. Visit the sample
2. Click the overflow menu for _Layer 1_ and note that the menu flows out of the `<calcite-tree-item>` container.
3. Click the overflow menu for _Layer 2.1_ and note that the menu causes the layer name to scroll up and become partially obscured.

### Reproduction Version

beta.91

### Relevant Info

`<calcite-tree>` is uniquely useful for displaying a hierarchy of layers and nested groups of layers. It'd also be helpful to expose within each `<calcite-tree-item>` a menu of actions that can be performed on that layer.

FWIW, removing `overflow: hidden` from the `.children-container` element in the `<calcite-tree-item>` shadow DOM seemed to get things most of the way there (save some `z-index` futzing). The expand/collapse animation appeared to be unaffected and not depending on the overflow style.

**Comment by jcfranco** [comment] 2022-08-24 00:03
@paulcpederson @macandcheese I have a couple of questions:

* Do you recall why tree items use [`overflow: hidden`](https://github.com/Esri/calcite-components/blob/master/src/components/tree-item/tree-item.scss#L111) on the children container?
* Would it be possible to transition on the [children container's height vs transform](https://github.com/Esri/calcite-components/blob/master/src/components/tree-item/tree-item.scss#L116-L117)? The latter will mess up `floating-ui` positioning.

**Comment by paulcpederson** [comment] 2022-08-24 00:34
>  Do you recall why tree items use [overflow: hidden](https://github.com/Esri/calcite-components/blob/master/src/components/tree-item/tree-item.scss#L111) on the children container?

I think Pat added that https://github.com/Esri/calcite-components/commit/3e6e48c57c3a47b540cb1267a4a3a8fbca9f3f98 but I'd assume it's to prevent scroll because the height for collapsed children containers is set to 0

> Would it be possible to transition on the [children container's height vs transform](https://github.com/Esri/calcite-components/blob/master/src/components/tree-item/tree-item.scss#L116-L117)? The latter will mess up floating-ui positioning.

I don't think you can transition to `height: auto` only between a length or percentage https://developer.mozilla.org/en-US/docs/Web/CSS/height#formal_definition

**Comment by paulcpederson** [comment] 2022-08-24 00:36
you could maybe do some JS hijinx and get the auto height as a pixel value and transition to that?

**Comment by geospatialem** [comment] 2023-01-16 23:38
The first `tree-item` has the expected behavior, but subsequent `tree-item`s placement looks off. This is likely a new issue related to floating UI, but wanted to get dev feedback on the expected behavior.

This is the [updated Codepen used for testing](https://codepen.io/geospatialem/pen/QWBqWeN) and the behavior below:

![verify-tree-action-dropdown](https://user-images.githubusercontent.com/5023024/212780237-ea5ab162-0128-45cd-bf3b-34c433228b7f.gif)

@anveshmekala Can you verify if this is the expected behavior of `tree` and `tree-item`, and the placement of the `dropdown-group` has a floating UI, or another issue? If so I will close this issue and create a follow-up issue to tackle.

**Comment by geospatialem** [comment] 2023-01-17 21:33
The issue above has been mitigated, and a new issue addressing the floating UI issue has been created with 6300.

**Closed by geospatialem** 2023-01-17 21:33 UTC
Labels: bug, 4 - verified, milestone adjusted
