### ISSUE TITLE
Bug: Clearable, numeric `calcite-input` with empty value not rendering

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2151] opened 2021-05-14 16:07 UTC
### Actual Behavior
A `<calcite-input>` element crashes when initialized with the following attributes: `type="number"`, `clearable`, and `value=""` (or omit `value`). As a result, no input element is shown.

### Expected Behavior
The input element is present.

### Reproduction Steps or Sample
```html
<calcite-input type="number" clearable></calcite-input>
```

### Relevant Info
Stack trace:
```
TypeError: null is not an object (evaluating 'this.value.length') = $1
  isClearable — calcite-input.entry.js:279:89
  render — calcite-input.entry.js:404:138
  callRender — index-1c5dced1.js:1403
  (anonymous function) — index-1c5dced1.js:1341
  asyncFunctionResume
  consume — index-1c5dced1.js:2758
  flush — index-1c5dced1.js:2811
```

_Version_: `@esri/calcite-components@1.0.0-next.192`

**Comment by caripizza** [comment] 2021-05-20 14:18
According to the prop's documentation, only calcite-input of `type="textarea"` should NOT support the clearable property:
https://github.com/Esri/calcite-components/blob/master/src/components/calcite-input/calcite-input.tsx#L65

Which types of input need to support this property? @eriklharper @macandcheese do either of you know by chance?

**Comment by macandcheese** [comment] 2021-05-20 14:34
It should definitely support number, the docs seem right there (as well as showing by default for the notes types). Seems like this happens only when the number input has a certain set of initial attributes?

**Comment by eriklharper** [comment] 2021-05-20 18:04
@nwhittaker I can't reproduce this locally in `@esri/calcite-components`'s dev server, but I am noticing issues when rendering the self-closing tag, which is not supported for custom elements, so your code should render the input like `<calcite-input type="number" clearable></calcite-input>`.

Could you post a Codepen or something that shows this specific error that you're seeing?

**Comment by caripizza** [comment] 2021-06-08 18:31
@nwhittaker I think this was fixed as of beta.56 as a part of Erik's time-picker feature. Can you confirm?

(If you agree, I'll remove the [BUG comments](https://github.com/Esri/calcite-components/blob/master/src/demos/calcite-input.html#L231) I had added in the demo calcite-input.html page.)

**Comment by nwhittaker** [comment] 2021-06-08 20:19
@caripizza, it looks good in my jsbin -- thanks for following up.

**Comment by caripizza** [comment] 2021-07-23 19:37
Closing this one since it's no longer an issue. (We'll remove the bug comments when we update the input demo html page in #2483.)

**Closed by caripizza** 2021-07-23 19:37 UTC
Labels: 0 - new, bug
