### ISSUE TITLE
non-visible calcite-tooltip sometimes prevents interaction with reference element

### ISSUE THREAD

**Issue by mjuniper** [Esri/calcite-components#4577] opened 2022-05-18 17:28 UTC
### Actual Behavior

When used in another component, non-visible calcite-tooltips are sometimes positioned in a way that prevents interaction with the reference element.

### Expected Behavior

Tooltips should not prevent interaction with the reference element.

### Reproduction Sample

https://codepen.io/mjuniper/pen/XWZRXqV

### Reproduction Steps

1. visit the codepen
2. hover over one of the fabs below the card
3. observe that the tooltip does not show and the fabs can't be clicked

If you instead visit [this codepen](https://codepen.io/mjuniper/pen/OJQmMaV) it will work as expected. That is because in the version of hub-components that codepen uses, we have added the following css to the component:

```css
calcite-tooltip[aria-hidden="true"] {
  @apply pointer-events-none;
}
```

### Reproduction Version

beta.81

**Comment by macandcheese** [comment] 2022-05-18 17:33
Here's a visual to see where it's blocking - we should ensure visibility on this is hidden (or more broadly anywhere `calcite-hydrated-hidden` attribute is used.

![Screen Shot 2022-05-18 at 10 32 12 AM](https://user-images.githubusercontent.com/4733155/169105987-28f9f43b-b330-4fec-91d1-fef2b29805a6.png)
)

**Comment by driskull** [comment] 2022-05-18 18:40
Nice catch. I think we can probably just set `pointer-events:none` on any tooltip/popover that isn't open.

**Comment by driskull** [comment] 2022-05-18 18:40
We don't want to use `display:hidden` as it will mess with the animations

**Comment by driskull** [comment] 2022-05-18 18:57
@mjuniper are you sure you're including the calcite stylesheet? That has the following CSS which seems to be missing...

```css
[calcite-hydrated-hidden] {
  visibility: hidden;
  pointer-events: none;
}
```

https://unpkg.com/@esri/calcite-components@latest/dist/calcite/calcite.css

**Comment by driskull** [comment] 2022-05-18 18:58
Its not a problem on the storybook either. https://esri.github.io/calcite-components/?path=/story/components-tooltip--simple

**Comment by benelan** [comment] 2022-05-18 19:13
It could also be an issue that only occurs within another custom element

**Comment by driskull** [comment] 2022-05-18 19:26
I can move that CSS into a SCSS mixn that we can use in every component that needs it if we have to.

**Comment by driskull** [comment] 2022-05-18 20:41
Yeah I bet the stylesheet would also need to be included in that shadowRoot. So we should probably move this CSS into a mixin so its included inside every component that needs it.

cc @jcfranco.

We should also move the following style:
https://github.com/Esri/calcite-components/blob/master/src/assets/styles/global.scss#L70-L72

The general rule going forward should be that the global stylesheet is for setting CSS custom properties.

**Comment by jcfranco** [comment] 2022-05-18 21:03
Nice catch! 

Sidebar: we can also look into adding a custom stylelint rule to catch anything that doesn't match [Stencil's recommendations](https://stenciljs.com/docs/styling#:~:text=In%20addition%20to,CSS%20resets).

**Comment by driskull** [comment] 2022-05-18 22:55
@jcfranco because the way that Stencil adds a style attribute to the document in light DOM, we can't really override it via styles inside the component.

To get around this, I think we should...

- Remove use of `calcite-hydrated-hidden` attribute
  -  This means all components will be visible by default once `calcite-hydrated` attribute is added.
  -  Pointer events can still be disabled on a component by default since the hydrated attribute only deals with `visibility`.
- If a component needs be hidden by default, the component should set its internals to be invisible via a container in shadowRoot.
  - This means some tests would need to be updated

@jcfranco what do you think?

**Comment by driskull** [comment] 2022-05-20 23:42
Installed. Once the next `next` version comes we can test this out.

**Comment by benelan** [comment] 2022-06-10 18:34
@mjuniper can you please verify that this issue is resolved in `beta.83`?

**Comment by benelan** [comment] 2022-06-15 21:58
I'm having a hard time reproducing this outside of the `arcgis-stat-card` component in the provided sample. Any ideas on how to repro or confirm the issue is fixed @driskull @macandcheese ?

**Comment by mjuniper** [comment] 2022-06-21 21:24
Thanks everyone, this issues is resolved at beta.83.

**Closed** 2022-06-21 21:59 UTC
Labels: bug, 3 - installed
