### ISSUE TITLE
[Slider] Value labels can overflow container bounds and cause scrolling

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-components#4179] opened 2022-03-02 18:55 UTC
### Actual Behavior

If the label has a long string, and abuts the edge of a container, the extra width will cause horizontal scrolling. It also seems to have trouble determining its placement after its added to a container.

A thought would be to "dock" the string at the left or right-most extent of the container, although I could imagine this wouldn't always be desirable.

### Expected Behavior

I'd expect one of a few things to happen. Either the "center aligned" label as currently exists would not cause scrolling (overflowing container bounds ?), or the label would "dock" at the extent. Open to other thoughts there @asangma @driskull

https://user-images.githubusercontent.com/4733155/156428602-363a4e34-c652-4924-81b6-5d79f9ffcee2.mov

 
### Reproduction Sample

https://jsbin.com/kefusizefi/edit?html,output

### Reproduction Steps

1. View the reproduction link
2. Before adjusting the slider, see the horizontal scrolling.
3. Adjust the slider and see the scrolling stop.
4. Toggle the block section
5. View the placement of the label
6. Adjust the second slider - see the label move.

### Reproduction Version

77

**Comment by driskull** [comment] 2022-04-21 22:24
This is a duplicate of #4126

**Comment by jcfranco** [comment] 2022-04-27 02:16
Closing as duplicate.

**Closed by jcfranco** 2022-04-27 02:16 UTC
Labels: bug, 0 - new, milestone adjusted
