### ISSUE TITLE
Bug: `overflow-actions-disabled` attribute not getting set when added at render time in Stencil

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1938] opened 2021-04-08 22:20 UTC
Adding it via jsx in Stenciljs does not add the attribute to the action bar correctly, and the vertical scroll is missing

```tsx
<calcite-action-bar overflowActionsDisabled></calcite-action-bar>
```
![image](https://user-images.githubusercontent.com/52869490/114103133-6d7a5600-987d-11eb-9bd5-ce2be100d35f.png)

If it is added manually in `componentDidRender` it works:
```ts
public componentDidRender(): void {
  this.calciteActionBar.setAttribute("overflow-actions-disabled", "");
}
```
I am not sure if it needs to be set in a different lifecycle method, or is something else. Thanks! @driskull

**Comment by driskull** [comment] 2021-04-12 05:43
@ethanbdev I think it should be one of the following:

HTML
```html
<calcite-action-bar overflow-actions-disabled></calcite-action-bar>
```

JSX
```jsx
<calcite-action-bar overflowActionsDisabled={true} />
```

**Comment by driskull** [comment] 2021-04-12 05:44
Its probably also a duplicate of #1937 so I'll close for now.

**Closed by driskull** 2021-04-12 05:44 UTC
Labels: 1 - assigned, bug

**Comment by ethanbdev** [comment] 2021-04-12 14:24
> @ethanbdev I think it should be one of the following:
> 
> HTML
> 
> ```
> <calcite-action-bar overflow-actions-disabled></calcite-action-bar>
> ```
> 
> JSX
> 
> ```js
> <calcite-action-bar overflowActionsDisabled={true} />
> ```

Yes, sorry, I tried these too. I will track the other issue, thanks!
