### ISSUE TITLE
Stepper throws array length error on render

### ISSUE THREAD

**Issue by evanmosby** [Esri/calcite-components#531] opened 2020-04-29 14:58 UTC
Hi guys,

Been seeing the following error on render for the Stepper component. It appears using the sample provided in the docs too. We are using Vue.JS as a wrapping framework, but so far that's been fairly straightforward 

![image](https://user-images.githubusercontent.com/28676725/80610759-94ce6f00-89ee-11ea-97a2-92e95e258817.png)

Browsers tested:
-Chrome 81.0.4044.12
-Edge 81.0.416.64
-Firefox 75

Test Case Repo:
https://github.com/evanmosby/calcite-stepper-test

**Comment by evanmosby** [comment] 2020-04-29 15:21
Forgot to add, the stepper does function as expected even with that error thrown.

**Comment by macandcheese** [comment] 2020-04-29 19:01
OK, looked into this a little. There are actually additional errors when trying to use our custom keyboard navigation within the component (arrows / home / end) : `TypeError: Cannot read property 'focus' of undefined` - which indicates the array of stepper items isn't being properly created, as the initial error shows as well...

Strangely, using CJS instead of ESM doesn't result in any errors and the component seems to work as intended...

```
import {
  applyPolyfills as applyPolyfillsC,
  defineCustomElements as defineCustomElementsC
} from "@esri/calcite-components/dist/loader/index.cjs";
```

🤔

**Comment by evanmosby** [comment] 2020-04-30 01:16
Hmm, curious. I went ahead and updated our imports as you indicated to use CJS which indeed mitigated those errors. Not sure if this is a Vue thing? To provide some context, the import pattern we're using is from the Stencil docs: [https://stenciljs.com/docs/vue](https://stenciljs.com/docs/vue ).

**Comment by macandcheese** [comment] 2020-06-08 20:07
Fixed in https://github.com/Esri/calcite-components/pull/650

**Closed by macandcheese** 2020-06-08 20:07 UTC
Labels: bug 🐞, component-stepper, framework-vue
