### ISSUE TITLE
Bug: calcite-input showing Arabic characters for numbers only, add an option to switch to western numbers

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3079] opened 2021-09-20 23:23 UTC
Original issue submitted by Olga.

In FF and Safari when language is set to ar numbers in the input boxes appear in Arabic. Chrome doesn't have this problem, it is always showing English numbers. We only want to see English numbers, no matter the user's language.

![image](https://user-images.githubusercontent.com/44481292/134092650-58cda652-dd47-4d9f-8d40-7515e7abd9f2.png)

![image](https://user-images.githubusercontent.com/44481292/134087429-abf2a44d-dd50-4d2a-b7cb-629b1b760375.png)
When dragging the dot of color picker over the colored area the values update with other Arabic numbers.
Same when using up and down arrows.

https://jsbin.com/dutarurohu/edit?html,output

I'm using beta.65, but I also see it with beta.59.

### Actual Behavior

Showing Arabic numbers

### Expected Behavior

only English numbers

### Reproduction Steps and Sample

_Sample_:

Contact me

### Relevant Info

_Version_: `@esri/calcite-components@beta.65`

- [ ] CDN
- [ ] NPM package

**Comment by benelan** [comment] 2021-09-21 17:29
Reproducible in firefox: https://jsbin.com/yarikuquji/edit?html,output

**Comment by julio8a** [comment] 2021-09-23 19:32
@AdelheidF, where does the requirement to only support English numbers come from?
@babakbolour mentioned that showing Arabic characters is the best practice, see comment here: https://github.com/Esri/calcite-components/issues/2765#issuecomment-926079026

**Comment by AdelheidF** [comment] 2021-09-23 19:39
> where does the requirement to only support English numbers come from?

Map Viewer issue 3854

**Comment by babakbolour** [comment] 2021-09-23 23:32
@AdelheidF here is my perspective on this:  What Map Viewer has implemented or restricted users to (English numbers), is Map Viewer (or even Esri app) app specific. Calcite is not only for internal esri-developed apps, but also for public to use and create solutions/GIS apps. For that, it would be best to not exclude or restrict our users to only use English/western digits.
Also, @raje9276 is saying Chrome has now fixed their bug and now show Arabic western digits.

**Comment by AdelheidF** [comment] 2021-09-23 23:57
Ok, is there an option to change it to western?

**Comment by babakbolour** [comment] 2021-09-24 06:10
@AdelheidF let me talk to Olga and get back to you and clarify.

**Comment by babakbolour** [comment] 2021-09-24 21:41
@AdelheidF I chatted with Olga on what she recommended originally and the different recommendations between Olga's and mine.  What Olga did not know when she gave her recommendation, is that Calcite is now a customer-facing product/platform, released to global non-Esri people. Given this new information, she agrees with my recommendation - to support Arabic indic digit in Calcite input. pls let us know if you have additional info or if we can help in anyways - coding, testing, etc cc: @julio8a

**Comment by AdelheidF** [comment] 2021-09-24 22:30
Talked to Olga again and we do want western numbers inside the Map Viewer, because every other piece displayed in that app uses western numbers.

Could we add an option so we can switch between western and Arabic numbers for `calcite-input`?

**Comment by driskull** [comment] 2021-10-13 19:41
https://github.com/Esri/calcite-components/issues/2321

**Comment by AdelheidF** [comment] 2021-10-13 20:20
Sorry, I still don't understand how this should work. 
FF doesn't seem fixed to me when I use `locale="en"`, then it has the wrong decimal.

Below, you can see that French and Arabic both have comma decimals. If I overwrite `locale` (and in the future `lang`) with `"en"` I'm loosing the correct decimal separator.

Tested a bit using FF
![image](https://user-images.githubusercontent.com/44481292/137206020-5d9264c7-52b9-483f-9bf0-139f045a08a8.png)
![image](https://user-images.githubusercontent.com/44481292/137206142-9f3f3bce-1dcc-4822-99cc-128baacc1b76.png)
![image](https://user-images.githubusercontent.com/44481292/137206222-f681852f-a14f-4aa9-a210-6d24c6061831.png)
![image](https://user-images.githubusercontent.com/44481292/137206310-cb5ae5a9-4b3d-4b18-b5aa-3b4384305f4b.png)
![image](https://user-images.githubusercontent.com/44481292/137206383-90792518-5221-4e1e-82e1-87e96b6bb969.png)

**Comment by dasa** [comment] 2021-10-13 22:29
Can the locale include the numbering system? This is how we override the default numbering system for `ar` (`arab`) in the API by using the locale value of `ar-u-nu-latn`.

**Comment by babakbolour** [comment] 2021-10-13 23:47
@dasa which API is that? just wondering if all browsers honor this 'u' extension

**Comment by Olga8614** [comment] 2021-11-23 01:26
Another bug reported for the mixture of Western and Indic numerals: https://github.com/ArcGIS/I18N-MOR-Bugs/issues/2401

**Comment by AdelheidF** [comment] 2022-01-12 23:03
I can't reproduce this anymore. All numbers appear in Western numerals.

![image](https://user-images.githubusercontent.com/44481292/149236856-22502952-3766-43f8-bc79-04df58f32c56.png)

@Olga8614 do you see the same?

**Comment by eriklharper** [comment] 2022-02-09 18:09
> Can the locale include the numbering system? This is how we override the default numbering system for `ar` (`arab`) in the API by using the locale value of `ar-u-nu-latn`.

This is what I would try first before exploring any kind of numbering system override prop.  Because input uses the browser's  `Intl.NumberFormat` api, passing in a locale string for the `lang` prop that specifies the numbering system would be the way I'd recommend achieving something like this.  You can use a template string in your JS to still include the passed-in lang by writing something like `<calcite-input lang="`${document.lang}-u-nu-latn`">`.

**Comment by AdelheidF** [comment] 2022-02-17 01:52
adding that lang doesn't seem to fix it in FF

![image](https://user-images.githubusercontent.com/44481292/154389236-c3e3e8db-659f-4210-a737-c939c8617c7e.png)

**Comment by eriklharper** [comment] 2022-02-18 18:34
Use `locale` instead of `lang` and it should work.  Input hasn't been updated to use `lang` yet so you still have to set it with `locale`.

This example shows the default Arabic display (first one) and Arabic with latin numbering (second one) in Firefox using the `locale` prop:

<img width="962" alt="image" src="https://user-images.githubusercontent.com/821864/154742174-2092ef56-770e-46f3-aab9-73b8d94e0fb4.png">

**Comment by eriklharper** [comment] 2022-02-18 18:35
Based on this, it seems like we can close this issue since western numbers can be set in the locale string.  What do you think @AdelheidF @jcfranco @babakbolour ?

**Comment by jcfranco** [comment] 2022-02-18 19:10
> Can the locale include the numbering system? 

@dasa I was not aware of this. This is awesome, thanks for sharing! 

> Based on this, it seems like we can close this issue since western numbers can be set in the locale string. What do you think

@eriklharper Agreed. 

Sidebar: I'll create a separate issue to update `calcite-input` to use `lang`. It'd be good to do this for consistency.

**Comment by AdelheidF** [comment] 2022-02-25 01:36
OK, adding `locale="ar-u-nu-latn"` does work, but I really don't think it's good that we expect every client to now check the user's locale and add that prop only for ar to every calcite-input box. Same issue if we change the prop to `lang`. It should have at least a prop that can stay the same for all locales. Something like `latin-numbers=true`, and I'd prefer this be the default because it's how we get the same behavior across browsers.

Anyway, `calcite-color-picker`, e.g., has to make this change too.
![image](https://user-images.githubusercontent.com/44481292/155635484-34cbf1b9-fc8d-48b6-8bc9-c9bdb032212f.png)

**Comment by eriklharper** [comment] 2022-02-25 16:42
One solution could be to update your arabic entry in that list to use `ar-u-nu-latn` instead of just plain `ar`  I'm guessing that this might not work because you are relying on the `html lang="ar"` attribute which wouldn't match the name in the json, but if the json file encoded a key/value pair you could store the `key` as `ar` which would match the html lang attribute and then have the value set to `ar-u-nu-latn`:

`{ key: "ar", value: "ar-u-nu-latn" }`

You may not have it set up this way, but if so, this could work.

I can see the benefit in adding a `number-system` property, I can see that being useful.

**Comment by AdelheidF** [comment] 2022-02-25 21:04
We already have an issue for calcite-color-picker: https://github.com/Esri/calcite-components/issues/2476

**Comment by AdelheidF** [comment] 2022-06-01 17:13
How was this solved now? Is there a new prop?

**Comment by anveshmekala** [comment] 2022-06-01 18:50
we added a prop `numbering-system` for `calcite-input` . To get english numbers for a given locale use `numbering-system=latn`  . Numbering System is specific to locale and to set english numbers for a given locale you need to append the attribute given default is not `latn`. Default values are set by [CLDR](https://cldr.unicode.org/translation/core-data/numbering-systems).

**Comment by geospatialem** [comment] 2022-06-06 15:29
Verified in Firefox with `next`.

![verified in next](https://user-images.githubusercontent.com/5023024/172192946-9121b761-c71c-4011-ad96-8ddb363e3cb4.png)

**Comment by AdelheidF** [comment] 2022-06-27 18:29
@geospatialem 
Hi, could I see your test app? How did you get `color-picker` to use the Latin numbering-system with FF?
I also don't see it implemented here: https://github.com/Esri/calcite-components/blob/master/src/components/color-picker/color-picker.tsx#L1014
I think `color-picker` still needs the draft PR from here https://github.com/Esri/calcite-components/issues/2476

**Comment by benelan** [comment] 2022-06-27 19:12
It looks fixed to me by bumping the sample you provided to beta.83 - https://jsbin.com/dutarurohu/edit?html,output

The draft PR is something I recommended to pass through the numberingSystem prop to provide more options, but using the default numberingSystem should fix this issue - https://github.com/Esri/calcite-components/blob/dc475ead3da98356247156a3b316b320770b4196/src/utils/locale.ts#L58

**Comment by AdelheidF** [comment] 2022-06-27 19:24
Oh, that's great. So the default is Latin numbers, I thought that wasn't in the plan originally.

All good then, thanks.

**Comment by babakbolour** [comment] 2022-06-27 19:38
Reading the above, it looks great.  I assume someone will write up the how-to in the documentation, for the customers. or do we need a KB? if later, maybe Aine in my team can help.

**Comment by benelan** [comment] 2022-06-27 19:43
Once the #4801 merges and beta releases, the numberingSystem prop will be documented in the color-picker component reference. Is that what you are referring to?

**Comment by babakbolour** [comment] 2022-06-27 19:46
@benelan yes, assuming this solution is for color-picker only (and not for calcite inout or other components)

**Comment by benelan** [comment] 2022-06-27 20:20
Input already has the prop documented here: https://developers.arcgis.com/calcite-design-system/components/input/#component-api-properties-numberingSystem

color-picker uses input internally, so essentially we are adding the same prop to color-picker and then passing that value to the input. After the next beta release, the `numberingSystem` prop will be documented for color-picker as well. As of now, there is no way to specify the numbering system for color-picker without going into the shadowRoot. However, setting the default numbering system to latin fixed this issue in the meantime.

**Comment by dasa** [comment] 2022-06-27 20:37
Was this verified in Firefox when `navigator.language` started with "ar-"?

**Comment by dasa** [comment] 2022-06-27 21:20
> I'm not sure how to set the navigator language to "ar-...".

That's fine, I was assuming you would have a country code too.

**Comment by benelan** [comment] 2022-06-27 22:04
@dasa In firefox I can set `navigator.language` to `ar-` and it works for me in https://codepen.io/benesri/pen/KKoPExR?editors=1000
![image](https://user-images.githubusercontent.com/10986395/176043456-6e6813b5-dd4f-4b09-a32a-cac9cf4475e0.png)

**Comment by AdelheidF** [comment] 2022-06-27 22:10
I have no idea why it's working differently when I try in FF.

![image](https://user-images.githubusercontent.com/44481292/176044075-5c1adc5b-d8d4-47c8-b0bd-4af2aa2722c5.png)

**Comment by benelan** [comment] 2022-06-27 22:14
Huh, weird. I am on version FF 101.0.1

I only changed this option: 
![image](https://user-images.githubusercontent.com/10986395/176044445-89da65c2-d70c-4829-a4cb-7d800088fe9e.png)

It looks like you also changed this one which may be why we are seeing different results:
![image](https://user-images.githubusercontent.com/10986395/176044490-fd460695-0eb7-4983-b0f5-08d5813ba3b0.png)

So maybe the browser language setting takes precedent over `navigator.language`? Not sure what we can do about that.

**Comment by AdelheidF** [comment] 2022-06-27 22:22
That's correct, but if I change both of those settings to ar I still see the same thing. I would think this is what ar users would see too then.

![image](https://user-images.githubusercontent.com/44481292/176045526-793777d3-7571-4aa7-b502-33e55b316fe8.png)

**Comment by benelan** [comment] 2022-06-27 23:05
@anveshmekala I put in a PR that fixes the issue

**Comment by benelan** [comment] 2022-06-27 23:43
@Olga8614 @annierm18 - Can we have some clarity on this issue, we are looking at two options:

1. Arab users see arab numerals by default in Firefox, and can change the numbering system to latin using a property. In Safari and Chrome it is already latin by default.
2. Arab users see latin numerals by default in all browsers, and they can change the numbering system to arabic using a property.

It sounds like most Esri products went with option 2. Calcite Components also serves non-Esri users, so do you have any thoughts on which option we should go with?

**Comment by driskull** [comment] 2022-06-27 23:57
I'd prefer to maintain browser defaults as well. We should be consistent with native HTML elements.

**Comment by AdelheidF** [comment] 2022-06-28 00:28
It does not make sense to have it work differently between browsers. Calcite should be better than native HTML elements. And since most users of calcite are Esri products I prefer having the default to be Latin. Number input is a very commonly used component and we'd have to add `numbering-system="latn"` to all of the existing ones too. Also, this would prevent having issues when this is forgotten, which is probably a common case. I'd like the default to be Latin (option 2).

**Comment by babakbolour** [comment] 2022-06-28 00:40
There are two sides to this! from one point of view, we need to adapt to customer environment and not force something on them. If they are used to seeing Arabic digits in their choice of browser (Firefox) with everything they do, then we probably need to honor it. on the other hand, it would be good to be consistent WITHIN Esri apps. So we may need to be consistent with JSAPI-enabled esri apps.

**Comment by driskull** [comment] 2022-06-28 00:41
It seems like we are trying to fix a firefox bug. Is there a firefox issue for this that we can maybe track and remove this logic once its fixed?

**Comment by benelan** [comment] 2022-06-28 00:45
Sometimes browsers just make different choices, which is always fun. But I'll look for a FF bug. 

@babakbolour - it sounds like you're saying we should go with option 1 then, and that all of the Esri teams that use the CC need to set the `numberingSystem` prop to "latn"?

**Comment by driskull** [comment] 2022-06-28 00:47
> Sometimes browsers just make different choices, which is always fun. But I'll look for a FF bug.

Yeah, it kind of sucks but I lean toward just honoring what they return for `new Intl.NumberFormat().resolvedOptions().numberingSystem`.

**Comment by dasa** [comment] 2022-06-28 01:02
The default for Safari is also "arab".

**Comment by AdelheidF** [comment] 2022-06-28 01:02
Does calcite-slider also support `numbering-system`?

https://codepen.io/afreitag/pen/jOapXNW

![image](https://user-images.githubusercontent.com/44481292/176064657-24a9a161-f457-40d3-bf00-83ddc002d825.png)

**Comment by AdelheidF** [comment] 2022-06-28 16:02
I noticed calcite-stepper and calcite-time-picker don't seem to use Arabic numbers by default in FF. If we decide to go with Arabic as the default they should probably be all the same. Though I still very much prefer a default that's the same across all browsers.

https://codepen.io/afreitag/pen/jOapXNW

![image](https://user-images.githubusercontent.com/44481292/176226440-1a87ef81-4b25-4106-b38e-bd03dd1fd19f.png)

**Comment by anveshmekala** [comment] 2022-06-28 16:41
CLDR reference for arabic https://icu4c-demos.unicode.org/icu-bin/locexp?d_=en&_=ar

**Comment by jcfranco** [comment] 2022-06-29 18:50
I agree that we should try to align whenever possible with browser defaults, but it doesn't mean we can't make adjustments to make it easier for our users (e.g., `calcite-button`'s default button type is `button` vs `submit`). WRT the defaults, I think we should provide one for consistency and document it clearly. Otherwise, we are forcing users to be aware of this and (IMO unnecessarily), set it. We could then revisit this approach if browsers align on a default in the future.

**Comment by benelan** [comment] 2022-07-08 23:50
Alright, thanks for your patience everyone. The default numbering system for arabic is now latin.  We will be releasing `beta.84` on Monday which will include this change. Users can still use the arab numbering system like:
```html
<calcite-input numbering-system="arab" type="number" value="5"></calcite-input>
```

**Comment by AdelheidF** [comment] 2022-07-09 02:26
`calcite-input` works now with next.515, will someone take care of `calcite-slider` too?

![image](https://user-images.githubusercontent.com/44481292/178088131-6fecd92b-20c0-43a7-8e18-7be4126e2c41.png)

**Comment by jcfranco** [comment] 2022-07-09 02:47
I thought we had already created follow-up issues for this. 🥲 @benelan can we create an issue to update additional components that display numbers? Aside from `calcite-slider`, we may also need to update `calcite-alert`. There may be others.

@AdelheidF Thanks for the reminder. 🏆

**Comment by benelan** [comment] 2022-07-09 03:12
new issue: #4893

**Comment by geospatialem** [comment] 2022-07-15 21:15
Verified the default numbering system for Arabic is Latin across browsers, and when using the `numberingSystem` prop can set to "arab" on `beta.86`. 👍🏻  

Follow-up for the `numberingSystem` prop for `alert`, `slider`, `stepper`, `date-picker`, and `time-picker` will be relayed in #4893.

**Closed by geospatialem** 2022-07-15 21:15 UTC
Labels: bug, p - high, 4 - verified, i18n-l10n, milestone adjusted

**Comment by Olga8614** [comment] 2023-06-01 23:24
cc @eriklharper
