### ISSUE TITLE
calcite-dropdown: width as wide as dropdown-trigger ?

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#404] opened 2020-03-20 19:40 UTC
The design:
<img src=https://user-images.githubusercontent.com/44481292/77197774-fbcd3f80-6aa2-11ea-8518-62adb8667f59.png width=250/>

The component appears inside a shell panel which changes width depending on browser width.
So it's hard to find a width=[s,m,l] that will fit in all cases. 
Really what I would want is a dropdown that is as wide as the `dropdown-trigger` element. Or one that is at least as wide as the `drodown-trigger` element and expands with longer text like the standard HTML dropdown.

<img src=https://user-images.githubusercontent.com/44481292/77198112-9cbbfa80-6aa3-11ea-9eb1-8c96aa86cf16.png width=200/><img src=https://user-images.githubusercontent.com/44481292/77198038-77c78780-6aa3-11ea-82be-025a0f92f138.png width=200/>

Maybe a `width=auto`?

Current implementation with a  small screen (width=s)
<img src=https://user-images.githubusercontent.com/44481292/77198311-fde3ce00-6aa3-11ea-91f5-b01b4f6575a5.png width=200/>

With a little bit bigger screen.
<img src=https://user-images.githubusercontent.com/44481292/77198439-31bef380-6aa4-11ea-8cc5-1d4b0103820c.png width=220/>

**Comment by macandcheese** [comment] 2020-03-20 21:26
Yeah, it may be worth it to add a few options here... one that was fixed to the size of the trigger element, one that expanded the dropdown (to edge of page) based on length of content, and... maybe some combination of those?

For naming... 
- "constrain to width of trigger" = `inherit` or `trigger`
- "size to width of content (not extending past edge of page)" = `auto`
- "constrain to width of trigger, (dropdown could not be narrower than trigger) , but extend to edge of page if width was wider" - `?????`

Thoughts?

**Comment by dhrumil83** [comment] 2020-04-07 17:13
Same issue with font dropdown:

![image](https://user-images.githubusercontent.com/14285436/78699037-13d0fb80-78b8-11ea-8692-6a5cf485de9e.png)

**Comment by macandcheese** [comment] 2020-04-07 18:03
Yeah, will be a good enhancement to make. Would probably just need to get the width of the slotted `dropdown-trigger` element, and check for updates to that width for resize, etc. 

@dhrumil83 - it looks like there are some alignment issues as well caused by adding additional content into the slot besides text, maybe we could solve that by having more aggressive flex-positioning rules on the `calcite-dropdown-item`. It may be solvable in your case by positioning those in a right-aligned manner, but the dot should ideally just line up with all slotted content.

**Comment by jcfranco** [comment] 2020-08-13 16:59
@macandcheese FYI reassigning this one.

**Comment by jcfranco** [comment] 2021-09-08 18:24
@Esri/calcite-design-representatives Do we need to make the width customizable? If so, what are the primary use cases? 

I took a look at some other component libs (from https://open-wc.org/guides/community/component-libraries/) and it seems like the dropdown content is at least the width of the trigger.

1. https://patternflyelements.org/components/dropdown/
1. https://shoelace.style/components/dropdown
1. https://www.htmlelements.com/demos/dropdownlist/overview/
1. https://component.kitchen/elix/DropdownList
1. https://crayons.freshworks.com/components/dropdown-button/#usage
1. https://boltdesignsystem.com/pattern-lab/?p=viewall-components-dropdown
1. https://web-components.carbondesignsystem.com/?path=/story/components-dropdown--default

**Comment by macandcheese** [comment] 2021-09-08 19:23
I find the current a s, m, l width scale to be unneeded. The chances one of our "other" options happens to work for a use case seems low. We should just default to a single width per scale. 

That said, I think the easiest way to allow customizable might be to expose a custom css property on `calcite-dropdown`, similar to modal? This way the vast majority of dropdowns would be of consistent default width, but the option to customize it would be available.

A more comprehensive approach might be to have some "widthMode" property that allowed you to select from a set of options like "min-width is that of trigger", "fit to content", or "default width".

Re: use cases - I think the screenshots above illustrate the need for the optional "fit to width of trigger" functionality, perhaps not a specific pixel width?

**Comment by patrickarlt** [comment] 2021-10-29 23:17
We have run into this on pages like https://developers.arcgis.com/net/wpf/sample-code/choose-camera-controller/#sample-code at narrow screen widths there filenames are cut off.

![139301719-dd11540d-fcee-442c-9f96-38e0ee5dc274](https://user-images.githubusercontent.com/378557/139510654-ea754686-3656-4ca6-a6f0-caa61894f15a.png)

This usually cuts off the extension which is essential since sometimes files have the same name with different extensions.

**Comment by macandcheese** [comment] 2021-11-20 00:32
@patrickarlt would the above use case be solved if the text would wrap lines?

**Comment by AdelheidF** [comment] 2021-11-20 00:46
> would the above use case be solved if the text would wrap lines?

The native component doesn't wrap, it just gets wider. It might become a messy look if things start wrapping especially if the text has no spaces. I definitely prefer no wrapping.

**Comment by macandcheese** [comment] 2021-11-20 00:50
Which native component are you referencing - a select?

Are the screenshots in the OP still using this `calcite-dropdown` still? I think `calcite-select` or `calcite-combobox` may be better fits, I'm not sure if they existed or were capable enough when this issue was opened.

**Comment by AdelheidF** [comment] 2021-11-20 01:14
Correct, the calcite-select didn't exist when I opened this issue. And calcite-select is doing it fine.
![image](https://user-images.githubusercontent.com/44481292/142708753-42f2b73d-ec34-471c-96af-f18dc51bad23.png)

This is still using calcite-dropdown, but I will change it to calcite-select now.
![image](https://user-images.githubusercontent.com/44481292/142708853-c056f8a5-2ee2-4409-8054-85ddd7b62904.png)

But why would it be better for calcite-dropdown to wrap text instead of displaying the whole thing as wide as it needs to be?

**Comment by patrickarlt** [comment] 2021-12-03 20:22
> @patrickarlt would the above use case be solved if the text would wrap lines?

@macandcheese generally not because we often have really long text that is considred "1 item" like a file name that shouldn't wrap or doesn't have a character that is a break point.

**Comment by AdelheidF** [comment] 2022-02-25 00:01
The original test case has been changed to calcite-select a while ago.
![image](https://user-images.githubusercontent.com/44481292/155627499-f6654cf4-f8b8-4a54-8eb9-883f11a2fa1a.png)

The font selection has images that calcite-select or calcite-combobox don't support. So it's still a valid issue.

![image](https://user-images.githubusercontent.com/44481292/155627699-d684e06e-af22-49e7-8337-ce3aa7d305c8.png)

**Comment by macandcheese** [comment] 2022-02-25 00:16
My thoughts on this are still along the lines of "A more comprehensive approach might be to have some "widthMode" property that allowed you to select from a set of options like "min-width is that of trigger", "fit to content", or "default width"."

**Comment by jcfranco** [comment] 2022-02-25 23:24
@macandcheese Sorry for sounding like a broken record, but do we really need an option to customize the width? It seems heavy-handed. [Rehashing my earlier comment](https://github.com/Esri/calcite-components/issues/404#issuecomment-915469219), but could we:

1. have the dropdown's minimum width be the width of the trigger and,
2.  allow it to grow if the dropdown items are wider than the trigger?

If this doesn't cover all use cases, for clarity, can you share the ones for a narrower-than-trigger dropdown?

**Comment by macandcheese** [comment] 2022-03-03 22:23
> If this doesn't cover all use cases, for clarity, can you share the ones for a narrower-than-trigger dropdown?

I don't think there is a use case for the dropdown being "narrower-than-trigger". But very often, dropdowns are triggered by a square "icon action" of 48px width. In these cases, setting the minimum width to 48px is useless - the content will always be wider. 

Imagine a set of three actions, that each launches a dropdown to configure x. Some of the dropdown-items are longer than others. Without a consistently set default pixel width (300px, 10em, whatever), each dropdown would be a different width. It would be better from a UI standpoint to have each dropdown be of consistent width and wrap the text where word breaks occur. 

This is why I suggest having a "default" and a "fit content" mode, where:

In default mode, as proposed, if the trigger is 48px (example), the min-width would be 300px (or whatever single value we choose). If the trigger is 500px, the min-width, and max-width would be 500px so dropdown is as wide as the trigger. I suggest we remove the "width" property - that would no longer be needed.

a new "fit content" mode - no default px width (other than trigger min-width)- this would solve the "file name being longer than trigger" use case.

Both of these behaviors are shown in the examples provided, but none seem to solve all the use cases brought up in this thread.

**Comment by jcfranco** [comment] 2022-03-04 21:22
Thanks for the rundown. I know the proposed changes would cause some open dropdowns to be a different width in some cases, but wouldn't it be better for ergonomics to not have the user think about this? 

Even with the sizing mode prop, I think you would also run into an issue of inconsistent trigger sizes if they're not using the same element + configuration.

In any case, I ~hacked~ whipped up a prototype: https://codepen.io/jcfranco/pen/OJOdbdP?editors=1000 

### Pros

- better suited for items where the size won't be known upfront (from a service endpoint or translation)
- users do not need to think about the width of the content
- removes need for the `width` prop

### Cons

- needs custom styling on the group or item if the item layout requires it (e.g., item + trailing icon) ⚠️
- open dropdowns may differ in width based on trigger or content (minor?)

Would something like this work? If so, could we proceed with this for now and gauge feedback?

**Comment by macandcheese** [comment] 2022-03-04 21:37
I agree the width difference is minor, although not ideal - that we can live with if needed.

The "have to set width:200px" on your dropdown group because you've used our built-in icon offering seems weird. If that can be handled by the component without needing to choose a width-mode, it would be a better option. 

Just IMO - Opting into a prop for the "really long non-wrapping string" use case doesn't seem that arduous, and solves (I think) for every possible use case, while keeping the current default behavior. Although I understand it is one more thing for the component to maintain - if I'm alone on this I can just let it go at this point.

**Comment by driskull** [comment] 2022-05-27 22:28
@macandcheese @jcfranco would this solve the issue: https://github.com/Esri/calcite-components/pull/4635

- Set the minWidth of the dropdown to the size of the trigger.
- Remove default width value of "m". Without a defined width he dropdown will take up the space it needs.
- Remove flex width on trigger container

**Comment by jcfranco** [comment] 2022-06-03 21:20
@driskull Nice! From what I understand, your solution strikes a good balance.

**Comment by benelan** [comment] 2022-06-10 18:59
verified on beta.83

I took the [prototype codpen](https://codepen.io/jcfranco/pen/OJOdbdP?editors=1000) Franco put together and removed all of the hacky code. Looks good! - https://codepen.io/benesri/pen/poaQWRJ

**Comment by AdelheidF** [comment] 2022-06-27 23:24
symbol styler currently (next.468 ~= beta.82) has this

![image](https://user-images.githubusercontent.com/44481292/176052694-1680f186-a676-42e0-926d-5d411dda779e.png)

When I upgrade to beta.83 I see this

![image](https://user-images.githubusercontent.com/44481292/176052290-9ee2e979-ba72-4694-a1cb-9f55d80b6190.png)

The button no longer shows the line and the width is not as wide as the dropdown button. 
I don't see a breaking change listed.

-----------------

font selection for labels currently (next.468) looks like this

![image](https://user-images.githubusercontent.com/44481292/176053153-74ed68ac-3bc6-48f5-a02a-4efb86e1c328.png)

with beta.83 it's like this

![image](https://user-images.githubusercontent.com/44481292/176052919-e70da2e7-2e98-4f00-9788-b75b34fd168b.png)

**Comment by driskull** [comment] 2022-06-29 16:50
This is the change that altered that width. I'll see if we can revert it.

https://github.com/Esri/calcite-components/commit/7ad58acd9e26ebcd8dfdb79f4ab99b3c559e6d13#diff-f5e51bae797d7632e72f2d68b1b3b6bf9256ad8e6614ef9768b317e803ba382bR32

**Comment by AdelheidF** [comment] 2022-06-30 15:33
looks good with v1.0.0-next.504

**Comment by AdelheidF** [comment] 2022-07-09 02:31
Missed something, seeing it with next.510

![image](https://user-images.githubusercontent.com/44481292/178088377-67a83ab0-8aab-4941-87c0-5f90c9c6f6d9.png)

**Closed** 2022-07-09 02:40 UTC
Labels: enhancement, help wanted, 4 - verified, milestone adjusted

**Comment by AdelheidF** [comment] 2022-07-09 03:04
FYI. We had just added `position: relative;` to all those dropdowns in lists to fix the not being sticky scrolling issue with the menu. But this now messes up the width. Need to remove it again, seems to still be sticky now.

![image](https://user-images.githubusercontent.com/44481292/178089212-ba83b049-b35f-4f70-b549-10bdac8fbc59.png)
