### ISSUE TITLE
Tooling: cannot run calcite-components locally, getting build errors on the css files

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1941] opened 2021-04-09 15:36 UTC
## Summary 
Trying to run calcite-components locally, with this workflow:
clone -> `npm install` -> `npm start` and hit build errors on the css files like so:
![image](https://user-images.githubusercontent.com/52869490/114204831-7e26dc80-990e-11eb-9170-092fec805276.png)

I get numerous similar errors on many components. This is on:

Node v14.14.0
Npm 6.14.9
Windows 10

Is there a step I am missing to setup Tailwind?

**Comment by caripizza** [comment] 2021-04-30 19:20
@ethanbdev were you able to resolve this issue on your end based on [the Teams conversation](https://teams.microsoft.com/l/message/19:fd15b51dacd24e70895ec1218a54ae06@thread.skype/1617979641752?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1617979641752&teamName=Calcite%20Design%20System&channelName=Calcite%20Components&createdTime=1617979641752)?

**Comment by ethanbdev** [comment] 2021-05-05 16:08
> @ethanbdev were you able to resolve this issue on your end based on [the Teams conversation](https://teams.microsoft.com/l/message/19:fd15b51dacd24e70895ec1218a54ae06@thread.skype/1617979641752?tenantId=aee6e3c9-711e-4c7c-bd27-04f2307db20d&groupId=56fae21a-9407-4943-859f-a9bfcf0bbad3&parentMessageId=1617979641752&teamName=Calcite%20Design%20System&channelName=Calcite%20Components&createdTime=1617979641752)?

No luck, @caripizza. I still get postcss errors.. Is anyone else using calcite on windows?
![image](https://user-images.githubusercontent.com/52869490/117173247-70d00700-ad81-11eb-8d9f-9454567470c3.png)

**Comment by benelan** [comment] 2021-10-01 23:16
closing this issue as a duplicate of #2697

**Closed by benelan** 2021-10-01 23:16 UTC
Labels: question, tooling, 0 - new
