### ISSUE TITLE
calcite-input type="number" doesn't support display or entry of locale-specific number characters

### ISSUE THREAD

**Issue by eriklharper** [Esri/calcite-components#2765] opened 2021-08-09 18:22 UTC
> @eriklharper what is the behavior with native numbers like Arabic?
> 
> Does input accept native numbers like these
> 
> ١	٢	٣	٤	٥	٦	٧	٨	٩

Doesn't look like it currently.  I see a brief flash of the arabic numerals on initial load, but it looks like one of our number validator functions ignores them so we'll have to convert the localized number characters back to english numbers to do the validation instead of validating the locale characters. Thanks for testing this!  I'll create a new issue that adds locale numeral support, and this will apply to all other languages that use different number characters as well.

_Originally posted by @eriklharper in https://github.com/Esri/calcite-components/issues/2127#issuecomment-895438708_

**Comment by julio8a** [comment] 2021-09-09 16:12
this one needs to be triaged

**Comment by eriklharper** [comment] 2021-09-09 17:05
I think we'll want to make language-specific issues for this effort.  After spending some time researching this, we'll have to employ some third party JS libraries (or write them ourselves) for translating, for example Arabic characters into English for the purpose of storing the english equivalent values in state and in event emitters.  We can start with Arabic, since this is one language we definitely need to support.

**Comment by julio8a** [comment] 2021-09-22 23:34
@babakbolour What's the best approach here?

**Comment by benelan** [comment] 2021-09-23 00:43
Related issue: #3079

**Comment by babakbolour** [comment] 2021-09-23 04:18
@julio8a I have to pull in @raje9276  to comment on the approach/solution. we may need one for Web apps and a diff approach for Windows. (side note - it was just lately that MS removed the 'Native digit' setting from the Region setting)

**Comment by raje9276** [comment] 2021-09-23 05:44
@julio8a Is the requirements to accept both Western and Arabic numbers?

**Comment by raje9276** [comment] 2021-09-23 05:51
Chrome Arabic issue: https://bugs.chromium.org/p/chromium/issues/detail?id=694391. When UI language is set to Arabic, input type number accepts Arabic numbers.

**Comment by julio8a** [comment] 2021-09-23 16:42
@raje9276 and @babakbolour, this issue references the use of local number support. However, this issue #3079 is requesting only English number support. We are looking for guidance and best practices from the i18n team on the best way to move forward.

**Comment by babakbolour** [comment] 2021-09-23 19:06
@julio8a  our team recommendation is to support Arabic native digits in inout and display. this is industry standard. Many esri apps do support this and some don't. However with Calcite going public, it emphasizes more on this nativie digit support requirement.  FF, Chrome/Edge, Safari all support this.  @raje9276 can work with you and others if you need some coding best practices.

**Comment by benelan** [comment] 2021-11-20 00:14
closing as duplicate of #3079

**Closed by benelan** 2021-11-20 00:14 UTC
Labels: bug, duplicate, a11y, 0 - new, i18n-l10n
