### ISSUE TITLE
Popover and Tooltip do not auto-position itself correctly when placed inside other components on non-chromium browsers

### ISSUE THREAD

**Issue by sonofflynn89** [Esri/calcite-components#5429] opened 2022-10-10 23:33 UTC
#### Popover
I was able to reproduce this bug with a `calcite-popover`  /  `calcite-card` combo, though I suspect that other component combinations might also exhibit this behavior. Essentially, you have to position the popover trigger in such a way that the popover would be hidden if it flowed to the right (default behavior).

In a Chrome window, the popover correctly positions itself to the left of the trigger to avoid overflow:

![image](https://user-images.githubusercontent.com/30124777/194966621-249379f9-2728-4406-b289-dc0a96439569.png)

On either Firefox or Safari windows, the popover positions itself to the right of the trigger, is hidden due to overflow, and is not completely vertically centered:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/30124777/194966663-6d2e2733-7e4e-421b-9866-8ced24995f2a.png">

#### Tooltip

**Firefox/Safari**:
![image](https://user-images.githubusercontent.com/5023024/196545264-9a695b31-1841-4cab-8903-9b5e6eb74d93.png)

**Chromium**:
Tooltips and popovers with `overlay-positioning="fixed"` are not initially positioned properly. On first target hover the tooltip or popover becomes visible and then moves to correct position. All subsequent openings are fine.

### Expected Behavior

On Safari / Firefox, the popover correctly positions itself to the left of the trigger to avoid overflow, just like on Chrome. The popover is also vertically centered.

#### Popover
https://codepen.io/sonofflynn89/pen/YzLROEP

#### Tooltip
- Firefox/Safari browsers: https://codesandbox.io/s/gifted-tess-bujev9
- Chromium browsers: https://codepen.io/COV-GIS/pen/vYjwZLN

#### Popover
- Open the [codepen](https://codepen.io/sonofflynn89/pen/YzLROEP) in Chrome
- Click the button
- Notice that the popover auto-positions itself to the left, avoiding overflow

- Open the [codepen](https://codepen.io/sonofflynn89/pen/YzLROEP) in Safari / Firefox
- Click the button
- Notice that the popover auto-positions itself to the right, is hidden by overflow, and is not vertically centered

#### Tooltip
- Firefox/Safari browsers: Hover over the items in the shell and see that "absolute" positioning has an offset the height of the header in the calcite shell
- Chromium browsers: Hover over target, optionally uncomment js for workaround

### Reproduction Version

1.0.0-beta.95

### Esri team

ArcGIS Hub

**Comment by sonofflynn89** [comment] 2022-10-11 21:46
After further experimentation, it seems as though something is not just screwing up the placement calculations for auto, but for all placement types in these non-chromium browsers. And the weirdest thing is that it only happens when we wrap the popover in a calcite-card. For example, look where the hidden popover element is positioned when the popover is wrapped in a div:

![image](https://user-images.githubusercontent.com/30124777/195204227-3da96baf-3e83-4757-a8cc-df1dbb3ccee9.png)

vs when the popover is wrapped in a card:

![image](https://user-images.githubusercontent.com/30124777/195203931-ad857529-726d-41b7-98cf-9d1c8965f60a.png)

**Comment by jcfranco** [comment] 2022-10-14 00:07
Thanks for submitting this one. 

This is a regression from a `@floating-ui/dom` update (see https://github.com/Esri/calcite-components/issues/5146#issuecomment-1267699351). This is also a duplicate of the referenced issue. 

@geospatialem @brittneyzwolfer Maybe we can keep this open until ☝️ is resolved for tracking purposes?

**Comment by COV-GIS** [comment] 2022-10-18 21:32
Thanks for working on this @jcfranco and @geospatialem.

Just to be clear...this is behavior is present in chromium browsers.

**Comment by geospatialem** [comment] 2022-10-18 22:00
@COV-GIS, Thanks for clarifying - should have linked 5515 to the more related #5146. 

We've got a PR in progress to address both issues.

**Comment by COV-GIS** [comment] 2022-10-19 18:40
Two more scenarios of the visible reposition with overlay positioning absolute in chromium:

1. On window resize. Increase width in particular, but possible with both axes increase/decrease.
2. If an element up the dom tree is initially hidden, e.g. a header action tooltip in a panel hidden in a shell panel after becoming unhidden.

Resize can reproduced on the docs page https://developers.arcgis.com/calcite-design-system/components/tooltip/.

**Comment by jcfranco** [comment] 2022-10-20 17:01
@COV-GIS Thanks for the additional scenarios. I did want to mention that what you're observing is most likely related to https://github.com/Esri/calcite-components/issues/5399 (delayed repositioning) and not this issue.

**Comment by jcfranco** [comment] 2022-10-20 17:16
Quick update on this one: I managed to wire up floating-ui's reverted code and only have it apply to non-Chromium browsers, but I'm noticing performance degradation (more so than what was reported in https://github.com/Esri/calcite-components/issues/5286. Going to look into this some more and see if I can get perf to an acceptable state.

**Comment by jcfranco** [comment] 2022-10-21 21:07
Found a promising solution, I'll submit a PR and maybe this can land by today or early next week at the latest.

**Comment by geospatialem** [comment] 2022-10-27 14:23
Verified in `beta.96`.

### Popover
#### Firefox:
![verify-1](https://user-images.githubusercontent.com/5023024/197630211-c46c2f8e-c3e4-459f-940f-cb493fba9b06.png)

### Tooltip

#### Firefox:
![verify-tooltip-firefox](https://user-images.githubusercontent.com/5023024/198310764-d4fe6eac-91ac-448e-9d53-e2f1abafe9c6.gif)

#### Chrome:
![verify-tooltip-chrome](https://user-images.githubusercontent.com/5023024/197631501-2a9710d5-6573-488d-8cfd-ddb47a8ddd33.gif)

**Closed by geospatialem** 2022-10-27 14:23 UTC
Labels: bug, browser-safari, browser-firefox, p - high, 4 - verified, regression, milestone adjusted, ArcGIS Hub
