### ISSUE TITLE
Bug: tooltip flashes on mobile

### ISSUE THREAD

**Issue by isaacviel** [Esri/calcite-components#2171] opened 2021-05-19 15:28 UTC
### Actual Behavior

On iOS a button label appears after clicking button 

### Expected Behavior

When clicking on this button, I should not see the hover/label 

### Reproduction Steps or Sample

On a mobile device/simulator:
1. Navigate to https://master.sites.afd.arcgis.com/pricing/tile-estimator/ (Currently on dev only, prod after 5/20)
2. Click the `<<` icon in the top right to collapse the sidebar
3. Click the filter icon to open the sidebar
4. Notice the `Collapse` hover label appear in the top right then jumps down the `<<` location then disappears. This label should not show it self at all on this tap let alone in the top corner then jump. 

![calcite](https://user-images.githubusercontent.com/3312529/118840231-0f795f00-b87c-11eb-8b38-4127378329b8.gif)

### Relevant Info

iOS simuator

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by driskull** [comment] 2021-05-19 16:57
It seems like this is the tooltip on the expand/collapse. It appears to be showing delayed because the simulator is running very slow.

I'm not sure what we can do to address this.

**Comment by isaacviel** [comment] 2021-05-19 17:10
Thanks @driskull 

That's actually just the gif. The conversion from mov to gif really slowed it down which helps see the issue but misrepresents the speed. Even in real-time, the issue is quite obvious as a flash.

**Comment by driskull** [comment] 2021-05-19 20:30
I think the issue is that when clicking it, it focuses it which triggers the tooltip to show.

**Comment by isaacviel** [comment] 2021-05-19 20:54
Yeah, it seems like that's the issue for sure. Thanks @driskull

**Comment by jcfranco** [comment] 2021-05-24 17:21
@isaacviel This was installed last week. Can you help verify w/ `next`?

**Comment by isaacviel** [comment] 2021-05-24 17:49
You bet. Where exactly should I be testing?

**Comment by jcfranco** [comment] 2021-05-24 18:15
If possible, could you update the tile-estimator app to use the latest release?

**Comment by isaacviel** [comment] 2021-05-24 18:48
Thanks @jcfranco. We're hoping to be upgraded to the lasted version this week. I'll test as soon as we have an environment up.

cc @noahmulfinger

**Comment by jcfranco** [comment] 2021-05-24 18:52
Sounds good. I'll go ahead and close this as self-verified then since our sprint is done. Please submit a new issue if you find anything else to address.

**Comment by jcfranco** [comment] 2021-05-24 18:52
Closing as self-verified.

**Closed by jcfranco** 2021-05-24 18:52 UTC
Labels: 3 - installed, bug

**Comment by isaacviel** [comment] 2021-05-25 16:20
@jcfranco this is still happening only the label is white now. 

Here's a test from our Calcite Components v55 preview site:


https://user-images.githubusercontent.com/3312529/119533083-5b277f00-bd3a-11eb-949b-d5b066cbe260.mov
