### ISSUE TITLE
Bug: error when using calcite-radio-group with Maquette.js (in JS API)

### ISSUE THREAD

**Issue by hccampos** [Esri/calcite-components#2204] opened 2021-05-25 14:45 UTC
### Actual Behavior

Creating a simple `calcite-radio-group` with Maquette.js triggers an exception and prevents the component from working:

![Screen Shot 2021-05-25 at 15 33 11](https://user-images.githubusercontent.com/3759114/119517881-4a95f980-bd78-11eb-9b1d-c39cf5130381.jpg)

### Expected Behavior

- The component should work normally.

### Reproduction Steps or Sample

Happens with a simple usage of the component, like so:

```jsx
<calcite-radio-group
  layout="horizontal"
  scale="m"
  bind={this}
  onCalciteRadioGroupChange={this._onModeChange}
>
  <calcite-radio-group-item
    value="foo"
    checked={mode === "foo"}
  >
    {messages.continuousLabel}
  </calcite-radio-group-item>
  <calcite-radio-group-item
    value="bar"
    checked={mode === "bar"}
  >
    {messages.hourlyLabel}
  </calcite-radio-group-item>
</calcite-radio-group>
```

1.

### Relevant Info

_Version_: `@esri/calcite-components@beta.55`

- [ ] CDN
- [x] NPM package

<sub>SVCH</sub>

**Comment by jcfranco** [comment] 2022-03-14 21:14
@hccampos Can you confirm if this is still an issue? I could not reproduce with the latest version used by the API.

**Comment by jcfranco** [comment] 2022-06-30 23:26
@hccampos Let me know if this is still an issue. Closing for now.

**Closed by jcfranco** 2022-06-30 23:26 UTC
Labels: bug, 0 - new, needs triage, need more info
