### ISSUE TITLE
Component Date + Date Range

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-components#58] opened 2019-06-14 19:24 UTC
Draft spec for a date picker component. This is a very common need for almost every team, so would be good to start working on this one. Below is a rough draft:

# Date

Browser-consistent date selection can be accomplished with the `calcite-date` component. Set `value`, `min`, and `max` properties. Value will default to today if no value is provided:

```html
<calcite-date value="2017-06-01" max="2019-06-01"></calcite-date>
```

We suggest you wrap the component and add a visible label for clarity:

```html
<label>
  Due date
  <calcite-date value="2017-06-01" max="2019-06-01"></calcite-date>
</label>
```

When using with React, an input can be passed in which will act as the source of truth:

```html
<label>
  Due date
  <calcite-date>
    <input type="date" min="2016-06-01" max="2019-06-01" value="2017-06-01">
  </calcite-date>
</label>
```

## Events:
- `calciteDateChange` emitted with standard event properties plus `details: {date: "2018-03-05"}`

## Date Range

Frequently a UI will need to ask the user for a `start` and `end` date. Wrapping two `calcite-date` components inside a `calcite-date-range` will do the legwork of ensuring dates don't overlap:

```html
<calcite-date-range>
  <calcite-date slot="start" value="2017-06-01" min="2016-06-01"></calcite-date>
  <calcite-date slot="end" value="2017-06-01" max="2019-06-01"></calcite-date>
</calcite-date-range>
```

## Events:
- `calciteDateRangeChange` emitted with standard event properties plus `details: {startDate: "2018-03-05", endDate: "2018-03-05"}`

---

Questions include:

- how to integrate moment into the build without bloating people's apps
- how to do locale-specific date formatting

---

Assigning to @julio8a to add his designs he's working on into this issue. We can work through API questions here prior to implementation.

**Comment by ekenes** [comment] 2019-08-09 17:09
ccing myself @ekenes since I want to track progress on this for our Smart Mapping workflows in the JS API.

**Comment by ekenes** [comment] 2019-08-20 19:59
@julio8a @kumarGayu What is the estimated milestone for this? There are several JS API widgets that would like to take advantage of this component.

**Comment by kumarGayu** [comment] 2019-08-20 20:09
@ekenes Right now i am in training for 2 weeks, but by then whenever i get free time i will make this available. However, now we have the date picker in place for light theme.

**Comment by ekenes** [comment] 2019-08-20 20:22
Cool! So date + time picker is already available for light themes?

**Comment by kumarGayu** [comment] 2019-08-20 20:41
Time is not yet there. :(

**Comment by ekenes** [comment] 2019-08-20 22:04
Ok. What's the approximate timeline for adding time?

**Comment by kumarGayu** [comment] 2019-08-20 22:33
a week or 2 max.

**Comment by macandcheese** [comment] 2019-09-24 23:31
Hey @kumarGayu - any update on the status of this or the related Edge issue? https://github.com/Esri/calcite-components/issues/137 - thanks in advance!

**Comment by ffaubry** [comment] 2019-11-08 17:26
A bit of late feedback.

#### Feedback 1
A the case for a single calendar range selector. For Dashboard UI, the double calendar range selector is over killing. Too much space, etc. I would encourage a more compact range selector relying on a single calendar. You can look at:
- https://ember-power-calendar.com/docs/range-selection

#### Feedback 2
The case for date pattern. Currently if the calendar is set to French, the placeholder shows: DD/MM/YYYY.

DD, MM, YYYY have only a meaning for english language.
In German DD should TT, in French should be JJ.
My point is this pattern has no meaning outside of english speaking countries and it's inner guts exposed outside.

#### Feedback 3
I really hope that the calendar is a component by itself and can be decoupled from the click button behavior and hosted in other components such as Modal or just by itself.

#### Feedback 4
The current calendar is not using calcite colors. 

#### Feedback 5
As I type in the input box a date, the calendar doesn't reflect the date.
![image](https://user-images.githubusercontent.com/3506166/68497630-dc2b2e00-0209-11ea-8d7c-7a7bd3234364.png)

**Comment by macandcheese** [comment] 2019-11-10 21:35
@ffaubry agree on those points - @julio8a can we make some tweaks to support single input range? - would likely just need to update the input area a bit.

**Comment by evanmosby** [comment] 2020-01-17 06:53
One additional thought would be to consider a slot for range shortcuts? For instance, select yesterday, last week, month etc. A simple example: [Link](https://mengxiong10.github.io/vue2-datepicker/index.html#Shortcut
)
Monitor's got a bunch of date range selections - we're super interested in this. Looking epic!

**Comment by macandcheese** [comment] 2020-01-23 23:53
Agree @evanmosby I'd say that's almost expected behavior for many use cases.

**Comment by paulcpederson** [comment] 2020-04-06 23:14
@julio8a can you post the design for single input range selection?

**Comment by ffaubry** [comment] 2020-04-06 23:36
@paulcpederson could add Ben to this repo?
He will provide our requirements for this.
He has been designing our date UX for dashboard.

**Comment by julio8a** [comment] 2020-04-06 23:47
Designs for single input range:
![image](https://user-images.githubusercontent.com/6144462/78615416-50541700-7826-11ea-8587-6bcae84bbac4.png)

@ffaubry, I added Ben to the repo.

**Comment by evanmosby** [comment] 2020-04-30 01:51
Hi guys, curious as to the timeline on this one. The Monitor product could sure use a date range picker :) We can implement two individual pickers today to get us by, but probably not something we'd wanna ship with. Thanks!

**Comment by paulcpederson** [comment] 2020-04-30 15:57
@julio8a what does the input look like for the range? Also what interaction model should it use? As in, if I click "8" does the range _extend_ to 8 or am I selecting a new range beginning at 8.

As per the API for this, considering aligning this with [calcite-slider props](https://github.com/Esri/calcite-components/blob/master/src/components/calcite-slider/readme.md#properties). Basically add two props for range:

- `minValue`
- `maxValue`

We would then need to change the event detail for the emit on date select to:

```
e.detail = { min: Date, max: Date }
```

@macandcheese thoughts on this API?

Because of the rework I did a while back, the range feature should be a lot easier to add now...

**Comment by paulcpederson** [comment] 2020-04-30 16:26
@julio8a also might be worth moving a full spec + designs for range to a new issue as this one is getting a little wacky.

**Comment by macandcheese** [comment] 2020-04-30 16:37
@paulcpederson API looks good, consistency is 👑 - Agree with a new issue.

**Comment by julio8a** [comment] 2020-04-30 17:35
Will do new issue

**Comment by julio8a** [comment] 2020-05-01 00:28
Date is in master. I split range into another issue #541. Closing this one out. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2020-05-01 00:29 UTC
Labels: enhancement ✨, in progress 🚧, new component 🆕
