### ISSUE TITLE
Tall buttons in fullscreen modal

### ISSUE THREAD

**Issue by grover556** [Esri/calcite-components#6529] opened 2023-02-27 04:21 UTC
### Actual Behavior

When a modal is in fullscreen mode (forced or automatic), calcite-buttons in the content slot are stretched vertically and take up enormous amount of space. This behavior is on macOS (Safari, Chrome) and Windows 10 (Edge, Chrome).

<img width="458" alt="Tall buttons" src="https://user-images.githubusercontent.com/62857444/221471888-d76f22af-92f2-4625-86bd-652af6a24f0d.png">

### Expected Behavior

Buttons should remain the same size no matter the fullscreen attribute of the modal.

<img width="1050" alt="fullscreen" src="https://user-images.githubusercontent.com/62857444/221472195-3842b30f-1ed0-4ce0-9290-e9e4d68ab191.png">

### Reproduction Sample

~https://codepen.io/pen?template=RwgrjEx~
https://www.4dkfire.com/calcite_test.html

### Reproduction Steps
1. Visit https://www.4dkfire.com/calcite_test.html
2. Observe when the `modal` is in `fullscreen` the buttons behave abnormally
3. Edit the code to remove the `fullscreen` attribute, and observe the buttons behave as-expected outside of fullscreen mode

See modal code below:

<calcite-modal aria-labelledby="modal-splash-title" id="modal-splash" close-button-disabled escape-disabled outside-close-disabled fullscreen>
  <div slot="header" id="modal-splash-title">Splash screen title</div>
  <div slot="content">
    <img src="https://cdn4.buysellads.net/uu/1/122891/1660242968-T589N_Native-Ads_Bug_80x80.png" alt="Logo" style="max-width: 80vw;">
    <p>Some random text</p>
    <calcite-button appearance="outline-fill" href="https://www.google.com" target="_blank" ref="help">Usage Instructions</calcite-button>
    <calcite-button appearance="outline-fill" href="https://www.yahoo.com" target="_blank" ref="help">Quick Start Guide</calcite-button>
  </div>
  <calcite-button slot="primary" width="full" id="modal-splash-enter">Enter</calcite-button>
</calcite-modal>

### Reproduction Version

1.0.7

### macOS Ventura 13.2.1
Safari 16.3
Chrome Canary 112.0.5605.0

### Windows 10
Edge 102.0.1245.30
Chrome 110.0.5481.178

### Priority impact

p2 - want for current milestone

### Esri team

N/A

**Comment by macandcheese** [comment] 2023-02-27 17:54
Hi @grover556 - is it possible to update the Codepen in the issue with a reproduction sample of this behavior? 

I am unable to replicate this with buttons in the content slot and `fullscreen` enabled: https://codepen.io/mac_and_cheese/pen/xxaRBVR?editors=1000

**Comment by grover556** [comment] 2023-02-27 18:18
I was trying to put in the notes that it wasn't able to be reproduced in codepen, but its quite obvious when using a mobile device or the inspector in a browser. Anyways, a link to the codepen is here: https://codepen.io/grover556/pen/MWqbxQa

**Comment by geospatialem** [comment] 2023-04-18 18:09
@grover556 We're unable to repro with https://codepen.io/grover556/pen/MWqbxQa on iOS with either Chrome or Safari. The Codepen references the `latest` version (`1.2.0`), wondering if you are still experiencing the behavior, or if it's mitigated?

Without being able to repro the bug with an updated sample, we plan to close out this issue in the next month.

**Comment by grover556** [comment] 2023-04-18 19:17
@geospatialem, I mentioned in my reply to @macandcheese that the issue does not replicate in Codepen. This is still a thing even in 1.2.0, and I just put the exact same code on my public web site, https://www.4dkfire.com/calcite_test.html, which clearly reproduces the issue on Safari iOS 16.4.1, Safari 16.4 (18615.1.26.11.22) and on macOS Ventura 13.3 (22E252). The issue is also reproduced on Edge 112.0.1722.48 and Chrome 112.0.5615.121 on Windows 10 20H2 (Build 19042.1706). Please let me know if you are still unable to reproduce this.

**Comment by geospatialem** [comment] 2023-04-18 21:48
Thanks for the use case example!

Updated the context above to test internally. Able to reproduce outside of Codepen, where the issue is presented on both desktop and mobile devices. This does not appear to be a regression, but will work towards assignment in a future milestone soon.

Adding to the June milestone for research to determine a time estimate for consideration.

The `content` slot might be a good starting spot for the research activity.

**Comment by jcfranco** [comment] 2023-06-16 21:59
Found out the culprit: missing doctype.

This is required in all HTML pages to ensure consistent rendering:

> In [HTML](https://developer.mozilla.org/en-US/docs/Glossary/HTML), the doctype is the required "<!DOCTYPE html>" preamble found at the top of all documents.

☝️ https://developer.mozilla.org/en-US/docs/Glossary/Doctype

You can see how it affects layout with the following:

### Without doctype ❌
https://jsbin.com/ruveceb/edit?html,output

### With doctype ✅
https://jsbin.com/gibuhey/edit?html,output

The reason why it's not reproducible in Codepen is because the doctype is injected into the preview.

Closing as invalid based on the reasons stated above.

**Closed by jcfranco** 2023-06-16 21:59 UTC
Labels: bug, research, 2 - in development, p - medium, p2 - want for current milestone
