### ISSUE TITLE
Bug: Value List component multiple select not working

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1464] opened 2021-01-21 19:05 UTC
### Summary
Recently bumped the version of Calcite Components to next.76  to use the empty color picker option and saw this issue. Shift + click and ctrl + click seem to no longer be working with a value list. Still looking into it to make sure it is not on our end, please let me know if you can repro. Thanks!
### Actual Behavior
Click a value list item -> use shift + click or ctrl + click and select a different value list item -> it selects just the item clicked on even though they have the "selected" attribute
![image](https://user-images.githubusercontent.com/52869490/105516521-d690fb00-5c8a-11eb-80cc-b1f19a953cc5.png)
![image](https://user-images.githubusercontent.com/52869490/105516570-e4468080-5c8a-11eb-9786-03358b26c75e.png)

### Expected Behavior
Click a value list item -> use shift + click or ctrl + click and select a different value list item -> it selects multiple items, honoring the selected attribute.
### Reproduction Steps

https://codepen.io/eborgen/pen/GRjmmgE?editors=1000

### Relevant Info 

Update: I think this is just a visual bug with the selection, and the multi-select is working correctly otherwise. It seems like it is not allowing more than one selection in the value list even if we try to manually set multiple value list items as selected. 
![image](https://user-images.githubusercontent.com/52869490/105516335-9b8ec780-5c8a-11eb-9b6b-51f068732a36.png)

**Comment by jcfranco** [comment] 2021-01-26 01:19
Thanks for reporting this, @ethanbdev!

Did a `git bisect` and narrowed it down to this commit: 1e3f17c61c382c8a338ed298149e7a5caddffa59 @asangma Can you take a look at this? Basically, the styling for multiple selected value list items got lost. It looked like this before:

![value-list-toggling](https://user-images.githubusercontent.com/197440/105786163-5fc95b80-5f31-11eb-8d15-f3249473e0fe.gif)

**Comment by bstifle** [comment] 2021-01-27 21:54
Hi yalls, where does this stand? What is the priority for this?

**Comment by bstifle** [comment] 2021-01-27 22:12
@asangma do you have an eta?

**Comment by jcfranco** [comment] 2021-01-27 23:55
> Hi yalls, where does this stand? What is the priority for this?

Since this is a regression, I'd say high.

**Comment by subgan82** [comment] 2021-02-08 21:22
Hi @asangma 

Any update on this issue . Due to this regression we are unable to upgrade calcite components version in charts to use other calcite components fixes.

**Comment by asangma** [comment] 2021-02-10 16:36
I believe disabled this as it has accessibility issues. Instead the app would turn on `multiple`.

**Comment by asangma** [comment] 2021-02-10 16:39
Another way of putting that is that we don't currently have a way to shift-click using keyboard navigation.

**Comment by subgan82** [comment] 2021-02-10 16:40
The multiple selection is used with charts format UX workflows, would it be addressed as its a regression ?

**Comment by asangma** [comment] 2021-02-10 16:46
@jcfranco It looks like value-list-item is referring to a CSS color var that isn't in CalciteColor yet...? Looks like it might be pulling from the Tailwind config.

**Comment by ethanbdev** [comment] 2021-02-23 14:57
This looks good in the next builds now, since next.84 👍

**Comment by jcfranco** [comment] 2021-02-23 17:28
Thanks, @ethanbdev! Closing as verified based on ☝️

**Closed by jcfranco** 2021-02-23 17:28 UTC
Labels: 2 - in development, bug, p - high
