### ISSUE TITLE
Enhancement: Allow calcite-slider to set direction to rtl

### ISSUE THREAD

**Issue by dhatcher** [Esri/calcite-components#2169] opened 2021-05-19 14:21 UTC
### Description
We have several use-cases where we would like to use the slider to have users select a minimum value
### Acceptance Criteria 
The highlighted portion of the slider starts at the right-hand side.
#### Which Component
calcite-slider
#### Example Use Case
User needs to select a minimum value to be accepted in a filter.

**Comment by macandcheese** [comment] 2021-05-19 14:28
Related https://github.com/Esri/calcite-components/issues/720

**Comment by jcfranco** [comment] 2021-06-21 20:58
Closing as duplicate of #720.

**Closed by jcfranco** 2021-06-21 20:58 UTC
Labels: 0 - new, duplicate, enhancement
