### ISSUE TITLE
Bug: calcite-block-section horizontal alignment issues

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#2244] opened 2021-06-01 19:27 UTC
Using next.210 but can reproduce with beta.54.

I would expect the text and toggle button to be horizontally aligned.
![image](https://user-images.githubusercontent.com/44481292/120379125-271d0280-c2d4-11eb-9875-6b0efeb5b7dd.png)![image](https://user-images.githubusercontent.com/44481292/120378797-baa20380-c2d3-11eb-833c-ae7fa9d4a450.png)

With a multi-line text the toggle is in a weird place, not on top or centered.
![image](https://user-images.githubusercontent.com/44481292/120379018-02c12600-c2d4-11eb-9b57-d189ceaacc47.png)![image](https://user-images.githubusercontent.com/44481292/120379063-0fde1500-c2d4-11eb-932c-fdff9c0fa0fe.png)

### Reproduction Steps or Sample

1.

### Relevant Info

_Version_: `@esri/calcite-components@<version>`

- [ ] CDN
- [ ] NPM package

**Comment by macandcheese** [comment] 2021-06-01 21:47
Possible duplicate of https://github.com/Esri/calcite-components/issues/2232 ?

**Closed** 2021-06-01 21:49 UTC
Labels: 0 - new, bug, needs triage
