### ISSUE TITLE
Button hover Status and Dropdown Focus Status

### ISSUE THREAD

**Issue by ShangleiZ** [Esri/calcite-components#3605] opened 2021-12-01 00:06 UTC
### Should the red button hover status be red instead of blue? 
![image](https://user-images.githubusercontent.com/41970091/144147183-998cdd3d-e7c4-441e-a765-0350241aeac4.png)
![image](https://user-images.githubusercontent.com/41970091/144147199-2e8e3aa1-6786-4e15-8a73-7ce46c682347.png)

### When the dropdown opens, focus is set to the first item in the dropdown. 
![Screen Shot 2021-11-23 at 4 18 01 PM](https://user-images.githubusercontent.com/41970091/144147102-d9d7d74b-01e6-4e48-ba7a-d755d033cd6b.png)

**Comment by benelan** [comment] 2022-02-20 06:46
cc @macandcheese for design

**Comment by macandcheese** [comment] 2022-02-20 17:01
For the first screenshot, only the destructive delete button should be using that color - cancel is a secondary action and associating it with red / delete probably isn’t needed.

The focus color should be overridable with the brand css variable. 

The dropdown focus was added for accessibility - AFAIK that is intentional and working as intended.

**Comment by benelan** [comment] 2022-04-20 21:40
Closing based on ☝️

**Closed by benelan** 2022-04-20 21:40 UTC
Labels: question, design, 0 - new, needs triage
