### ISSUE TITLE
New Component: Skeleton Loader/UI

### ISSUE THREAD

**Issue by samanthahunter** [Esri/calcite-components#1090] opened 2020-10-07 19:00 UTC
#### User Stories
Unknown

### Acceptance Criteria 
- Shimmer effect using css gradients
- theme-able?

#### Out of Scope 
Unknown

**Comment by macandcheese** [comment] 2020-10-07 19:34
Closing as dupe of https://github.com/Esri/calcite-components/issues/1088

**Closed by macandcheese** 2020-10-07 19:34 UTC
Labels: new component 🆕
