### ISSUE TITLE
[ArcGIS Online] I18N-FCN-TH: Year of showed date in textbox is changed once selected date in calendar or clicked inside and then outside date textbox on create schedule report page.

### ISSUE THREAD

**Issue by jlias-devtester** [Esri/calcite-components#6498] opened 2023-02-21 17:51 UTC
### Actual Behavior

file://esri.com/dev/data/i18n/i18nPublic/screenshots/18896_date.gif

### Expected Behavior

The year shouldn't be changing

### Reproduction Sample

https://codepen.io/rpanichakit/pen/MWqywja?editors=1000

### Reproduction Steps

1. Prepare a clean TH Win10 64bit OS.
2. Login https://qaext.arcgis.com with a valid account.
3. Go to Organization->Status->Reports.
4. Click "Create report" and click "Report schedule".(key step)
5. Select date in calendar of Start date on Create report schedule dialog and observe.
6. Click date textbox again.
7. Click outside date textbox and observe.

### Reproduction Version

1.0.5

### Relevant Info

Configuration:
1. Build: AGOL 2023.r01 qaext site
2. OS: TH Win10 64bit
3. Browser: Edge Chromium(110.0.1587.50)
4. Found by date: 2/21/2023

### Regression?

Yes

### Impact

Low

### Esri team

ArcGIS Online

**Comment by geospatialem** [comment] 2023-04-18 17:47
Closing - duplicate of #6636.

**Closed by geospatialem** 2023-04-18 17:47 UTC
Labels: bug, 0 - new, needs triage, i18n-l10n, ArcGIS Online, airtable
