### ISSUE TITLE
<calcite-button> spacing is incorrect in certain cases

### ISSUE THREAD

**Issue by jcfranco** [Esri/calcite-components#434] opened 2020-04-02 22:41 UTC
Beta 21 introduced a regression with button layout.

<img width="712" alt="Screen Shot 2020-04-02 at 3 33 15 PM" src="https://user-images.githubusercontent.com/197440/78306095-66489b80-74f7-11ea-8750-2e3239e98618.png">

![4172fc00-7403-11ea-964a-fdb5446d1d2b-1](https://user-images.githubusercontent.com/197440/78306175-96903a00-74f7-11ea-96c8-5d3b0cfdc5f6.png)

I haven't been able to create an isolated test case, but the problem shows up in an app that uses [maquette](https://github.com/AFASSoftware/maquette) (VDOM library that works by creating elements programmatically and updating props) to generate its DOM. 

test case:
http://devext.arcgis.com/apps/mapviewer/index.html?urls=https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/2
Click on 'Styles' on the right tool bar, then click on '+ Field' and select POP2000 and click 'Add'. Then click on tile with orange dots and click on 'Custom' below slider.

**Comment by macandcheese** [comment] 2020-04-02 22:46
Thanks for submitting - initial thought is that it probably has to do with the change made to how we check for `hasText` in the PR for `calcite-split-button`:

https://github.com/Esri/calcite-components/pull/383

Without a test case to check against, we could probably just make that change as long as @kstinson14 is ok with it. @kstinson14 - was this to check to see if `hasText` should be true after text is programmatically added? It looks like we could probably just check in `componentDidUpdate` vs. the newly added MutationObserver.

**Comment by AdelheidF** [comment] 2020-04-02 22:50
From Kevin:

Yeah something changed with calcite-button, i was able to work around it by adding the "text" attribute to the calcite-button element, which then sets the hastext style

**Comment by macandcheese** [comment] 2020-04-03 19:59
Can you confirm this solved your issue?

**Comment by jcfranco** [comment] 2020-04-03 20:00
Until we get an isolated repro case. It'll be easier to test once we release.

**Comment by jcfranco** [comment] 2020-04-03 20:01
I'll follow-up on this today.

**Comment by jcfranco** [comment] 2020-04-03 20:06
Actually, @kevindoshier, could you follow up after trying beta 22?

**Comment by AdelheidF** [comment] 2020-04-03 20:15
Still reproducible with 5.7.0 and beta.22.

**Comment by macandcheese** [comment] 2020-04-03 21:12
:( 

Is there anyway to reproduce this in a codepen? I'm not sure what else could have caused the change, unless even just re-checking for 'hasText' in the update lifecycle method doesn't totally sync with how Maquette is injecting into DOM - I don't really have any experience with Maquette to know without being able to look at something.

**Comment by macandcheese** [comment] 2020-04-07 17:59
This seems like it's still not working in the reported scenario. Is there a reproduction codepen we can look at? If not, I guess the thing to do would be to revert any changes to `hasText` that were made in the `calcite-split-button` PR - that seemed to coincide here and switching from mutationObserver to lifecycle method check didn't solve for it. That internal prop has been here for awhile so if it just started giving you issues, the additional check is all I can think of that would have changed. @kstinson14 can you comment on that maybe?

**Comment by jcfranco** [comment] 2020-04-07 22:39
No codepen at the moment, but I can help look at this since I can repro on my side.

**Comment by macandcheese** [comment] 2020-04-07 22:40
Thanks. Apologies for ongoing issue here.

**Comment by jcfranco** [comment] 2020-04-07 22:49
No worries, this is a sneaky one. 😈

**Comment by jcfranco** [comment] 2020-04-08 01:07
I suspect this issue originally was caused by Stencil's new compiler (see https://github.com/Esri/calcite-app-components/issues/919#issuecomment-610218382 for more info).

When the issue occurs, the element's `textContent` gets set after initial lifecycle methods and when that happens it does not trigger a re-render, so `hasText` isn't recalculated. Restoring `MutationObserver` fixes this in my testing. 

@macandcheese @kstinson14 `<calcite-split-button>` had the fix all along. 😅 Sorry for the hassle! I'll submit a PR to revert #436.

**Comment by jcfranco** [comment] 2020-04-08 01:21
Installed. This will be available in `v1.0.0-beta.23`.

**Comment by macandcheese** [comment] 2020-04-08 01:51
Released in beta 23.

**Comment by AdelheidF** [comment] 2020-04-08 18:39
This change caused build issues. I'll close it once I verified this issue locally.

**Comment by AdelheidF** [comment] 2020-04-08 20:10
verified locally with beta.24

**Closed by AdelheidF** 2020-04-08 20:10 UTC
Labels: bug 🐞, component-button
