### ISSUE TITLE
Enhancement: Provide additional filter options for calcite-value-list

### ISSUE THREAD

**Issue by dhrumil83** [Esri/calcite-components#2209] opened 2021-05-25 23:17 UTC
### Description
We have the search filter, but also need the ability for additional filter that can be applied via slot="menu-actions"

### Acceptance Criteria 
Potential solution could be for client to provide filter methods for each action in the menu.

#### Which Component
calcite-value-list, calcite-value-list-item and calxite-filter

#### Example Use Case
![attr](https://user-images.githubusercontent.com/14285436/119579711-dd806500-bd73-11eb-87c2-d1c2d59bd41e.gif)

Another use case to consider: Multiple filters via the menu options.
<img width="211" alt="Screen Shot 2021-05-25 at 4 15 40 PM" src="https://user-images.githubusercontent.com/14285436/119580062-8fb82c80-bd74-11eb-9a8d-5149201298ac.png">

@jcfranco @AdelheidF @asangma

**Comment by AdelheidF** [comment] 2021-05-25 23:37
FYI, in the filter component we currently use the simple filter (just the input line) with a menu for sorting. Do we want to update this eventually to add the fancy filter too? If so, how would we make this work then?
I'd love to have the option to filter for number or string fields there. 

<img src=https://user-images.githubusercontent.com/44481292/119580728-d4909300-bd75-11eb-868c-d8982e12824d.png width=250/>

**Comment by driskull** [comment] 2021-06-03 17:52
duplicate of #2254

**Comment by AdelheidF** [comment] 2021-06-03 20:36
from @driskull 

I think we can either:

Expose an event for when a filter is done so a user can further filter items
Allow for a function to be called to filter more items.

**Comment by driskull** [comment] 2021-07-07 22:31
We need to discuss how we want to handle supporting this.

@AdelheidF @dhrumil83 
Currently, if you just listen for `calciteFilterChange` you can know to go through the items that aren't already filtered and filter them by setting their item to have the hidden attribute. That is what the built in search filter does.

Do we need to do anything else?

**Comment by dhrumil83** [comment] 2021-07-12 21:31
I think the issue is both filters working together.
e.g.
User filters by "Number" fields
Types something "Shape" in search
Currently I have both filters applied. Now if user clears the "Number" filter, client does not have a way to know what's in the search box.

**Comment by jcfranco** [comment] 2021-07-12 21:41
Maybe something like this could help?

```ts
interface HTMLCalcite(Value|Pick)ListElement {
  // @param item - item being filtered
  // @param filterText - current filter text
  // @param matched - original filter match
  // @returns true if filtering matches element (keep/list element)
  filter: (item: HTMLCalcite(Value|Pick)ListItemElement, filterText: string, matched: boolean): boolean; 
}
```

This would allow users to tap into the component's filtering and override filtered items if necessary (e.g., no search term, but user has custom number-type filter applied). I think this would be more flexible than the event approach since it allows hooking directly into the filtering step.

WDYT?

**Comment by dhrumil83** [comment] 2021-07-12 23:16
Ideal solution might be that the client provides the pick list all the needed information, and then the pick list takes care of everything (similar to how search filter currently works)

Suggestion above would help, but seems like client would have to track and maintain bunch of things, though it would provide more flexibility.

**Comment by jcfranco** [comment] 2021-07-12 23:31
> Ideal solution might be that the client provides the pick list all the needed information

Could you expand on this suggestion? Maybe an ideal-situation snippet?

**Comment by driskull** [comment] 2021-07-13 00:00
I don't think the pick-list can do the advanced filtering here. It doesn't know about the types of the items and stuff like that.

**Comment by dhrumil83** [comment] 2021-07-13 00:01
Expand the metadata prop, or perhaps have an additional filterMetadata prop.
https://github.com/Esri/calcite-components/tree/master/src/components/calcite-value-list-item

For text filter, currently client passes something like this:

```
metadata={{
     label: field.alias, // Shape Area
     fieldName: field.name // shape_area
}}

```

Could be expanded to:
```
metadata={{
     label: field.alias, // Shape Area
     fieldName: field.name // shape_area
     filterBy: [OptionA, OptionZ] // any filter option possible in the dropdown. e.g OptionA = "number" OptionZ = "popup"
}}
```
or maybe
```
metadataFilterBy={
     ["number", "popup"] 
}
```

Now when user filters by text, or via the dropdown(number and/or popup), or any combination of these 3 pick list has enough information to handle the results.

**Comment by jcfranco** [comment] 2021-07-13 00:54
I second what @driskull said. The lists don't have enough info for non-text filtering. `metadata` is used as additional data to find text matches.

Not sure if this helps, but here's an example of how my proposal could work for your use case:

```ts
let customFilters;

someList.filter = (item, filterText, matched) => {
  // assumes custom filter checks item's value and metadata for matching
  if (customFilters?.some(filter => filter(item))) {
    return true;
  }

  // fallback on default filtering 
  //we could also pass the default filter function to call here and avoid unnecessary filtering
  return matched;
}

// ...

dropdown.on("calciteDropdownSelect", (event) => {
  customFilters = getFiltersFromDropdown(event.currentTarget);
  someList.applyFilter();
});
```

Admittedly, this doesn't address how active filter options are displayed in the UI, so we'll also need someone from the design team to chime in on the filter options UI/UX. +@Esri/calcite-design-representatives

**Comment by dhrumil83** [comment] 2021-07-13 17:11
This works as well.
Pick list will still take care of the text filter, and the client will handle the filter that comes via the dropdown.

**Comment by jcfranco** [comment] 2021-07-16 18:18
@asangma Could you chime on this? I think we've got a solution worked out for the functionality, but it's not clear what UI/UX changes are needed for the lists.

**Comment by driskull** [comment] 2021-07-16 18:23
Should this use a `calcite-action-menu` or `calcite-dropdown`?

**Comment by AdelheidF** [comment] 2021-07-19 16:37
Once implemented, could you add an example like the one above to the doc so it's clear how to use it? Thanks!

**Comment by bstifle** [comment] 2021-07-19 16:52
will need to consider this for the new filter input design as well:
#1549

**Comment by asangma** [comment] 2021-07-19 17:35
I think we should explore making the chips part of the Filter and representing text searches as chips.
I will make a mockup to demonstrate more clearly.
But the intention is to help clarify that that typing "shape" into the search input filters based on title/description. Other custom filters, e.g. from the fancy filter, could pushed to the stack of chips.

This would be a more UI-y version of what Github does.
`is:open is:issue assignee:asangma milestone:"Sprint 7/19 – 7/30" `

And also akin to my fave YT Studio
![image](https://user-images.githubusercontent.com/12503298/126202360-17128791-d760-45e9-9e43-8b86ba780d34.png)

**Comment by asangma** [comment] 2021-07-20 15:05
More thinking: the search input converted to chip would be at odds with our debounced filtering. Maybe it would be a separate mode.

**Comment by bstifle** [comment] 2021-07-20 16:08
yeahhh. i think the search thing should just be stock calcite-input  (small or med)

**Comment by driskull** [comment] 2021-07-20 16:09
The combobox could be used for filtering. Why do we need a filter component?

**Comment by asangma** [comment] 2021-07-20 18:04
@driskull I was thinking combo-box could be nice for that.

**Comment by driskull** [comment] 2021-07-20 18:10
Maybe we don't need a filter component if the combobox could handle the use case properly.

**Comment by asangma** [comment] 2021-07-20 18:13
Hmmm...c'est possible.

**Comment by brittneyzwolfer** [comment] 2023-02-22 17:38
@jcfranco can this be closed?

**Comment by geospatialem** [comment] 2023-03-03 21:44
Closing with the deprecation of the `value-list` component.

**Closed by geospatialem** 2023-03-03 21:44 UTC
Labels: enhancement, help wanted, design, 0 - new, need more info, airtable
