### ISSUE TITLE
Bug: Color input does not use calcite-color-picker on Firefox

### ISSUE THREAD

**Issue by benelan** [Esri/calcite-components#2941] opened 2021-08-28 00:00 UTC
### Actual Behavior
 Firefox does not use our color picker when selecting a color for an input with type="color".
![image](https://user-images.githubusercontent.com/10986395/131197547-e87f8d06-9789-45eb-b3d1-596c2fb35b4f.png)

### Expected Behavior
Use calcite-color-picker 

### Reproduction Steps or Sample
https://codepen.io/benesri/pen/qBjOdbG

### Relevant Info
Firefox 91.0.2 (64-bit)
Windows 10

_Version_: `@esri/calcite-components/1.0.0-beta.62`

- [x] CDN
- [ ] NPM package

### Related Issue
- #1934
- #2940

**Comment by mjuniper** [comment] 2021-11-19 15:53
I see the same thing on chrome and I notice that it just renders an `<input type="color" />` so the browser handles the colorpicker aspect. That makes me think that this is actually the intended behavior?

**Comment by jcfranco** [comment] 2022-02-18 00:23
> That makes me think that this is actually the intended behavior?

This is correct. 

The plan moving forward would be to deprecate `type=color` and introduce a color-specific input. Looks like it'd be https://github.com/Esri/calcite-components/issues/1616 or https://github.com/Esri/calcite-components/issues/1934. @benelan @macandcheese Let's sync up next week to decide which one. FWIW, Map Viewer has a custom version of the former.

Closing based on ☝️.

**Closed by jcfranco** 2022-02-18 00:23 UTC
Labels: bug, browser-firefox, 0 - new
