### ISSUE TITLE
Combobox: change dropdown focus/open behavior

### ISSUE THREAD

**Issue by ptmdmusique** [Esri/calcite-components#2514] opened 2021-07-12 21:36 UTC
### Question

Currently the combobox element will open the dropdown whenever it's focused. I'm wondering if we can make it more like a `select` tag where it will only open the dropdown on clicked or on some certain keys pressed instead

cc @paulcpederson

**Comment by paulcpederson** [comment] 2021-07-12 21:38
@bstifle this came up recently while looking into some accessibility issues. Interested in your thoughts.

**Comment by paulcpederson** [comment] 2021-08-31 16:44
@jcfranco if you get a second, we should figure out how to prioritize this one

**Comment by jcfranco** [comment] 2021-08-31 16:52
@paulcpederson Can you share info on the a11y issues and provide an effort estimate on this one? Seems low effort to me.

**Comment by paulcpederson** [comment] 2021-08-31 22:57
The [spec for combobox](https://www.w3.org/TR/wai-aria-practices-1.1/#combobox) sort of allows for multiple interpretations:

> The popup is hidden by default, and the conditions that trigger its display are specific to each implementation. Some possible popup display conditions include:
> - It is displayed only if a certain number of characters are typed in the textbox and those characters match some portion of one of the suggested values.
> - It is displayed as soon as the textbox is focused, even if the textbox is empty.
> - It is displayed when the Down Arrow key is pressed or the show button is activated, possibly with a dependency on the content of the textbox.
> - It is displayed if the value of the textbox is altered in a way that creates one or more partial matches to a suggested value.

Currently we use `It is displayed as soon as the textbox is focused` but for the single select, because it's more like a select menu, I think we'd like to make it comparable to a select menu, meaning moving to `It is displayed when the Down Arrow key is pressed or the show button is activated`. Obviously typing in characters will work as well.

I'm not entirely sure what effort would be required, but I think it should be relatively straightforward to move the opening behavior behind the down arrow key and off the input focus event. However the combobox is fairly complex so ensuring that this doesn't cause regressions and making sure tests pass successfully may add time.

**Comment by geospatialem** [comment] 2022-04-04 21:16
@paulcpederson noticed in the list you mentioned a list of items to implement with this issue. While running through a verification it looks like we were able to fulfill one of the requirements. 

Can you verify we're fulfilling the expected behavior, as there is no current functionality for characters entered by the user. _Note that there is functionality for arrow keys (and home/end), spacebar, and on click._

![screenshot of combobox with focus/open behavior](https://user-images.githubusercontent.com/5023024/161626424-4627f69b-bc4f-44f1-9e29-95f24c69133f.png)

Also, a [code pen](https://codepen.io/geospatialem/pen/zYppmdb) if its helpful for testing.

- [ ]  ~It is displayed only if a certain number of characters are typed in the textbox and those characters match some portion of one of the suggested values.~
- [ ] ~It is displayed as soon as the textbox is focused, even if the textbox is empty.~
- [X] **It is displayed when the Down Arrow key is pressed or the show button is activated, possibly with a dependency on the content of the textbox.**
- [ ] ~It is displayed if the value of the textbox is altered in a way that creates one or more partial matches to a suggested value.~

**Comment by paulcpederson** [comment] 2022-04-04 21:22
Yeah looks good, IMO

**Closed** 2022-04-04 21:23 UTC
Labels: enhancement, 4 - verified
