### ISSUE TITLE
calcite-time-picker/calcite-input-time-picker: wrong order of time in RTL

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#3883] opened 2022-01-08 00:48 UTC
According to Olga the current format of ss:mm:hh is not correct for Arabic or Hebrew. The numbers should not switch order between LTR and RTL. 

value="18:46"
![image](https://user-images.githubusercontent.com/44481292/148110669-d34924f6-bf50-4e2c-9c8b-01fd1ebf6b45.png)

![image](https://user-images.githubusercontent.com/44481292/149235717-29449841-0dce-4db8-8fac-e97640323e57.png)

https://codepen.io/afreitag/pen/QWqrRGg

### Relevant Info

_Reproducible version_: `@esri/calcite-components@1.0.0-beta.73`

- [ ] CDN
- [ ] NPM package

**Comment by AdelheidF** [comment] 2022-01-27 00:18
looks good to me now

**Comment by AdelheidF** [comment] 2022-01-27 00:20
Actually, I think the unit needs to stay in front of the number.

This is wrong 
![image](https://user-images.githubusercontent.com/44481292/151268708-6567776f-cd94-4540-8731-b1c11acf5905.png)

**Comment by benelan** [comment] 2022-01-27 00:53
> Actually, I think the am/pm needs to stay in front of the numbers.

Assigning back to @anveshmekala to look into ^

**Comment by AdelheidF** [comment] 2022-01-27 00:55
Those 2 might be related, not sure. https://github.com/Esri/calcite-components/issues/1475#issuecomment-1022739244

**Comment by anveshmekala** [comment] 2022-01-27 17:39
@AdelheidF  Setting meridiem  in front of the time format is applicable for just `rtl` direction ?

cc: @asangma

**Comment by AdelheidF** [comment] 2022-01-27 17:42
Seems to be also the case for ko and zh, see here: https://github.com/Esri/calcite-components/issues/1475#issuecomment-1023475022

Isn't there a lookup you could use?

I don't know those specifics....

**Comment by jcfranco** [comment] 2022-01-27 21:56
@anveshmekala brought this up, but is this a duplicate of #1475? They both seem related to the ordering of time parts per locale.

**Comment by AdelheidF** [comment] 2022-01-27 22:00
> They both seem related to the ordering of time parts per locale.

The original issues addressed separate things, but what's left is kind of similar now. 

I opened this issue here because of you guys not commenting on this: https://github.com/Esri/calcite-components/issues/1475#issuecomment-1005093188

**Comment by AdelheidF** [comment] 2022-01-27 23:33
To recap:

What's left here is that in RTL languages AR and HE the am/pm is on the wrong side in `calcite-time-picker`. `calcite-input-time-picker` is correct.

https://codepen.io/afreitag/pen/MWOYOrp

**Comment by AdelheidF** [comment] 2022-02-01 19:47
Looks like this issue is now also used for:

In LTR languages ZH and KO the am/pm is on the wrong side

**Comment by babakbolour** [comment] 2022-02-01 20:55
it would be great if we could put the am/pm on the correct side for KO, ZH, HE, AR. case in point is the 'nationalization' we do for GeoScene/China and we want the UI look appropriate for the culture. thank you.

**Comment by AdelheidF** [comment] 2022-02-17 00:20
looks good with next

**Closed** 2022-02-22 18:13 UTC
Labels: bug, p - high, 3 - installed, milestone adjusted
