### ISSUE TITLE
Bug: `calcite-button` with handlebar `href` not linking

### ISSUE THREAD

**Issue by nwhittaker** [Esri/calcite-components#2152] opened 2021-05-14 16:48 UTC
### Actual Behavior
Given a `<calcite-button>` element in an Ember template with an `href` attribute set to a handlebar expression, clicking the button does nothing.

### Expected Behavior
Clicking the button should load the link specified by the handlebar expression.

### Reproduction Steps or Sample
```hbs
{{! Link works }}
<calcite-button href="https://www.esri.com">button</calcite-button>

{{! Link does not work }}
<calcite-button href={{href}}>button</calcite-button>
```

See https://jsbin.com/dekozigeza/1/edit?html,js,output for a working test case with Ember.

### Relevant Info
_Version_: `@esri/calcite-components@next`

**Comment by benelan** [comment] 2021-10-08 21:54
closing as a duplicate of #3153 (button uses link)

**Closed by benelan** 2021-10-08 21:54 UTC
Labels: bug, framework-ember, 0 - new, needs triage

**Comment by nwhittaker** [comment] 2021-10-09 00:32
@benelan, can you please verify the duplicated issue? The one you linked in doesn't look related.
