### ISSUE TITLE
calcite-list - changing filter-text property/attribute does not filter the list items

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/calcite-components#6633] opened 2023-03-22 21:06 UTC
### Actual Behavior

The list of calcite-list-items is not updated/changed/filtered when changing the filter-text property/attribute of the calcite-list via code.

### Expected Behavior

I would expect the list of calcite-list-items to be updated/changed/filtered when changing the filter-text property/attribute of the calcite-list via code.

### Reproduction Sample

https://codepen.io/john-grayson/pen/ZEMMqdX

### Reproduction Steps

1. click on the 'FILTER BANANAS' button
2. see how the list is not filtered

### Reproduction Version

1.07

### Priority impact

p4 - not time sensitive

### Esri team

N/A

**Comment by jgrayson-apl** [comment] 2023-03-30 19:19
Q: Any current workarounds to this issue?  

I just need to change the filter via code... we should be able to do this somehow, no?

**Comment by jcfranco** [comment] 2023-04-17 07:02
@jgrayson-apl Not ideal by any means, but could you give this a try? https://codepen.io/jcfranco/pen/PoyzwKx?editors=0010

**Comment by jgrayson-apl** [comment] 2023-04-17 15:47
@jcfranco yes kinda hacky but ok for a workaround, I was able to adapt the concepts to a couple of apps.  Thank you very much.

**Comment by driskull** [comment] 2023-05-02 00:39
I think this needs to be fixed in the filter component.

The filter component doesn't emit an event when the filterText changes programmatically. The issue is that when filterText is changed programmatically the filteredItems property changes after a debounce so there's no way to know when to grab that new data. The filter would either need to emit or have another event for when the filteredItems changes.

**Comment by driskull** [comment] 2023-05-22 20:20
@jcfranco what are your thoughts regarding how filter can let other components know when the filterText changes?

**Comment by driskull** [comment] 2023-06-02 21:49
@jcfranco I'd like to get this going. What do you think about...

- Making a public filter method that would resolve once debouncing is complete.
- Changing the `calciteFilterChange` event to emit on both programatic and user changes.
- Removing debouncing from the filter and making other components handle debouncing

**Comment by jgrayson-apl** [comment] 2023-06-02 22:13
Since you guys are thinking about this issue...  I would like to have the ability to set/override a 'filter' function/callback (like we can do with simple arrays) where I could perform my own more complex checks to determine if an item passes the test.  There are many times when entering text in the input is not what we need.  Sometimes we have multiple criteria to consider or even a simple discrete set of options that we want to filter on.  Probably beyond what is going on here, but thought I'd mention anyways.

**Comment by jcfranco** [comment] 2023-06-03 00:43
@driskull I think we could proceed with your first suggestion and introduce a `filter(text)` method that updates the filter text and also resolves when done. Would this still necessitate the other suggestions? I'd like to avoid them if possible.

@jgrayson-apl https://github.com/Esri/calcite-components/issues/3454 might cover your request.

**Comment by geospatialem** [comment] 2023-06-29 22:28
Verified in `1.5.0-next.8`.

![verify-list-filter](https://github.com/Esri/calcite-components/assets/5023024/fac0b205-d2b6-444f-b556-39ad5396eaa3)

**Closed by geospatialem** 2023-06-29 22:28 UTC
Labels: bug, refactor, research, p - high, 4 - verified, has workaround, estimate - 5, p4 - not time sensitive
