### ISSUE TITLE
Bug: calcite-action-bar - overflowActionsDisabled issues

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#1937] opened 2021-04-08 22:14 UTC
### Summary

When I use `overflowActionsDisabled`,  overflow still seems to be enabled on the initial load, and the scrollBar is still disabled,  but once its loaded and I resize the window the overflow stays, so it seems the flag is being honored only after the initial loading of the component

### Expected Behavior

I think when its disabled the scrollBar should be visible, and the initial load should honor the flag

### Reproduction Steps

1.

**Comment by driskull** [comment] 2021-04-12 05:34
Thanks @kevindoshier. I have a PR to fix this. Then you should be able to turn it off if you don't want to use it for this release.

This will give us time to perfect the height calculating logic.

cc @AdelheidF

**Comment by ethanbdev** [comment] 2021-04-12 14:45
Unless I missed something, I grabbed the `next` build and I am still seeting #1938 - setting the attribute in Stencil, the css for `overflow: y` does not get added

**Comment by kevindoshier** [comment] 2021-04-12 15:00
I see the scrollbar if I set the attribute after its created

`element.setAttribute("overflow-actions-disabled", "");`

![image](https://user-images.githubusercontent.com/11093161/114416096-2fbf4b00-9b65-11eb-9d5f-01f8452ff627.png)

**Comment by ethanbdev** [comment] 2021-04-12 15:31
> I see the scrollbar if I set the attribute after its created
> 
> `element.setAttribute("overflow-actions-disabled", "");`
> 
> ![image](https://user-images.githubusercontent.com/11093161/114416096-2fbf4b00-9b65-11eb-9d5f-01f8452ff627.png)

Yes, this works for me too

**Comment by nel11211** [comment] 2022-06-15 22:51
> I see the scrollbar if I set the attribute after its created
> 
> `element.setAttribute("overflow-actions-disabled", "");`

We have been using this workaround for a while on Charts. But we are still seeing an issue in cases where the action bar is loaded into a small viewport, see the following issue on Charts https://devtopia.esri.com/WebGIS/arcgis-charts/issues/4385. Using `<calcite-action-bar overflowActionsDisabled={false}>` fixes the issue above, but then the scroll bar does not show up.

**Comment by driskull** [comment] 2022-06-15 23:14
@nel11211 the default for `overflowActionsDisabled` is `false` so I'm not understanding why you would do `<calcite-action-bar overflowActionsDisabled={false}>`

The issue seems to be that some of the actions are set with `text-enabled` by default.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/1231455/173957506-3d8ec12b-39f4-4d42-aa49-37f72e075d20.png">

If you remove that property and let the action-bar handle it it should be good. Let me know.

**Comment by nel11211** [comment] 2022-06-15 23:15
> @nel11211 the default for `overflowActionsDisabled` is `false` so I'm not understanding why you would do `<calcite-action-bar overflowActionsDisabled={false}>`
> 
> The issue seems to be that some of the actions are set with `text-enabled` by default.
> 
> <img alt="image" width="569" src="https://user-images.githubusercontent.com/1231455/173957506-3d8ec12b-39f4-4d42-aa49-37f72e075d20.png">
> 
> If you remove that property and let the action-bar handle it it should be good. Let me know.

My bad that was typo, I am setting it `true`.

**Comment by nel11211** [comment] 2022-06-15 23:18
> The issue seems to be that some of the actions are set with `text-enabled` by default.
>
> If you remove that property and let the action-bar handle it it should be good. Let me know.

None of the actions are being set with `textEnabled={true}`, I even tried manually changing them to `textEnabled={false}` but they are still being enabled after render from some other source. My suspicion is that happens upon calling `this.calciteActionBar.setAttribute("overflow-actions-disabled", "");`, because removing that line fixes it.

**Comment by nel11211** [comment] 2022-06-15 23:26
More to the point for this issue, setting `<calcite-action-bar overflowActionsDisabled={true}>` is disabling the scrollbar. Is that expected behavior?

**Comment by driskull** [comment] 2022-06-15 23:33
Sounds like a framework issue there. Can you verify that the attribute works? `<calcite-action-bar overflow-actions-disabled>`.

Are you sure the scrollbar just isn't there because the height is smaller than a scrollbar would be required?

**Comment by nel11211** [comment] 2022-06-15 23:41
> Sounds like a framework issue there. Can you verify that the attribute works? `<calcite-action-bar overflow-actions-disabled>`.

It looks like @ethanbdev already tried that, see https://github.com/Esri/calcite-components/issues/1938.

> Are you sure the scrollbar just isn't there because the height is smaller than a scrollbar would be required?

Yes, the content of the action bar well exceeds the viewport.

**Comment by driskull** [comment] 2022-06-15 23:48
I don't think #1938 is related. In that issue it was being set incorrectly: `<calcite-action-bar overflowActionsDisabled></calcite-action-bar>`.

The correct way to set it via JSX is `<calcite-action-bar overflowActionsDisabled={true}>` and when inspected in HTML, it should look like `<calcite-action-bar overflow-actions-disabled>`.

If it doesn't look like that, then it's an issue with JSX translating it to the correct attribute.

You can try just setting the attribute instead of the property by using `<calcite-action-bar overflow-actions-disabled>`

**Comment by nel11211** [comment] 2022-06-16 00:33
> The correct way to set it via JSX is `<calcite-action-bar overflowActionsDisabled={true}>` and when inspected in HTML, it should look like `<calcite-action-bar overflow-actions-disabled>`.
> 
> If it doesn't look like that, then it's an issue with JSX translating it to the correct attribute.

That's what I've been using, so there might be an issue translating the JSX then.

> You can try just setting the attribute instead of the property by using `<calcite-action-bar overflow-actions-disabled>`

Yup this fixed it. 👍

**Comment by nel11211** [comment] 2022-06-16 16:17
In that case we can re-close this, unless you want to use it to track the JSX issue.

**Comment by driskull** [comment] 2022-06-16 16:21
I think we can close

**Closed by driskull** 2022-06-16 16:21 UTC
Labels: bug, 3 - installed
