### ISSUE TITLE
Action-bar - Arabic text is is cut off in Firefox

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#3955] opened 2022-01-19 00:47 UTC
### Actual Behavior

Arabic text is cut off in Map Viewer in Firefox only. 
![image](https://user-images.githubusercontent.com/50747646/150042299-4a200e0d-88a8-43b9-b773-cbf87eaaf900.png)

### Expected Behavior

Text should not be cut off:
![image](https://user-images.githubusercontent.com/50747646/150042364-2a914776-c2cb-445e-9436-8d96439ce09e.png)

### Reproduction Sample

https://www.arcgis.com/apps/mapviewer/index.html?locale=ar

Codepen sample: https://codepen.io/mtb-alan/pen/LYzvMgg

1. If you don't see the descenders clipping, inspect the Action and look for the `.button` element.
2. Set `font-family` to `revert`

### Reproduction Steps

1. Open https://www.arcgis.com/apps/mapviewer/index.html?locale=ar in Firefox and expand the toolbars to see the text. 

### Reproduction Version

@esri/calcite-components@1.0.0-VERSION

### Relevant Info

Regression? Last working version: `@esri/calcite-components@1.0.0-VERSION`

### Source

- [ ] CDN
- [ ] NPM package

cc @asangma @driskull

**Comment by asangma** [comment] 2022-01-19 17:01
@benelan I can take this on.
I added a Codepen and some repro steps.

**Comment by asangma** [comment] 2022-01-21 18:37
@benelan I made a PR but then realized this issue doesn't have a milestone.

**Comment by benelan** [comment] 2022-01-21 18:38
No worries, it happens.

**Comment by jcfranco** [comment] 2022-03-21 19:21
@asangma Is this still valid? I didn't see a difference in FF when comparing the codepen between its version (beta.65) and the latest.

**Comment by zaramatheson** [comment] 2022-03-30 23:06
@jcfranco @asangma This is still an issue in MV using beta.77

**Comment by AdelheidF** [comment] 2022-03-30 23:11
beta.77 was released Feb 14, 2022. This PR got merged Jan 28. So I assume this is still an issue with the latest beta.80.

**Comment by AdelheidF** [comment] 2022-04-21 18:34
still an issue with beta.81, @zara checked

**Comment by jcfranco** [comment] 2022-04-27 02:05
@asangma Apologies if this is redundant info, but it looks like the clipping is caused by the text-truncation styles applied to the action's text container: https://codepen.io/jcfranco/pen/OJzeYWa. I stumbled upon [Capsize](https://seek-oss.github.io/capsize/), which uses font metadata to generate styles for better text layout. Their FAQ also has some info on [truncation](https://seek-oss.github.io/capsize/#:~:text=What%20is%20the%20recommended%20way%20to%20handle%20text%20overflow/truncation%3F) and [diacritic/accent marks for non-latin alphabets](https://seek-oss.github.io/capsize/#:~:text=What%20does%20this%20mean%20for%20diacritic%20and%20accent%20marks%20in%20non%2DLatin%20alphabets%3F). Something worth looking into.

**Comment by paulcpederson** [comment] 2022-04-27 16:08
Per another issue I was added to I think the map viewer is moving to the [v2 calcite fonts implementation](https://github.com/ArcGIS/calcite-fonts/releases/tag/v2.0.0). This uses Avenir Next World for Arabic, greatly improving the rendering. This should help with this specific case where it's cutting off the text.

I will say that this line-height is pretty tight, though. It may make sense to bump it regardless (could lower y-padding to compensate). 

Using something like capsize is going to be hard. We have lots of languages using system defaults (all different per language), then some faces still using non-avenir web fonts, plus older calcite-fonts and calcite web implementations which also use different font files with different metrics. There is no way to know for the system fonts which font a user has on their machine. This is a problem capsize has acknowledged https://github.com/seek-oss/capsize/issues/23#issuecomment-673743474

**Comment by jcfranco** [comment] 2022-04-27 16:29
Awesome. It looks like v2 fonts will work w/o us doing anything. Is this correct? 

I understand the complexity of covering all cases w/ Capsize. I brought it up to see if it would at least help cover our bases with the [calcite font-families](https://github.com/Esri/calcite-components/blob/ea4ba957a15a631b72e517be0f7eac364602b714/src/assets/styles/_type.scss#L2-L3).

**Comment by paulcpederson** [comment] 2022-04-27 16:55
> Awesome. It looks like v2 fonts will work w/o us doing anything. Is this correct?

Correct, basically avenir next world was redrawn with new metrics and characters for more languages, so the arabic descenders/joiners fit inside the glyph better.

**Comment by jcfranco** [comment] 2022-05-24 20:58
> I will say that this line-height is pretty tight, though. It may make sense to bump it regardless (could lower y-padding to compensate).

@asangma Can we tweak the line-height as suggested above and rely on apps using Avenir Next for the rest?

**Comment by benelan** [comment] 2022-08-04 22:30
verified an increased `line-height` on next

**Closed by benelan** 2022-08-04 22:30 UTC
Labels: bug, 3 - installed, i18n-l10n, milestone adjusted
