### ISSUE TITLE
Enhancement: Can Am/AM be a binary option in Timepicker

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#933] opened 2020-09-01 23:37 UTC
Either with a dropdown or some other method. It is not always clear that the value is expected to be AM or PM (could be intrepeted as  seconds when blank).  and you have to type AM or PM in caps for it to take 
![image](https://user-images.githubusercontent.com/50747646/91916190-5e8d4e80-ec71-11ea-9eb5-28097cc4ff44.png)

@jcfranco

**Comment by macandcheese** [comment] 2020-09-01 23:45
Hey - having trouble replicating the "needs caps" portion of this - seems like it works for me with upper or lower case "a" or "p" to complete it (or arrow up / down)..

In any case, that looks like it is just a `calcite-input` of type `time` - maybe it's time for someone to finally take a stab at https://github.com/Esri/calcite-components/issues/407 (which would have a more explicit AM / PM entry method as you mention) 🤔

**Comment by zaramatheson** [comment] 2020-09-01 23:48
@macandcheese ah sorry you are right, it works with or without caps. Either way, would be nice to have it a bit more obvious that AM or PM is expected here.

**Comment by macandcheese** [comment] 2020-09-01 23:51
@zaramatheson agreed - that'd be a nice enhancement, we had planned on a separate `calcite-time` component as a sibling to `calcite-date`, we just haven't had the time (ha...). Could you see if the designs here would work for you? https://github.com/Esri/calcite-components/issues/407#issuecomment-622119064

**Comment by zaramatheson** [comment] 2020-09-01 23:58
@macandcheese I think that those designs would work, they would also help with this issue: https://github.com/Esri/calcite-components/issues/932

**Comment by jcfranco** [comment] 2021-06-21 21:03
@zaramatheson The new time picker component was installed last week. @eriklharper Do you think this is still valid with the component?

**Comment by eriklharper** [comment] 2021-06-22 17:28
I don't think this is valid because this is relying on using `<calcite-input type="time">` which is a) completely separate component and b) the new `input-time-picker` component doesn't use the `type="time"` native equivalent, so unless there are bugs or unintended behavior with the current way the input displays the meridiem, then this is safe to close IMO.

As an aside, the confusion around whether the empty area to the right of the hour:minute portion of the input is for seconds or meridiem should be cleared up by the lack of a `:` in between them.  This is native behavior, at least in Chromium and some other modern browsers, and it's not even consistent nor standardized behavior anyway.  When you use `step="1"` on a native time input, you'll see the seconds portion separated from minutes with a colon as expected.

**Comment by benelan** [comment] 2021-08-31 17:09
Closing this issue as no longer valid.

**Closed by benelan** 2021-08-31 17:09 UTC
Labels: enhancement
