### ISSUE TITLE
CalciteButton remain disabled even when `disabled={false}` (React)

### ISSUE THREAD

**Issue by kwokhou** [Esri/calcite-components#7226] opened 2023-06-27 00:04 UTC
### Actual Behavior

The `<CalciteButton>` is disabled whenever the attribute `disabled` is added. Even when the value is set to false.

```
<CalciteButton disabled={false}>Button</CalciteButton>
```

The property definition says that:
_When true, interaction is prevented and the component is displayed with lower opacity._

### Expected Behavior

Button should not be disabled when `disabled` attribute is not `true`

### Reproduction Sample

https://codesandbox.io/s/black-snow-cpn2wc?file=/src/App.js

### Reproduction Steps

1. In a React app, add a <CalciteButton>
2. Set the attribute `disabled` to false like this `<CalciteButton disabled={false}>Button</CalciteButton>`
3. See the result

### Reproduction Version

1.4.2

### Relevant Info

Chrome, Firefox

### Priority impact

p1 - need for current milestone

### Impact

This is a very serious bug. Something so fundamental should not be broken. Almost all buttons on forms will use this attribute to control form submission.

### Esri team

N/A

**Comment by geospatialem** [comment] 2023-06-27 02:27
Hello @kwokhou - this is the expected behavior with React due to compatibility issues with web components, where boolean attributes should either:
- Not be set, or
- Use `undefined` instead of `false` values

Check out more information on [Calcite's React Gotchas](https://developers.arcgis.com/calcite-design-system/resources/frameworks/#boolean-attributes) for additional details.

For instance:
```js
function App() {
  let [disabledVal, disabledState] = useState(undefined);

  return (
    <>
      <CalciteButton
        id="my-button"
        onClick={() => disabledState(true)}
        disabled={disabledVal}
      >
        Button state
      </CalciteButton>
    </>
  );
}
```

Here's a [full example](https://codesandbox.io/s/wild-hooks-ctgyyz) for additional context.

Closing this issue out as not planned with the above workflow provided.

**Closed by geospatialem** 2023-06-27 02:27 UTC
Labels: bug, 0 - new, needs triage, p1 - need for current milestone
