### ISSUE TITLE
Bug: calcite-input configured with precision > 0 doesn't format values correctly

### ISSUE THREAD

**Issue by jgrayson-apl** [Esri/calcite-components#1865] opened 2021-03-30 17:08 UTC
### Summary
calcite-input configured with precision > 0 doesn't format values correctly

### Actual Behavior
![image](https://user-images.githubusercontent.com/5324720/113028059-b163b180-913f-11eb-8578-9742293def47.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/5324720/113028134-c7717200-913f-11eb-9bff-ae992529cbb5.png)

### Reproduction Steps

` <calcite-input
        type="number"
        status="idle"
        alignment="start"
        number-button-type="horizontal"
        min="0.1"
        max="5"
        step="0.1"
        prefix-text=""
        suffix-text=""
        value="1.0"
        placeholder="Placeholder text"
        class="sc-calcite-input-h sc-calcite-input-s"
        dir="ltr"
        scale="m"
        calcite-hydrated=""
      >`

**Comment by macandcheese** [comment] 2021-03-30 17:11
Hi @jgrayson-apl , could you check out master / next and see if this fix by @paulcpederson took care of this https://github.com/Esri/calcite-components/pull/1830?

**Comment by benelan** [comment] 2021-11-15 20:32
closing as a duplicate of #3443

**Closed by benelan** 2021-11-15 20:32 UTC
Labels: bug, 0 - new
