### ISSUE TITLE
Tooling: "@types/sortablejs" is a dependency in latest next build

### ISSUE THREAD

**Issue by ethanbdev** [Esri/calcite-components#1818] opened 2021-03-22 16:47 UTC
## Summary 
Using calcite components inside another stencil project, the stencil build fails because its needs the "@types/sortablejs" package. It happens if using the type `HTMLCalciteValueListElement`
![image](https://user-images.githubusercontent.com/52869490/112026428-70dab700-8af3-11eb-930e-d319dacfbf0a.png)

Types are coming correctly from the `components.d.ts` file
![image](https://user-images.githubusercontent.com/52869490/112026533-894ad180-8af3-11eb-94f5-453ecce1f946.png)

## Measure of Success 
It can be fixed by adding "@types/sortablejs" to our projects dev dependencies for now, would like to not add this.

**Comment by jcfranco** [comment] 2021-09-10 05:27
@ethanbdev I can't reproduce this issue. Do you have an isolated test case I can take a look at? 

Here's the snippet I used to attempt to repro (using [Stencil's component starter](https://github.com/ionic-team/stencil-component-starter) as a base):

```tsx
import { Component, Prop, h } from '@stencil/core';
import { format } from '../../utils/utils';
import "@esri/calcite-components";

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true,
})
export class MyComponent {

  /**
   * Test prop 🧪 
   */
  valueList: HTMLCalciteValueListElement;

  /**
   * The first name
   */
  @Prop() first: string;

  /**
   * The middle name
   */
  @Prop() middle: string;

  /**
   * The last name
   */
  @Prop() last: string;

  private getText(): string {
    return format(this.first, this.middle, this.last);
  }

  render() {
    return <div>Hello, World! I'm {this.getText()}</div>;
  }
}
```

The build succeeds with the above. The type is also picked-up properly and the build will fail if I try to access non-existent props.

**Comment by ethanbdev** [comment] 2021-09-10 15:30
Hm, I am still getting it. In `calcite-value-list.d.ts` it has this import:
![image](https://user-images.githubusercontent.com/52869490/132878629-c8f0a90b-c1aa-4ac5-8c99-22bdc5827593.png)

To reproduce exactly, you could return a `HTMLCalciteValueListElement` from a private function, then call it from the render to render a value list
```ts
  private buildSeriesList(): HTMLCalciteValueListElement {
    return (
      <calcite-value-list dragEnabled onCalciteListOrderChange={this.onCalciteListOrderChange}>
        {this.buildSeriesListItem()}
      </calcite-value-list>
    );
  }
```

**Comment by jcfranco** [comment] 2021-09-10 17:18
I'm still not able to reproduce this after updating my test case:

```tsx
import { Component, Prop, h } from '@stencil/core';
import { format } from '../../utils/utils';
import "@esri/calcite-components"

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: true,
})
export class MyComponent {

  // omitted for brevity

  // sidebar: this returns a VNode and not an element
  private buildSeriesList(): HTMLCalciteValueListElement {
    return (
      <calcite-value-list>
        <calcite-value-list-item label="Dogs" description="Man's best friend" value="dogs"></calcite-value-list-item>
        <calcite-value-list-item label="Cats" description="Independent and fluffy" value="cats"></calcite-value-list-item>
      </calcite-value-list>
    );
  }

  render() {
    return <div>
      Hello, World! I'm {this.getText()}
      {this.buildSeriesList()}
    </div>;
  }
}
```

![Screen Shot 2021-09-10 at 9 58 31 AM](https://user-images.githubusercontent.com/197440/132891125-430476f0-a5a3-4183-81ec-85d4bcece82a.png)

---

Any chance something is referencing `calcite-value-list.d.ts` directly?

**Comment by ethanbdev** [comment] 2021-09-10 17:27
Okay, thanks for checking. I wonder if it is because the types are included in the tsconfig? I don't see any imports right from that type file.. Maybe this is not quite the right approach? 
```
{
  "extends": "../../tsconfig.json",
  "include": ["src"],
  "files": [
    "../../node_modules/@esri/calcite-components/dist/types/components.d.ts",
    "../../node_modules/arcgis-js-api/index.d.ts"
  ],
  "compilerOptions": {
    "target": "es2017",
    "isolatedModules": false
  }
}
```
iirc this is done to _not_ have to add an import but still get the types.

**Comment by jcfranco** [comment] 2021-09-10 17:50
I still can't repro after updating `tsconfig.json` to explicitly include the component types.

**Comment by jcfranco** [comment] 2021-09-10 18:12
I'm going to go ahead and close this since I can't proceed without a repro case. 

FWIW, here's my test case repo in case you wanted to take a stab at reproducing the issue there (and reopening this issue): https://github.com/jcfranco/repro-case-components-building-with-calcite-components.

**Closed by jcfranco** 2021-09-10 18:12 UTC
Labels: tooling, 1 - assigned, need more info

**Comment by ethanbdev** [comment] 2021-09-10 20:16
Okay, thanks for checking
