### ISSUE TITLE
InputMessage flashes on page load

### ISSUE THREAD

**Issue by nick-esri** [Esri/calcite-components#4323] opened 2022-03-29 15:57 UTC
### Actual Behavior

When defining an input message for validation- the message is initially inactive and hidden. On page load the input message is briefly displayed before being hidden leading to a flash / visual artifact. 

### Expected Behavior

The message should not show up at all on page load / refresh.

### Reproduction Sample

https://codepen.io/neilsonblack/pen/WNdOdqL

### Reproduction Steps

1. Open codepen
2. Click `Remove Input` button 
3. Click `Load Input` button - see the input message flash

### Reproduction Version

1.0.0-beta.80

**Comment by macandcheese** [comment] 2022-03-29 17:29
I think this may be a combination of https://github.com/Esri/calcite-components/issues/991 and, specifically to input message, this crazy animation that makes the root issue more noticeable : https://github.com/Esri/calcite-components/issues/4291

**Comment by nick-esri** [comment] 2022-03-29 18:18
Thanks @macandcheese - looks like the stencil fix we were waiting on for #991 was merged, also agree it would be nice to tone down the animation :+1:

**Comment by driskull** [comment] 2022-04-21 21:01
This seems like an error with the HTML in the codepen. If you remove all the `calcite-hydrated=""` then its fine.

**Comment by driskull** [comment] 2022-04-21 21:02
@benelan can we close this one?

**Comment by benelan** [comment] 2022-04-21 21:05
Thanks Matt, closing this issue as verified. The issue is resolved after removing `calcite-hydrated=""` from the repro sample.

**Closed by benelan** 2022-04-21 21:05 UTC
Labels: bug, 1 - assigned
