### ISSUE TITLE
calcite-slider: key-up catches focus from nearby input

### ISSUE THREAD

**Issue by AdelheidF** [Esri/calcite-components#7085] opened 2023-06-01 21:30 UTC
### Actual Behavior

Selecting the value in the input box and releasing the mouse button over the slider causes the slider to catch the focus.

![image](https://github.com/Esri/calcite-components/assets/44481292/54081b40-fad3-48b6-be60-e23d74d2238b)

cc @driskull 

### Expected Behavior

focus stays on input box so that I can edit the value

### Reproduction Sample

https://codepen.io/afreitag/pen/jOegOdO

### Reproduction Steps

Open codepen and read instructions.

### Reproduction Version

1.4.2

### Regression?

don't think so

### Priority impact

p3 - want for upcoming milestone

### Impact

annoying behavior

### Esri team

ArcGIS Map Viewer

**Comment by driskull** [comment] 2023-06-01 22:53
I can reproduce this pretty consistently by quickly dragging from the input to the slider.

I think the slider needs to update its logic to only honor the "dragUp" event if it started on the component. Currently, it seems like it will do the logic for dragging if the drag started elsewhere which is why the focus happens.

![Jun-01-2023 15-51-58](https://github.com/Esri/calcite-components/assets/1231455/2f31320c-d683-475c-826b-ed8b7e101656)

**Comment by driskull** [comment] 2023-06-01 23:11
Seems to be a duplicate of #5070.

Its actually because the label has two components inside of it.

**Comment by driskull** [comment] 2023-06-01 23:12
Closing in favor of above issue.

**Closed by driskull** 2023-06-01 23:12 UTC
Labels: bug, 0 - new, needs triage, ArcGIS Map Viewer, p3 - want for upcoming milestone
