### ISSUE TITLE
Bug: Date format is hard-coded as "mm/dd/yyyy" in textbox of Calcite-Date

### ISSUE THREAD

**Issue by zaramatheson** [Esri/calcite-components#1380] opened 2020-12-08 18:52 UTC
The date format is always "mm/dd/yyyy" when it should be localized. 

Related MV Beta issue: https://devtopia.esri.com/WebGIS/arcgis-webviewer-app/issues/1917

![image](https://user-images.githubusercontent.com/50747646/101527851-62510100-3943-11eb-9223-eb90f925d2ce.png)

@jcfranco

**Comment by julio8a** [comment] 2021-07-16 05:05
Is this issue still valid?

**Comment by macandcheese** [comment] 2021-12-21 18:18
@zaramatheson can you verify if this is still a valid issue? Thanks!

**Comment by zaramatheson** [comment] 2021-12-21 18:33
@macandcheese Yes it appears to still be valid:
![image](https://user-images.githubusercontent.com/50747646/146980901-035a81df-6404-48f1-93e3-fbbae0f5a1a6.png)

**Comment by macandcheese** [comment] 2021-12-21 18:37
Seems like we'll need to audit the `placeholder` values for each locale : https://github.com/Esri/calcite-components/tree/master/src/components/calcite-date-picker/assets/calcite-date-picker/nls

**Comment by benelan** [comment] 2022-02-15 22:11
closing as duplicate of #3531

**Closed by benelan** 2022-02-15 22:11 UTC
Labels: bug, 0 - new
