### ISSUE TITLE
Bug: calcite-slider missing rtl

### ISSUE THREAD

**Issue by dhrumil83** [Esri/calcite-components#990] opened 2020-09-15 16:43 UTC
calcite-slider does not flip on rtl.
Looking at the code here, seems like its missing.
https://github.com/Esri/calcite-components/blob/master/src/components/calcite-slider/calcite-slider.tsx

![image](https://user-images.githubusercontent.com/14285436/93239371-88497980-f737-11ea-8bf1-af3622526827.png)

**Comment by bstifle** [comment] 2021-01-27 21:28
@paulcpederson this is assigned to you and is `p-high` 

Has there been any movement? Thank you.

_end comment_

**Comment by paulcpederson** [comment] 2021-01-27 21:36
duplicate of https://github.com/Esri/calcite-components/issues/720

**Closed by paulcpederson** 2021-01-27 21:36 UTC
Labels: 1 - assigned, bug, design, p - high
