### ISSUE TITLE
Need option to ignore parent's overflow for popover-in-popover case

### ISSUE THREAD

**Issue by cont-kolomeets** [Esri/calcite-components#6622] opened 2023-03-21 13:21 UTC
### Actual Behavior

This could be related to https://github.com/Esri/calcite-components/issues/5877.

Our use case. We use an accordion inside a `div` element with `overflow:auto`. This is a very common use case, because the accordion can be very tall and we need a scroll. Inside the accordion we have a popover which also can bring up another popover. The 2nd popover refuses to be shown, even though there is plenty of space on the screen. This must not happen and doesn't make sense. Also it breaks the UI and can't be controlled by the developer. 

**At least we need an option to turn this kind of check off.**

See, the 2nd popover can't be shown. It's just broken UI for no good reason.

![image](https://user-images.githubusercontent.com/5318527/226617710-8100749c-d541-4929-990e-4a1fcf7f7ace.png)

This is all because the parent div has `overflow: auto`.

![image](https://user-images.githubusercontent.com/5318527/226617960-ee2b91ca-5913-4570-9453-a38c35dfc287.png)

### Expected Behavior

If I change to `overflow: visible`.

![image](https://user-images.githubusercontent.com/5318527/226618076-e5798d84-642a-4571-9d25-227ab110d1c0.png)

The 2nd popover can now be shown, but the tall accordion becomes unusable because there is no scroll.

We would expect to see this behavior regardless of the parent's overflow style.

![image](https://user-images.githubusercontent.com/5318527/226618129-869c8569-7ac7-4012-a6e6-d601fedf9c92.png)

### Reproduction Sample

https://codepen.io/cont-kolomeets/pen/ZEMqpJZ?editors=1000

### Reproduction Steps

See the sample.

### Reproduction Version

1.0.7

### Regression?

Unlikely

### Priority impact

p0 - emergency

### Impact

We can't build UI in our app because of this issue. We can't really use popovers.

### Esri team

ArcGIS Business/Community Analyst

**Comment by dingyuan** [comment] 2023-03-21 16:46
@jcfranco @macandcheese Can you please consider provide a fix for this? It is a **show stopper** for us.

**Comment by macandcheese** [comment] 2023-03-21 16:59
If you move the Popover elements outside of the Accordion element, it seems to work fine. Can you try something like this and let us know if it works for you?

![Screen Shot 2023-03-21 at 9 57 15 AM](https://user-images.githubusercontent.com/4733155/226684947-6b782e56-fd6e-462f-b955-53f64366c854.png)

https://codepen.io/mac_and_cheese/pen/dyqgzMG?editors=1000

**Comment by cont-kolomeets** [comment] 2023-03-22 02:29
@macandcheese Thanks! This seems like a workaround that we can use for now. The downside of this approach is that we have to take extra care of removing the popover, while in the original approach the popover would be removed automatically along with its reference element.
It still would be nice if we could place the popover inside and turn off the overflow check.

**Comment by geospatialem** [comment] 2023-03-30 17:05
Additional doc support is needed to describe workflow/structural guidelines.

**Comment by jcfranco** [comment] 2023-04-14 03:24
I think this is a duplicate of https://github.com/Esri/calcite-components/issues/5877 (see https://github.com/Esri/calcite-components/issues/5877#issuecomment-1507875159).

**Comment by geospatialem** [comment] 2023-04-20 21:47
Verified on the doc site via `next.sites`.

**Closed** 2023-04-20 21:59 UTC
Labels: docs, p - high, 4 - verified, has workaround, ArcGIS Business/Community Analyst, estimate - 2, p0 - emergency
