### ISSUE TITLE
calcite-stepper:  event "calciteStepperItemChange" was removed but seems very useful for certain scenarios

### ISSUE THREAD

**Issue by kevindoshier** [Esri/calcite-components#4733] opened 2022-06-14 20:23 UTC
### Actual Behavior

We are using the calcite-stepper and relying on the event "calciteStepperItemChange", but it was removed at some point but it seems to be a very useful event for certain scenarios such as the one we were using it for

### Expected Behavior

Would be nice if the stepper went back to emitting that event

### Reproduction Sample

https://codepen.io/pen?&editors=100

### Reproduction Steps

1. Try the link above to a basic sample for the stepper

### Reproduction Version

beta.82

**Comment by benelan** [comment] 2022-06-15 00:53
Closing as a duplicate of #4595, which I re-prioritized to this sprint

**Closed by benelan** 2022-06-15 00:53 UTC
Labels: bug, 0 - new, needs triage
